#include "plugin/builtin_operations.hpp"

namespace ps::plugin_internal {
Status register_builtin_operations(OperationRegistry* registry) {
  for (const auto function : {register_image_convolve_channels,
                              register_image_split_horizontal,
                              register_color_rgb_to_ycbcr420,
                              register_numeric_cast,
                              register_numeric_encode_range,
                              register_numeric_add,
                              register_numeric_subtract,
                              register_numeric_multiply,
                              register_numeric_divide,
                              register_numeric_clamp,
                              register_numeric_mean,
                              register_numeric_ordered_scan,
                              register_numeric_variance,
                              register_channel_extract,
                              register_channel_swizzle,
                              register_channel_merge,
                              register_alpha_associate,
                              register_alpha_unassociate,
                              register_color_rgb_to_xyz,
                              register_color_xyz_to_rgb,
                              register_color_xyz_to_lab,
                              register_color_lab_to_xyz,
                              register_color_assign,
                              register_mask_threshold,
                              register_mask_components,
                              register_component_count,
                              register_component_area,
                              register_component_bbox,
                              register_numeric_sample_expression,
                              register_lut_apply_1d,
                              register_image_exposure_gain,
                              register_image_opacity,
                              register_image_gaussian_blur,
                              register_image_mask,
                              register_image_source_over,
                              register_dependency_sampling,
                              register_image_downsample_box,
                              register_mask_downsample_box,
                              register_image_brush_circle,
                              register_curve_sample_linear,
                              register_curve_sample_monotone,
                              register_field_apply_lut_1d,
                              register_mask_invert,
                              register_mask_combine,
                              register_image_mix,
                              register_field_box_mean,
                              register_field_gaussian_blur,
                              register_mask_dilate,
                              register_mask_erode,
                              register_field_convolve,
                              register_field_correlate,
                              register_analysis_histogram,
                              register_analysis_histogram_out_of_range,
                              register_grade_levels,
                              register_numeric_minimum,
                              register_numeric_maximum,
                              register_numeric_abs,
                              register_field_smoothstep,
                              register_field_coordinate,
                              register_field_constant,
                              register_core_constant,
                              register_core_identity,
                              register_math_add,
                              register_core_delay,
                              register_core_gpu_fallback_probe}) {
    auto status = function(registry);
    if (!status.ok())
      return status;
  }
  return Status::success();
}
}  // namespace ps::plugin_internal
