if(NOT EXISTS "${VERSION_FILE}")
  message(FATAL_ERROR "Missing package version file")
endif()
function(check_version requested expected)
  set(PACKAGE_FIND_VERSION "${requested}")
  string(REPLACE "." ";" parts "${requested}")
  list(GET parts 0 PACKAGE_FIND_VERSION_MAJOR)
  list(GET parts 1 PACKAGE_FIND_VERSION_MINOR)
  list(GET parts 2 PACKAGE_FIND_VERSION_PATCH)
  set(PACKAGE_FIND_VERSION_COUNT 3)
  include("${VERSION_FILE}")
  if(NOT "${PACKAGE_VERSION_COMPATIBLE}" STREQUAL "${expected}")
    message(FATAL_ERROR "${requested}: compatibility=${PACKAGE_VERSION_COMPATIBLE}, expected ${expected}")
  endif()
  message(STATUS "request ${requested}: compatible=${PACKAGE_VERSION_COMPATIBLE}")
endfunction()
check_version("0.23.0" "FALSE")
check_version("0.24.0" "FALSE")
check_version("0.25.0" "FALSE")
check_version("0.26.0" "FALSE")
check_version("0.26.99" "FALSE")
check_version("0.27.0" "FALSE")
check_version("0.27.1" "FALSE")
check_version("0.28.0" "TRUE")
check_version("0.28.1" "FALSE")
check_version("0.29.0" "FALSE")
