if(NOT EXISTS "${VERSION_FILE}")
  message(FATAL_ERROR "Missing package version file")
endif()
function(check_version requested expected)
  set(PACKAGE_FIND_VERSION "${requested}")
  string(REPLACE "." ";" parts "${requested}")
  list(GET parts 0 PACKAGE_FIND_VERSION_MAJOR)
  list(GET parts 1 PACKAGE_FIND_VERSION_MINOR)
  list(GET parts 2 PACKAGE_FIND_VERSION_PATCH)
  set(PACKAGE_FIND_VERSION_COUNT 3)
  include("${VERSION_FILE}")
  if(NOT "${PACKAGE_VERSION_COMPATIBLE}" STREQUAL "${expected}")
    message(FATAL_ERROR "${requested}: compatibility=${PACKAGE_VERSION_COMPATIBLE}, expected ${expected}")
  endif()
  message(STATUS "request ${requested}: compatible=${PACKAGE_VERSION_COMPATIBLE}")
endfunction()
string(REPLACE "." ";" current_parts "${CURRENT_VERSION}")
list(GET current_parts 0 current_major)
list(GET current_parts 1 current_minor)
list(GET current_parts 2 current_patch)
math(EXPR next_minor "${current_minor} + 1")
math(EXPR next_patch "${current_patch} + 1")
check_version("${CURRENT_VERSION}" "TRUE")
check_version("${current_major}.${next_minor}.0" "FALSE")
check_version("${current_major}.${current_minor}.${next_patch}" "FALSE")
if(current_minor GREATER 0)
  math(EXPR previous_minor "${current_minor} - 1")
  check_version("${current_major}.${previous_minor}.0" "FALSE")
endif()
