#!/usr/bin/env bash

set -Eeuo pipefail

# @file build_integrity.sh
# @brief Build one CI producer and publish its complete post-build inventory.
# @note The default profile's strict build-smoke matrix is generated only after
#   the complete build, so POST_BUILD GoogleTest discoveries are authoritative.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=ci/scripts/common.sh
source "$SCRIPT_DIR/common.sh"

cd "$REPO_ROOT"

# @brief Persist one single-line build result to diagnostics and GitHub outputs.
# @param $1 Stable output key consumed by the workflow.
# @param $2 Nonempty single-line output value generated by tested repository code.
# @return Zero after all selected destinations are written, otherwise nonzero.
# @throws Nothing; invalid values and write failures return nonzero and terminate
#   the caller through strict shell mode.
# @note GITHUB_OUTPUT is optional for local-image execution. Output is written
#   synchronously and no descriptor or value survives the script process.
emit_output() {
  local key=$1
  local value=$2
  if [[ ! "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ||
    -z "$value" ||
    "$value" == *$'\n'* ||
    "$value" == *$'\r'* ]]; then
    echo "Refusing malformed build-integrity output '$key'." >&2
    return 2
  fi
  printf '%s=%s\n' "$key" "$value" |
    tee -a "$CI_ARTIFACT_DIR/outputs.log"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf '%s=%s\n' "$key" "$value" >> "$GITHUB_OUTPUT"
  fi
}

: > "$CI_ARTIFACT_DIR/outputs.log"

case "$CI_BUILD_PROFILE" in
  default)
    BUILD_TESTING=ON
    unset PHOTOSPIDER_BUILD_IPC || true
    ensure_ci_configured cmake_configure
    run_logged validate_profile_cache require_ci_profile_cache
    ensure_ci_targets build_required_targets \
      graph_cli \
      test_propagation \
      lifecycle_op_plugin \
      override_lifecycle_op_plugin \
      destroy_count_scheduler_plugin \
      cpu_work_stealing_example_plugin \
      gpu_pipeline_example_plugin \
      serial_debug_example_plugin
    ensure_ci_all build_all

    # @var build_smoke_matrix_file
    # @brief Strict matrix generated from the complete post-build CTest tree.
    # @note Its compact one-line JSON becomes the stable job output only after
    #   strict inventory validation succeeds.
    build_smoke_matrix_file="$CI_ARTIFACT_DIR/build_smoke_matrix.json"
    run_logged build_smoke_inventory \
      python3 -B "$SCRIPT_DIR/build_smoke_inventory.py" plan \
        --build-dir "$BUILD_DIR" \
        --ctest-executable "${CTEST_COMMAND:-ctest}" \
        --config "${CMAKE_BUILD_TYPE:-RelWithDebInfo}" \
        --label "$BUILD_SMOKE_LABEL" \
        --inventory-output "$CI_ARTIFACT_DIR/ctest_inventory.json" \
        --matrix-output "$build_smoke_matrix_file" \
        --names-output "$CI_ARTIFACT_DIR/build_smoke_names.z"
    mark_ci_build_reusable

    # @var build_smoke_matrix
    # @brief Validated single-line matrix value exposed to downstream CI jobs.
    # @note Command substitution removes the file's trailing newline; embedded
    #   line breaks are forbidden again by emit_output.
    build_smoke_matrix=$(<"$build_smoke_matrix_file")
    emit_output build_smoke_matrix "$build_smoke_matrix"
    echo "Default profile build and build-smoke inventory completed." |
      tee "$CI_ARTIFACT_DIR/summary.log"
    ;;
  *)
    echo "Unsupported CI_BUILD_PROFILE: $CI_BUILD_PROFILE" >&2
    exit 2
    ;;
esac
