#!/usr/bin/env bash

set -Eeuo pipefail

# @file build_integrity.sh
# @brief Build one CI producer and publish its complete post-build inventory.
# @note The default profile's strict build-smoke matrix is generated only after
#   the complete build, so POST_BUILD GoogleTest discoveries are authoritative.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=ci/scripts/common.sh
source "$SCRIPT_DIR/common.sh"

cd "$REPO_ROOT"

# @brief Create the exact producer build directory from an empty trusted state.
# @return Zero only for a new mode-0700 real directory below a real build root.
# @throws Nothing; cached, residual, symlinked, special, or aliased paths fail
#   before CMake can reuse configuration or artifact bytes.
# @note Hosted runners are normally ephemeral, but this explicit boundary also
#   makes reruns and future executor changes fail closed instead of signing a
#   build tree whose origin was not observed by this producer invocation.
prepare_fresh_producer_build() {
  local build_parent
  local build_parent_real
  local repository_real
  build_parent=${BUILD_DIR%/*}
  if [[ "$build_parent" == "$BUILD_DIR" || -z "$build_parent" ]]; then
    echo "Reusable producer build directory has no explicit parent." >&2
    return 1
  fi
  if [[ -e "$BUILD_DIR" || -L "$BUILD_DIR" ]]; then
    echo "Reusable producer refuses a cached or residual build directory: $BUILD_DIR" >&2
    return 1
  fi
  if [[ -L "$build_parent" ]]; then
    echo "Reusable producer build parent must not be a symlink." >&2
    return 1
  fi
  mkdir -p -- "$build_parent"
  if [[ ! -d "$build_parent" || -L "$build_parent" ]]; then
    echo "Reusable producer build parent is not a real directory." >&2
    return 1
  fi
  repository_real=$(cd -- "$REPO_ROOT" && pwd -P)
  build_parent_real=$(cd -- "$build_parent" && pwd -P)
  if [[ ${build_parent_real%/*} != "$repository_real" || ${build_parent_real##*/} != build ]]; then
    echo "Reusable producer build parent is not the repository's direct build child." >&2
    return 1
  fi
  mkdir -m 700 -- "$BUILD_DIR"
  if [[ ! -d "$BUILD_DIR" || -L "$BUILD_DIR" ]]; then
    echo "Reusable producer build directory is not a fresh real directory." >&2
    return 1
  fi
}

prepare_fresh_producer_build

# @brief Persist one single-line build result to diagnostics and GitHub outputs.
# @param $1 Stable output key consumed by the workflow.
# @param $2 Nonempty single-line output value generated by tested repository code.
# @return Zero after all selected destinations are written, otherwise nonzero.
# @throws Nothing; invalid values and write failures return nonzero and terminate
#   the caller through strict shell mode.
# @note GITHUB_OUTPUT is optional for local-image execution. Output is written
#   synchronously and no descriptor or value survives the script process.
emit_output() {
  local key=$1
  local value=$2
  if [[ ! "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ||
    -z "$value" ||
    "$value" == *$'\n'* ||
    "$value" == *$'\r'* ]]; then
    echo "Refusing malformed build-integrity output '$key'." >&2
    return 2
  fi
  printf '%s=%s\n' "$key" "$value" |
    tee -a "$CI_ARTIFACT_DIR/outputs.log"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf '%s=%s\n' "$key" "$value" >> "$GITHUB_OUTPUT"
  fi
}

: > "$CI_ARTIFACT_DIR/outputs.log"

case "$CI_BUILD_PROFILE" in
  default)
    BUILD_TESTING=ON
    unset PHOTOSPIDER_BUILD_IPC || true
    ensure_ci_configured cmake_configure
    run_logged validate_profile_cache require_ci_profile_cache
    capture_ci_target_inventory
    runtime_contract=$(ci_runtime_contract)
    printf 'runtime_contract=%s\n' "$runtime_contract" |
      tee "$CI_ARTIFACT_DIR/runtime_contract.log"
    run_logged validate_required_targets require_ci_targets \
      photospider_kernel \
      graph_cli \
      test_propagation \
      lifecycle_op_plugin \
      override_lifecycle_op_plugin
    ensure_ci_targets build_required_targets \
      photospider_kernel \
      graph_cli \
      test_propagation \
      lifecycle_op_plugin \
      override_lifecycle_op_plugin
    ensure_ci_all build_all

    # @var build_smoke_matrix_file
    # @brief Strict matrix generated from the complete post-build CTest tree.
    # @note Its compact one-line JSON becomes the stable job output only after
    #   strict inventory validation succeeds.
    build_smoke_matrix_file="$CI_ARTIFACT_DIR/build_smoke_matrix.json"
    run_logged build_smoke_inventory \
      python3 -B "$SCRIPT_DIR/build_smoke_inventory.py" plan \
        --build-dir "$BUILD_DIR" \
        --ctest-executable "${CTEST_COMMAND:-ctest}" \
        --config "${CMAKE_BUILD_TYPE:-RelWithDebInfo}" \
        --label "$BUILD_SMOKE_LABEL" \
        --inventory-output "$CI_ARTIFACT_DIR/ctest_inventory.json" \
        --matrix-output "$build_smoke_matrix_file" \
        --names-output "$CI_ARTIFACT_DIR/build_smoke_names.z"

    # @var ordinary_ctest_closure_file
    # @brief Canonical post-build ordinary CTest control/runtime closure.
    # @note The closure is written into producer-generated inventory before
    #   reusable identity measurement. It excludes only the exact build-smoke
    #   label and binds every ordinary executable/include/data/runtime input.
    ordinary_ctest_closure_file=
    ordinary_ctest_closure_file="$BUILD_DIR/generated/ci_inventory/ordinary_ctest_closure_v1.json"
    run_logged ordinary_ctest_runtime_closure \
      python3 -B "$SCRIPT_DIR/ctest_runtime_closure.py" create \
        --source-root "$REPO_ROOT" \
        --build-root "$BUILD_DIR" \
        --inventory "$CI_ARTIFACT_DIR/ctest_inventory.json" \
        --output "$ordinary_ctest_closure_file" \
        --config "${CMAKE_BUILD_TYPE:-RelWithDebInfo}"

    # @var consumer_build_smoke_matrix_file
    # @brief Matrix containing only smokes that need the minimal CTest-control
    #   artifact; producer-local roles remain in the original CTest tree.
    # @note The protected routing lock is an explicitly temporary current-main
    #   bridge. The candidate-owned versioned matrix replaces it before cleanup.
    consumer_build_smoke_matrix_file=
    consumer_build_smoke_matrix_file="$CI_ARTIFACT_DIR/consumer_build_smoke_matrix.json"
    # @var dedicated_build_smoke_matrix_file
    # @brief Exact installed-package build-smoke matrix output.
    # @note The protected lock requires its current-main identity exactly once.
    dedicated_build_smoke_matrix_file=
    dedicated_build_smoke_matrix_file="$CI_ARTIFACT_DIR/dedicated_build_smoke_matrix.json"
    # @var openexr_build_smoke_matrix_file
    # @brief Exact cache-only OpenEXR build-smoke matrix output.
    # @note It is consumed by the dedicated source-tree runner and never by the
    #   ordinary CTest-control artifact path.
    openexr_build_smoke_matrix_file=
    openexr_build_smoke_matrix_file="$CI_ARTIFACT_DIR/openexr_build_smoke_matrix.json"
    producer_build_smoke_names_file=
    producer_build_smoke_names_file="$CI_ARTIFACT_DIR/producer_build_smoke_names.z"
    run_logged route_build_smokes \
      python3 -B "$SCRIPT_DIR/build_smoke_route.py" \
        --matrix "$build_smoke_matrix_file" \
        --lock "$REPO_ROOT/ci/locks/build-smoke-routing.json" \
        --consumer-matrix "$consumer_build_smoke_matrix_file" \
        --dedicated-matrix "$dedicated_build_smoke_matrix_file" \
        --openexr-matrix "$openexr_build_smoke_matrix_file" \
        --producer-names "$producer_build_smoke_names_file"

    # @var producer_smoke_index
    # @brief Stable local counter used only to separate producer-smoke logs.
    # @note Exact test names remain NUL-delimited argv data and are revalidated
    #   against fresh CTest JSON before numeric-index execution.
    producer_smoke_index=0
    while IFS= read -r -d '' producer_smoke_name; do
      producer_smoke_index=$((producer_smoke_index + 1))
      run_logged "producer_build_smoke_$producer_smoke_index" \
        python3 -B "$SCRIPT_DIR/build_smoke_inventory.py" run \
          --build-dir "$BUILD_DIR" \
          --ctest-executable "${CTEST_COMMAND:-ctest}" \
          --config "${CMAKE_BUILD_TYPE:-RelWithDebInfo}" \
          --label "$BUILD_SMOKE_LABEL" \
          --inventory-output \
            "$CI_ARTIFACT_DIR/producer-smoke-$producer_smoke_index-inventory.json" \
          --selection-output \
            "$CI_ARTIFACT_DIR/producer-smoke-$producer_smoke_index-selection.json" \
          --test-name "$producer_smoke_name"
    done < "$producer_build_smoke_names_file"
    if ((producer_smoke_index == 0)); then
      echo "Protected routing produced no producer-local build smoke." >&2
      exit 1
    fi

    # @var installed_prefix
    # @brief Fresh package payload archived separately from runtime/CTest data.
    # @note The producer does not execute StaticProductConsumerSmoke. Its fresh
    #   installed prefix and exact cache/header metadata are archived for the
    #   dedicated downstream consumer to exercise in the same image digest.
    installed_prefix="$REPO_ROOT/CI-results/installed-prefix-default"
    if [[ -e "$installed_prefix" || -L "$installed_prefix" ]]; then
      echo "Targeted installed prefix contains residual or aliased state." >&2
      exit 1
    fi
    run_logged create_installed_prefix \
      cmake --install "$BUILD_DIR" --prefix "$installed_prefix"
    mark_ci_build_reusable

    # @var build_smoke_matrix
    # @brief Validated single-line matrix value exposed to downstream CI jobs.
    # @note Command substitution removes the file's trailing newline; embedded
    #   line breaks are forbidden again by emit_output.
    build_smoke_matrix=$(<"$consumer_build_smoke_matrix_file")
    emit_output build_smoke_matrix "$build_smoke_matrix"
    dedicated_build_smoke_matrix=$(<"$dedicated_build_smoke_matrix_file")
    emit_output dedicated_build_smoke_matrix \
      "$dedicated_build_smoke_matrix"
    openexr_build_smoke_matrix=$(<"$openexr_build_smoke_matrix_file")
    emit_output openexr_build_smoke_matrix \
      "$openexr_build_smoke_matrix"
    {
      echo "Default profile build and build-smoke inventory completed."
      echo "Runtime validation contract: $runtime_contract"
    } | tee "$CI_ARTIFACT_DIR/summary.log"
    ;;
  *)
    echo "Unsupported CI_BUILD_PROFILE: $CI_BUILD_PROFILE" >&2
    exit 2
    ;;
esac
