#!/usr/bin/env bash

set -Eeuo pipefail

# @file runtime_capability_test.sh
# @brief Regress runtime target discovery, trust export, and CLI config emission.
# @note The test uses only disposable target-help and trust-material fixtures;
#   it writes no source or build state.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/photospider-runtime-capability.XXXXXX")
CI_ARTIFACT_DIR="$TEST_ROOT/artifacts"
BUILD_DIR="$TEST_ROOT/build"
mkdir -p "$CI_ARTIFACT_DIR" "$BUILD_DIR"
# shellcheck source=ci/scripts/common.sh
source "$SCRIPT_DIR/common.sh"

pass_count=0

# @var TRUST_TEST_REPO_ROOT
# @brief Disposable repository root used only by trust-export regressions.
# @note The fixture keeps generated trust material out of the source tree and
#   is removed with TEST_ROOT by the process EXIT trap.
TRUST_TEST_REPO_ROOT="$TEST_ROOT/repository"

# @var TRUST_TEST_MANIFEST
# @brief Canonical disposable manifest path expected by the CI trust helper.
# @note This path mirrors the build-tree layout generated by CMake.
TRUST_TEST_MANIFEST="$BUILD_DIR/generated/plugin_trust/manifest.txt"

# @var TRUST_TEST_SIGNATURE
# @brief Canonical disposable detached-signature path for trust regressions.
# @note The regression validates file presence and shape, not cryptography.
TRUST_TEST_SIGNATURE="$BUILD_DIR/generated/plugin_trust/signature.hex"

# @var TRUST_TEST_PUBLIC_KEY
# @brief Canonical disposable public-key path expected by the CI trust helper.
# @note The file contains synthetic nonempty text because production parsing is
#   outside this shell helper's boundary.
TRUST_TEST_PUBLIC_KEY=
TRUST_TEST_PUBLIC_KEY="$TRUST_TEST_REPO_ROOT/tests/fixtures/trust/"
TRUST_TEST_PUBLIC_KEY+="test_ed25519_public_key.pem"

# @brief Remove the disposable test root.
# @return Nothing.
# @throws Nothing; cleanup is best effort after a recorded test result.
cleanup() {
  rm -rf -- "$TEST_ROOT"
}
trap cleanup EXIT

# @brief Stop the regression with one diagnostic.
# @param $1 Failure description.
# @return Does not return.
# @throws Nothing; exits the script with status one.
fail() {
  echo "FAIL: $1" >&2
  exit 1
}

# @brief Record one passing case.
# @param $1 Stable case label.
# @return Zero.
# @throws Nothing.
pass() {
  pass_count=$((pass_count + 1))
  echo "PASS: $1"
}

# @brief Replace the parser input with exact target-help lines.
# @param $@ Target-help lines.
# @return Zero after writing the fixture.
# @throws Nothing; filesystem failure terminates through strict shell mode.
write_inventory() {
  printf '%s\n' "$@" > "$CI_TARGET_INVENTORY_FILE"
}

# @brief Require an exact string equality.
# @param $1 Actual value.
# @param $2 Expected value.
# @param $3 Case label.
# @return Zero when equal.
# @throws Nothing; mismatch exits through fail.
assert_equal() {
  local actual=$1
  local expected=$2
  local label=$3
  [[ "$actual" == "$expected" ]] ||
    fail "$label: expected '$expected', got '$actual'"
}

# @brief Require one fixed string in a file.
# @param $1 File path.
# @param $2 Fixed expected text.
# @param $3 Case label.
# @return Zero when present.
# @throws Nothing; mismatch exits through fail.
assert_contains() {
  local file=$1
  local text=$2
  local label=$3
  grep -Fq -- "$text" "$file" || fail "$label: missing '$text'"
}

# @brief Require one fixed string to be absent from a file.
# @param $1 File path.
# @param $2 Forbidden fixed text.
# @param $3 Case label.
# @return Zero when absent.
# @throws Nothing; mismatch exits through fail.
assert_not_contains() {
  local file=$1
  local text=$2
  local label=$3
  if grep -Fq -- "$text" "$file"; then
    fail "$label: unexpected '$text'"
  fi
}

# @brief Replace all inherited plugin-trust variables with sentinel values.
# @return Zero after exporting the three sentinels.
# @throws Nothing; shell assignment failures terminate through strict mode.
# @note No sentinel names a usable trust artifact, which makes an unexpected
#   overwrite or consumer-visible inherited value unambiguous.
set_inherited_trust_environment() {
  export PHOTOSPIDER_PLUGIN_TRUST_MANIFEST=inherited-manifest
  export PHOTOSPIDER_PLUGIN_TRUST_SIGNATURE=inherited-signature
  export PHOTOSPIDER_PLUGIN_TRUST_PUBLIC_KEY=inherited-public-key
}

# @brief Require every plugin-trust variable to retain its inherited sentinel.
# @param $1 Stable case label.
# @return Zero when all three values remain unchanged.
# @throws Nothing; a mismatch exits through fail.
# @note This assertion covers both capability no-ops and fail-closed material
#   validation before any partial environment export.
assert_inherited_trust_environment() {
  local label=$1
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_MANIFEST" inherited-manifest \
    "$label-manifest"
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_SIGNATURE" inherited-signature \
    "$label-signature"
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_PUBLIC_KEY" inherited-public-key \
    "$label-public-key"
}

# @brief Write a complete nonempty synthetic trust-material tuple.
# @return Zero after creating all canonical fixture paths.
# @throws Nothing; filesystem failures terminate through strict shell mode.
# @note The production helper validates material shape before a consumer starts;
#   signature contents are intentionally outside this shell regression.
write_complete_trust_material() {
  mkdir -p "$(dirname -- "$TRUST_TEST_MANIFEST")" \
    "$(dirname -- "$TRUST_TEST_PUBLIC_KEY")"
  printf 'synthetic manifest\n' > "$TRUST_TEST_MANIFEST"
  printf 'synthetic signature\n' > "$TRUST_TEST_SIGNATURE"
  printf 'synthetic public key\n' > "$TRUST_TEST_PUBLIC_KEY"
}

# @brief Require trust export to fail before changing inherited variables.
# @param $1 Stable case label and log basename.
# @param $2 Canonical material or inventory path expected in the diagnostic.
# @param $3 Exact helper status expected for this failure class.
# @return Zero after observing a nonzero helper result and exact diagnostic.
# @throws Nothing; unexpected success or output exits through fail.
# @note The helper runs in the current shell so partial environment mutation
#   cannot be hidden by command-substitution process isolation.
expect_trust_export_failure() {
  local label=$1
  local expected_path=$2
  local expected_status=$3
  local failure_log="$TEST_ROOT/$label.log"
  local status
  set +e
  export_ci_plugin_trust_environment > "$failure_log" 2>&1
  status=$?
  set -e
  ((status != 0)) || fail "$label: invalid trust state was accepted"
  assert_equal "$status" "$expected_status" "$label-status"
  assert_contains "$failure_log" "$expected_path" "$label-diagnostic"
  assert_inherited_trust_environment "$label-environment"
}

# @brief Require runtime-contract detection to fail.
# @param $1 Case label.
# @return Zero after a nonzero classifier result.
# @throws Nothing; unexpected success exits through fail.
expect_contract_failure() {
  local label=$1
  local output
  local status
  set +e
  output=$(ci_runtime_contract 2>&1)
  status=$?
  set -e
  ((status != 0)) || fail "$label: invalid inventory was accepted"
  [[ "$output" == *"Invalid runtime capability inventory:"* ]] ||
    fail "$label: missing fail-closed diagnostic"
  pass "$label"
}

# @brief Exercise Make-style exact legacy-scheduler discovery.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
test_legacy_make_inventory() {
  write_inventory \
    "$ cmake --build /tmp/build --target help" \
    "The following are some of the valid targets for this Makefile:" \
    "... test_scheduler" \
    "... test_scheduler_plugin_loader" \
    "... destroy_count_scheduler_plugin" \
    "... test_scheduler_extra"
  local contract
  contract=$(ci_runtime_contract)
  assert_equal "$contract" legacy_scheduler legacy-make-contract
  ci_target_exists test_scheduler ||
    fail "legacy-make-contract: exact target was not found"
  if ci_target_exists test_policy_execution; then
    fail "legacy-make-contract: absent policy target was found"
  fi
  pass legacy-make-contract
}

# @brief Exercise Ninja-style exact policy/execution discovery.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
test_policy_ninja_inventory() {
  write_inventory \
    "[1/1] All primary targets available:" \
    "test_policy_execution: phony" \
    "test_policy_registry: phony" \
    "test_policy_plugin: phony" \
    "test_policy_execution_extra: phony"
  local contract
  contract=$(ci_runtime_contract)
  assert_equal "$contract" policy_execution policy-ninja-contract
  ci_target_exists test_policy_execution ||
    fail "policy-ninja-contract: exact target was not found"
  if ci_target_exists test_scheduler; then
    fail "policy-ninja-contract: absent scheduler target was found"
  fi
  pass policy-ninja-contract
}

# @brief Exercise partial, mixed, and empty fail-closed inventories.
# @return Zero after recording all cases.
# @throws Nothing; assertion failures exit through fail.
test_invalid_inventories() {
  write_inventory \
    "... test_scheduler" \
    "... test_scheduler_plugin_loader"
  expect_contract_failure partial-legacy-contract

  write_inventory \
    "... test_scheduler" \
    "... test_scheduler_plugin_loader" \
    "... destroy_count_scheduler_plugin" \
    "... test_policy_execution" \
    "... test_policy_registry" \
    "... test_policy_plugin"
  expect_contract_failure mixed-runtime-contract

  write_inventory "... graph_cli"
  expect_contract_failure absent-runtime-contract
}

# @brief Exercise complete required-target validation.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
test_required_targets() {
  local failure_log="$TEST_ROOT/required-targets-failure.log"
  local status
  write_inventory \
    "... photospider_kernel" \
    "... graph_cli"
  require_ci_targets photospider_kernel graph_cli ||
    fail "required-targets: complete inventory was rejected"
  set +e
  require_ci_targets photospider_kernel missing_target \
    > "$failure_log" 2>&1
  status=$?
  set -e
  ((status != 0)) ||
    fail "required-targets: absent target was accepted"
  assert_contains "$failure_log" \
    "Required configured CMake target is missing: missing_target" \
    required-targets
  pass required-targets
}

# @brief Exercise mutually exclusive legacy and policy CLI configurations.
# @return Zero after recording both cases.
# @throws Nothing; assertion failures exit through fail.
test_cli_configs() {
  local legacy_config="$TEST_ROOT/legacy.yaml"
  local policy_config="$TEST_ROOT/policy.yaml"
  local invalid_log="$TEST_ROOT/invalid-config.log"
  local status

  write_cli_config "$legacy_config" "$TEST_ROOT/cache-legacy" \
    legacy_scheduler
  assert_contains "$legacy_config" \
    "scheduler_hp_type: cpu_work_stealing" legacy-cli-config
  assert_not_contains "$legacy_config" "policy_dirs:" legacy-cli-config
  assert_not_contains "$legacy_config" \
    "execution_worker_count:" legacy-cli-config
  pass legacy-cli-config

  write_cli_config "$policy_config" "$TEST_ROOT/cache-policy" \
    policy_execution
  assert_contains "$policy_config" "policy_dirs:" policy-cli-config
  assert_contains "$policy_config" \
    "policy_interactive_type: fifo" policy-cli-config
  assert_contains "$policy_config" \
    "policy_throughput_type: fifo" policy-cli-config
  assert_contains "$policy_config" \
    "execution_worker_count: 0" policy-cli-config
  assert_not_contains "$policy_config" "scheduler_dirs:" policy-cli-config
  assert_not_contains "$policy_config" \
    "scheduler_worker_count:" policy-cli-config
  pass policy-cli-config

  set +e
  write_cli_config "$TEST_ROOT/invalid.yaml" "$TEST_ROOT/cache-invalid" \
    unsupported_contract > "$invalid_log" 2>&1
  status=$?
  set -e
  ((status != 0)) ||
    fail "invalid-cli-config: unsupported contract was accepted"
  assert_contains "$invalid_log" \
    "Unsupported CI runtime contract: unsupported_contract" \
    invalid-cli-config
  pass invalid-cli-config
}

# @brief Exercise a pre-trust policy inventory as an exact capability no-op.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
# @note Policy markers alone do not authorize trust export; only the exact
#   test_plugin_trust_bundle target enables the newer fixture contract.
test_pretrust_policy_trust_noop() {
  REPO_ROOT="$TRUST_TEST_REPO_ROOT"
  write_inventory \
    "test_policy_execution: phony" \
    "test_policy_registry: phony" \
    "test_policy_plugin: phony" \
    "graph_cli: phony"
  set_inherited_trust_environment
  export_ci_plugin_trust_environment ||
    fail "pretrust-policy-trust-noop: absent capability did not no-op"
  assert_inherited_trust_environment pretrust-policy-trust-noop
  pass pretrust-policy-trust-noop
}

# @brief Exercise missing, empty, and nonregular trust material fail-closed.
# @return Zero after recording the combined material-shape case.
# @throws Nothing; assertion failures exit through fail.
# @note The exact trust-bundle capability is present for every subcase, so none
#   may fall back to the pre-trust no-op behavior.
test_trust_material_failures() {
  write_inventory \
    "test_policy_execution: phony" \
    "test_policy_registry: phony" \
    "test_policy_plugin: phony" \
    "test_plugin_trust_bundle: phony"
  mkdir -p "$(dirname -- "$TRUST_TEST_MANIFEST")" \
    "$(dirname -- "$TRUST_TEST_PUBLIC_KEY")"

  printf 'synthetic signature\n' > "$TRUST_TEST_SIGNATURE"
  printf 'synthetic public key\n' > "$TRUST_TEST_PUBLIC_KEY"
  set_inherited_trust_environment
  expect_trust_export_failure trust-material-missing \
    "$TRUST_TEST_MANIFEST" 1

  printf 'synthetic manifest\n' > "$TRUST_TEST_MANIFEST"
  : > "$TRUST_TEST_SIGNATURE"
  set_inherited_trust_environment
  expect_trust_export_failure trust-material-empty \
    "$TRUST_TEST_SIGNATURE" 1

  printf 'synthetic signature\n' > "$TRUST_TEST_SIGNATURE"
  rm -f -- "$TRUST_TEST_PUBLIC_KEY"
  mkdir -- "$TRUST_TEST_PUBLIC_KEY"
  set_inherited_trust_environment
  expect_trust_export_failure trust-material-nonregular \
    "$TRUST_TEST_PUBLIC_KEY" 1
  rmdir -- "$TRUST_TEST_PUBLIC_KEY"
  pass trust-material-fail-closed
}

# @brief Exercise complete trust export and inherited-value replacement.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
# @note Successful export must publish only canonical build/source fixture
#   paths, never caller-provided inherited values.
test_complete_trust_export() {
  write_inventory \
    "test_policy_execution: phony" \
    "test_policy_registry: phony" \
    "test_policy_plugin: phony" \
    "test_plugin_trust_bundle: phony"
  write_complete_trust_material
  set_inherited_trust_environment
  export_ci_plugin_trust_environment ||
    fail "complete-trust-export: complete material was rejected"
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_MANIFEST" \
    "$TRUST_TEST_MANIFEST" complete-trust-export-manifest
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_SIGNATURE" \
    "$TRUST_TEST_SIGNATURE" complete-trust-export-signature
  assert_equal "$PHOTOSPIDER_PLUGIN_TRUST_PUBLIC_KEY" \
    "$TRUST_TEST_PUBLIC_KEY" complete-trust-export-public-key
  pass complete-trust-export
}

# @brief Exercise legacy runtime inventory isolation from trust export.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
# @note Complete material remains available from the prior case, proving that
#   target absence, rather than file coincidence, keeps legacy behavior intact.
test_legacy_trust_noop() {
  write_inventory \
    "... test_scheduler" \
    "... test_scheduler_plugin_loader" \
    "... destroy_count_scheduler_plugin"
  set_inherited_trust_environment
  export_ci_plugin_trust_environment ||
    fail "legacy-trust-noop: absent capability did not no-op"
  assert_inherited_trust_environment legacy-trust-noop
  pass legacy-trust-noop
}

# @brief Exercise a missing target inventory as a fail-closed gate error.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
# @note Complete trust material remains present, so inventory absence cannot be
#   mistaken for either target absence or sufficient export authority.
test_missing_trust_inventory() {
  rm -f -- "$CI_TARGET_INVENTORY_FILE"
  set_inherited_trust_environment
  expect_trust_export_failure missing-trust-inventory \
    "$CI_TARGET_INVENTORY_FILE" 2
  pass missing-trust-inventory
}

# @brief Exercise an unparseable target inventory as a fail-closed gate error.
# @return Zero after recording the case.
# @throws Nothing; assertion failures exit through fail.
# @note A valid-looking trust target cannot authorize export when another
#   record proves that the captured inventory is structurally contaminated.
test_malformed_trust_inventory() {
  write_inventory \
    "test_plugin_trust_bundle: phony" \
    "not a CMake target inventory"
  set_inherited_trust_environment
  expect_trust_export_failure malformed-trust-inventory \
    "$CI_TARGET_INVENTORY_FILE" 2
  pass malformed-trust-inventory
}

# @brief Run every runtime capability regression.
# @return Zero after printing the exact pass count.
# @throws Nothing; a child assertion exits the script.
main() {
  test_legacy_make_inventory
  test_policy_ninja_inventory
  test_invalid_inventories
  test_required_targets
  test_cli_configs
  test_pretrust_policy_trust_noop
  test_trust_material_failures
  test_complete_trust_export
  test_legacy_trust_noop
  test_missing_trust_inventory
  test_malformed_trust_inventory
  printf 'All %d runtime capability cases passed.\n' "$pass_count"
}

main "$@"
