#!/usr/bin/env python3
"""Independent fixed-seed FMT-09 sweep; formulas from fmt09_reference.py.

Every expected result must agree at 180/360 decimal digits. Samples combine
uniform and logarithmic distributions, not cached C++ implementation results.
This fixture is a reproducible test corpus, not a proof over the whole domain.
"""
import argparse
import random
from pathlib import Path
import mpmath as mp
import fmt09_reference as oracle


def generate(samples=128, table=False):
    rng = random.Random(0xF090925)
    definitions = [(k, 2.2, 0, .1, 100.) for k in range(10)]
    definitions += [(1, 2., 0, .1, 100.), (4, 2.2, 1, .1, 100.),
                    (4, 2.2, 2, .1, 100.)]
    cases = []
    for k, g, v, lb, lw in definitions:
        for encode in (False, True):
            for narrow in (False, True):
                for i in range(samples):
                    sample = rng.random()
                    if i % 2 == 0:
                        u = sample
                    else:
                        # Host libm pow differs by one ULP between macOS and
                        # FreeBSD/Linux. Pin the binary64 exponent, then round
                        # high-precision 2**exponent directly to binary64.
                        exponent = -24 * sample
                        rounded = []
                        for precision in (180, 360):
                            with mp.workdps(precision):
                                rounded.append(oracle.rn(
                                    mp.power(2, oracle.exact(exponent)), False))
                        if rounded[0] != rounded[1]:
                            raise RuntimeError('sweep input precision disagreement')
                        u = oracle.value(rounded[0], False)
                    x = lb + (lw - lb) * u if k == 5 and encode else (
                        10000 * u if k == 6 and encode else u)
                    cases.append((k, encode, narrow, g, v, lb, lw, oracle.bits(x, narrow)))
    expected = None
    for precision in (180, 360):
        mp.mp.dps = precision
        beta = mp.findroot(lambda b: 10 * b ** (mp.mpf(11) / 20) - 1 - mp.mpf(11) * b / 2,
                           (mp.mpf('.018'), mp.mpf('.019')))
        current = []
        for k, e, n, g, v, lb, lw, bits in cases:
            y = oracle.real(k, e, oracle.exact(oracle.value(bits, n)), oracle.exact(g),
                            v, oracle.exact(lb), oracle.exact(lw), beta)
            current.append(oracle.rn(y, n))
        if expected is not None and expected != current:
            raise RuntimeError('independent sweep precision disagreement')
        expected = current
    if table:
        return '\n'.join(' '.join(map(str, (k, int(e), int(n), g, v, lb, lw, b, r)))
                         for (k, e, n, g, v, lb, lw, b), r in zip(cases, expected)) + '\n'
    lines = ['// Generated by tests/oracles/fmt09_sweep.py; seed 0xF090925; 180/360 dps.',
             '#pragma once', '#include "fmt09_golden.hpp"', 'namespace fmt09_test {',
             'inline constexpr Case sweep[] = {']
    for (k, e, n, g, v, lb, lw, b), r in zip(cases, expected):
        lines.append(f'  {{{k}, {str(e).lower()}, {str(n).lower()}, {g.hex()}, {v}, '
                     f'{lb.hex()}, {lw.hex()}, UINT64_C(0x{b:016x}), UINT64_C(0x{r:016x})}},')
    return '\n'.join(lines + ['};', '}  // namespace fmt09_test', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--samples', type=int, default=128)
    parser.add_argument('--table', type=Path)
    args = parser.parse_args()
    if args.samples < 128 or args.samples > 65536:
        parser.error('samples must be in 128..65536')
    if args.table:
        args.table.write_text(generate(args.samples, table=True))
        print(f'Wrote independent table to {args.table}')
        raise SystemExit(0)
    if args.samples != 128:
        parser.error('nondefault samples requires --table')
    path = Path(__file__).resolve().parents[1] / 'fixtures/fmt09_sweep.hpp'
    text = generate()
    if args.check:
        if path.read_text() != text:
            raise RuntimeError('stale sweep fixture')
        print('FMT-09 6,656-case independent sweep verified')
    else:
        path.write_text(text)
        print(f'Wrote {text.count("UINT64_C") // 2} independent sweep cases')
