#!/usr/bin/env python3
"""Generate/certify the 4096-bit BT.2020 smooth-beta isolating interval.
Only integer arithmetic is used for the root certificate. No third-party package.
The defining polynomial is strictly increasing in the chosen [0.018,0.019]
bracket: the original function derivative 5.5*(beta**(-9/20)-1) is positive.
"""
from pathlib import Path
import argparse

BITS = 4096

def polynomial(n, d):
    # (10*x**(11/20))**20 - (1+11*x/2)**20, denominator 2**20*d**20.
    return 20**20 * n**11 * d**9 - (2*d + 11*n)**20

def generate():
    d = 1 << BITS
    lo, hi = (18*d)//1000, (19*d)//1000 + 1
    assert polynomial(lo, d) < 0 < polynomial(hi, d)
    while hi - lo > 1:
        mid = (lo + hi)//2
        if polynomial(mid, d) < 0: lo = mid
        else: hi = mid
    assert polynomial(lo, d) < 0 < polynomial(hi, d)
    words = [(lo >> (64*i)) & ((1 << 64)-1) for i in range(64)]
    rows = ["    " + ", ".join(f"UINT64_C(0x{x:016x})" for x in words[i:i+3])
            for i in range(0, 64, 3)]
    return ('// Generated by tests/oracles/fmt09_constants.py; exact integer certificate.\n'
            '#pragma once\n#include <array>\n#include <cstdint>\n'
            'namespace ps::plugin_internal::transfer_ops {\n'
            'inline constexpr std::array<std::uint64_t, 64> beta_floor_4096{\n' +
            ',\n'.join(rows) + '\n};\n}  // namespace ps::plugin_internal::transfer_ops\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[2]/'plugins/ops/02-format-color/transfer_constants.hpp'
    text = generate()
    if args.check:
        assert path.read_text() == text, 'constant certificate mismatch'
        print('BT.2020 4096-bit integer root certificate: PASS')
    else:
        path.write_text(text)
