#!/usr/bin/env python3
"""Independent Python integer divmod fixtures for the compact strict divider."""
import argparse
import random
from pathlib import Path


def generate():
    rng = random.Random(909263)
    inputs = []
    for i in range(160):
        n = rng.getrandbits(64 * (1 + i % 8))
        d = rng.getrandbits(64 * (1 + (i // 8) % 8)) or 1
        if i % 13 == 0:
            n = (1 << 512) - 1
        if i % 17 == 0:
            d = (1 << 64) - 1
        inputs.append((n, d))
    b = 1 << 64
    h = b // 2
    # One/two trial quotient corrections, low-word add-back, normalized
    # numerator carry beyond the eight stored words, and exact division.
    inputs += [((h - 1) * b * b + (b - 1) * b, h * b + b - 1),
               ((h - 1) * b * b, h * b + b - 1),
               (h * b * b + b - 2, h * b * b + b - 1),
               (b**8 - 1, b**6 + 7), (b**7, b**3)]
    lines = ['// Generated by tests/oracles/fmt09_division.py; Python divmod.',
             '#pragma once', '#include <cstdint>', 'namespace fmt09_test {',
             'inline constexpr std::uint64_t division[][4][8] = {']
    for n, d in inputs:
        q, r = divmod(n, d)
        arrays = []
        for value in (n, d, q, r):
            arrays.append('{' + ','.join(
                f'UINT64_C(0x{(value >> (64 * j)) & (b - 1):016x})'
                for j in range(8)) + '}')
        lines.append('  {' + ','.join(arrays) + '},')
    return '\n'.join(lines + ['};', '}  // namespace fmt09_test', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'fixtures/fmt09_division.hpp'
    text = generate()
    if args.check:
        if target.read_text() != text:
            raise RuntimeError('stale integer division oracle')
        print('165 Python divmod cases verified')
    else:
        target.write_text(text)
