#!/usr/bin/env python3
"""Exercise the installed OpenCV/YAML-disabled Host product."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath, PureWindowsPath

from cmake_build_smoke_support import (
    producer_osx_architecture_arguments,
)


#: @brief Build-relative directory containing CMake-owned consumer manifests.
#: @note The directory is generated by the disposable consumer configure and
#:   is never installed or retained after the smoke.
CONSUMER_INVENTORY_RELATIVE_DIRECTORY = Path("generated/ci_inventory")
#: @brief Configure-time manifest containing the exact declared target order.
#: @note CMake derives this file from the same single target list that creates
#:   the executables and the configuration-specific target-file manifest.
CONSUMER_TARGET_DECLARATION_MANIFEST_NAME = "consumer_targets.txt"
#: @brief Exact first record required by the declaration manifest.
#: @note Every following record contains one canonical local target name.
CONSUMER_TARGET_DECLARATION_HEADER = "# target"
#: @brief Prefix for configuration-specific target-file manifest basenames.
#: @note The validated configuration and ``.tsv`` suffix are appended by the
#:   reader; CMake uses the matching ``$<CONFIG>`` expression when generating.
CONSUMER_TARGET_FILE_MANIFEST_PREFIX = "consumer_target_files-"
#: @brief Exact first record required by the target-file TSV manifest.
#: @note Each later record binds one target to CMake's configured target
#:   filename and full target path. No comment, blank, or repeated-header
#:   record is legal after this line.
CONSUMER_TARGET_FILE_MANIFEST_HEADER = (
    "# target\tconfigured executable filename\tconfigured executable"
)
#: @brief Lexical local executable-target spelling shared with CMake.
#: @note Semantic validation separately excludes ``.``, ``..``, imported/alias
#:   syntax, and typed ``_NOT_BUILT`` sentinel names.
CONSUMER_TARGET_NAME_PATTERN = re.compile(r"[A-Za-z0-9_.+-]+")


def is_canonical_consumer_target_name(target_name: str) -> bool:
    """@brief Validate one local executable target name for both manifests.

    @param target_name Exact declaration or target-file manifest field.
    @return True only for a lexical local target name that is neither a
      reserved dot spelling nor a typed ``_NOT_BUILT`` sentinel.
    @throws None Validation is deterministic and performs no I/O.
    @note The generated CMake writer applies the equivalent conditions before
      target creation or manifest serialization, keeping both boundaries in
      one fail-closed contract.
    """

    return (
        target_name not in {".", ".."}
        and CONSUMER_TARGET_NAME_PATTERN.fullmatch(target_name) is not None
        and not target_name.endswith("_NOT_BUILT")
    )


def is_canonical_consumer_target_filename(
    target_name: str, executable_name: str
) -> bool:
    """@brief Validate CMake's configured filename for one local target.

    @param target_name Exact canonical target identity from both manifests.
    @param executable_name Configuration-specific ``$<TARGET_FILE_NAME>``
      field emitted by the generated CMake project.
    @return True only for the extensionless target spelling or that exact
      spelling plus the native Windows/Cygwin/MSYS2 ``.exe`` suffix.
    @throws None Validation is deterministic and performs no host-platform
      classification or I/O.
    @note The generated consumer does not customize ``OUTPUT_NAME``, prefix,
      suffix, or configuration postfix. CMake, rather than Python's
      ``os.name`` or ``sys.platform``, therefore chooses which of the two
      target-bound native spellings is authoritative. Requiring that closed
      relationship prevents a forged filename field from selecting an
      arbitrary build-local executable.
    """

    return (
        is_canonical_consumer_target_name(target_name)
        and executable_name not in {"", ".", ".."}
        and not contains_forbidden_ascii_control(executable_name)
        and PurePosixPath(executable_name).name == executable_name
        and PureWindowsPath(executable_name).name == executable_name
        and executable_name in {target_name, f"{target_name}.exe"}
    )


def run(command: list[str], cwd: Path) -> None:
    """@brief Run one required smoke command with inherited output.

    @param command Executable and arguments passed without a shell.
    @param cwd Working directory for the child process.
    @return None.
    @throws OSError If the command cannot start.
    @throws subprocess.CalledProcessError If the command exits nonzero.
    @note Inherited streams remain visible in CTest and CI artifacts.
    """

    print("$ " + " ".join(command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def run_expect_failure(
    command: list[str], cwd: Path, expected_diagnostic: str
) -> None:
    """@brief Require one configure command to fail with a stable diagnostic.

    @param command Executable and arguments passed without a shell.
    @param cwd Working directory for the child process.
    @param expected_diagnostic Text that must occur in combined child output.
    @return None after a nonzero child status.
    @throws OSError If the command cannot start.
    @throws RuntimeError If the command succeeds or omits the diagnostic.
    @note Combined child output remains visible in CTest and CI artifacts.
    """

    print("$ " + " ".join(command), flush=True)
    completed = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    print(completed.stdout, end="", flush=True)
    if completed.returncode == 0:
        raise RuntimeError("expected configure command to fail")
    normalized_output = " ".join(completed.stdout.split())
    normalized_diagnostic = " ".join(expected_diagnostic.split())
    if normalized_diagnostic not in normalized_output:
        raise RuntimeError(
            "failed configure omitted expected diagnostic: "
            f"{expected_diagnostic}"
        )


def contains_forbidden_ascii_control(
    text: str, allowed_controls: str = ""
) -> bool:
    """@brief Detect ASCII controls that are not record delimiters.

    @param text Exact manifest text or field to inspect.
    @param allowed_controls Controls reserved structurally by the current
      format, normally LF or LF plus TAB while validating complete manifests.
    @return True if text contains a disallowed C0 control or DEL; otherwise
      False.
    @throws None Character inspection is deterministic and in-memory.
    @note NUL is included even though CMake strings cannot represent it, so an
      externally modified manifest still fails closed.
    """

    return any(
        character not in allowed_controls
        and (ord(character) < 32 or ord(character) == 127)
        for character in text
    )


def consumer_target_file_manifest_path(
    build: Path, configuration: str
) -> Path:
    """@brief Resolve one configuration-specific target-file manifest path.

    @param build Configured disposable consumer build directory.
    @param configuration Exact single- or multi-config name selected for build.
    @return Build-local path generated from ``$<CONFIG>`` by CMake.
    @throws RuntimeError If configuration is empty, path-like, or contains an
      ASCII control character.
    @note Both POSIX and Windows basename rules are applied before the value is
      used in a path, preventing traversal on either host family.
    """

    if (
        not configuration
        or PurePosixPath(configuration).name != configuration
        or PureWindowsPath(configuration).name != configuration
        or configuration in {".", ".."}
        or contains_forbidden_ascii_control(configuration)
    ):
        raise RuntimeError(
            "invalid dependency-disabled consumer configuration for target "
            f"inventory: {configuration!r}"
        )
    return (
        build
        / CONSUMER_INVENTORY_RELATIVE_DIRECTORY
        / f"{CONSUMER_TARGET_FILE_MANIFEST_PREFIX}{configuration}.tsv"
    )


def read_strict_manifest_lines(
    path: Path,
    *,
    expected_header: str,
    allow_tab: bool,
    description: str,
) -> list[str]:
    """@brief Read one exact LF-delimited CMake-owned manifest.

    @param path Fixed build-local manifest path to read.
    @param expected_header Exact first record required by the format.
    @param allow_tab Whether TAB is reserved as a structural field delimiter.
    @param description Controlled diagnostic label that contains no file data.
    @return Non-header records in serialized order.
    @throws OSError If the manifest cannot be read.
    @throws RuntimeError If the path is absent/non-regular/symlinked, UTF-8 is
      invalid, a forbidden control occurs, the final LF is absent, the header
      differs, or a later blank/comment/header record occurs.
    @note The exact path is produced by the current consumer configure. The
      reader nevertheless validates its complete byte/record boundary before
      a target path can reach process execution.
    """

    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f"{description} is missing or not a regular file")
    try:
        manifest_text = path.read_bytes().decode("utf-8")
    except UnicodeDecodeError as error:
        raise RuntimeError(f"{description} is not valid UTF-8") from error
    allowed_controls = "\n\t" if allow_tab else "\n"
    if contains_forbidden_ascii_control(manifest_text, allowed_controls):
        raise RuntimeError(
            f"{description} contains a forbidden ASCII control character"
        )
    if not manifest_text.endswith("\n"):
        raise RuntimeError(f"{description} lacks its exact final LF")
    lines = manifest_text[:-1].split("\n")
    if not lines or lines[0] != expected_header:
        raise RuntimeError(f"{description} has a missing or invalid header")
    for line_number, line in enumerate(lines[1:], start=2):
        if not line:
            raise RuntimeError(
                f"{description} contains a blank entry at line {line_number}"
            )
        if line.startswith("#"):
            raise RuntimeError(
                f"{description} contains a comment or repeated header at "
                f"line {line_number}"
            )
    return lines[1:]


def configured_consumer_target_files(
    build: Path, configuration: str
) -> list[tuple[str, Path]]:
    """@brief Validate and resolve every declared consumer executable.

    The reader first parses the configure-time target declaration and the
    configuration-specific ``$<TARGET_FILE_NAME:...>`` plus
    ``$<TARGET_FILE:...>`` TSV independently. It then requires the same
    nonempty unique target sequence before validating every executable name
    and path. Configured names must remain target-bound native spellings;
    paths must use canonical native spelling, resolve without a symlink inside
    the current consumer build, match the configured name exactly, and
    identify an executable regular file. Only after the complete inventory
    passes does the function return any runnable path.

    @param build Configured and built disposable consumer build directory.
    @param configuration Exact configuration selected by the consumer build.
    @return Target/path pairs in the CMake declaration order.
    @throws OSError If a fixed manifest cannot be read or filesystem metadata
      cannot be inspected.
    @throws RuntimeError If either manifest is malformed, empty, duplicated,
      inconsistent, unsafe, noncanonical, unexpected, or references an
      unbuilt/non-file/non-executable target.
    @note The manifests are trusted only as products of this invocation's
      disposable configure/generate step. Exact cross-manifest identity,
      build-root confinement, basename binding, and file checks prevent either
      manifest from becoming a general-purpose executable input.
    """

    build_root = build.resolve(strict=True)
    declaration_path = (
        build_root
        / CONSUMER_INVENTORY_RELATIVE_DIRECTORY
        / CONSUMER_TARGET_DECLARATION_MANIFEST_NAME
    )
    declaration_lines = read_strict_manifest_lines(
        declaration_path,
        expected_header=CONSUMER_TARGET_DECLARATION_HEADER,
        allow_tab=False,
        description="dependency-disabled consumer target declaration",
    )
    declared_targets: list[str] = []
    declared_target_set: set[str] = set()
    for line_number, target_name in enumerate(declaration_lines, start=2):
        if not is_canonical_consumer_target_name(target_name):
            raise RuntimeError(
                "dependency-disabled consumer target declaration contains "
                f"an invalid target at line {line_number}"
            )
        if target_name in declared_target_set:
            raise RuntimeError(
                "dependency-disabled consumer target declaration contains "
                f"a duplicate target: {target_name!r}"
            )
        declared_target_set.add(target_name)
        declared_targets.append(target_name)
    if not declared_targets:
        raise RuntimeError(
            "dependency-disabled consumer target declaration is empty"
        )

    target_file_path = consumer_target_file_manifest_path(
        build_root, configuration
    )
    target_file_lines = read_strict_manifest_lines(
        target_file_path,
        expected_header=CONSUMER_TARGET_FILE_MANIFEST_HEADER,
        allow_tab=True,
        description="dependency-disabled consumer target-file inventory",
    )
    serialized_records: list[tuple[str, str, str]] = []
    serialized_target_set: set[str] = set()
    serialized_filename_set: set[str] = set()
    for line_number, line in enumerate(target_file_lines, start=2):
        fields = line.split("\t")
        if len(fields) != 3:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a malformed entry at line {line_number}"
            )
        target_name, executable_name, executable_text = fields
        if (
            not is_canonical_consumer_target_name(target_name)
            or not is_canonical_consumer_target_filename(
                target_name, executable_name
            )
            or not executable_text
        ):
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"an invalid entry at line {line_number}"
            )
        if target_name in serialized_target_set:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a duplicate target: {target_name!r}"
            )
        if executable_name in serialized_filename_set:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                "a duplicate configured executable filename"
            )
        serialized_target_set.add(target_name)
        serialized_filename_set.add(executable_name)
        serialized_records.append(
            (target_name, executable_name, executable_text)
        )
    if not serialized_records:
        raise RuntimeError(
            "dependency-disabled consumer target-file inventory is empty"
        )

    serialized_targets = [
        target for target, _filename, _path in serialized_records
    ]
    missing_targets = [
        target
        for target in declared_targets
        if target not in serialized_target_set
    ]
    unexpected_targets = [
        target for target in serialized_targets if target not in declared_target_set
    ]
    if missing_targets or unexpected_targets:
        raise RuntimeError(
            "dependency-disabled consumer target inventory mismatch: "
            f"missing={missing_targets!r}, unexpected={unexpected_targets!r}"
        )
    if serialized_targets != declared_targets:
        raise RuntimeError(
            "dependency-disabled consumer target inventory order differs "
            "from the CMake declaration"
        )

    resolved_records: list[tuple[str, Path]] = []
    resolved_path_set: set[Path] = set()
    for target_name, executable_name, executable_text in serialized_records:
        executable = Path(executable_text)
        if not executable.is_absolute():
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a relative path for target {target_name!r}"
            )
        if os.name == "nt":
            normalized_text = executable_text.replace("\\", "/")
            canonical_text = PureWindowsPath(executable_text).as_posix()
        else:
            normalized_text = executable_text
            canonical_text = executable.as_posix()
            if executable_text.startswith("//"):
                canonical_text = ""
        if normalized_text != canonical_text:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a noncanonical path for target {target_name!r}"
            )
        if executable.is_symlink():
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a symlink path for target {target_name!r}"
            )
        try:
            resolved_executable = executable.resolve(strict=True)
        except OSError as error:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory references "
                f"an unbuilt target {target_name!r}"
            ) from error
        if executable != resolved_executable:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"a noncanonical path for target {target_name!r}"
            )
        try:
            build_relative_executable = resolved_executable.relative_to(
                build_root
            )
        except ValueError as error:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory escapes "
                f"the consumer build for target {target_name!r}"
            ) from error
        if resolved_executable.name != executable_name:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory path does "
                f"not match target {target_name!r}"
            )
        if build_relative_executable not in {
            Path(executable_name),
            Path(configuration) / executable_name,
        }:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                f"an unexpected build path for target {target_name!r}"
            )
        if (
            not resolved_executable.is_file()
            or not os.access(resolved_executable, os.X_OK)
        ):
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory references "
                f"a non-executable file for target {target_name!r}"
            )
        if resolved_executable in resolved_path_set:
            raise RuntimeError(
                "dependency-disabled consumer target-file inventory contains "
                "a duplicate executable path"
            )
        resolved_path_set.add(resolved_executable)
        resolved_records.append((target_name, resolved_executable))
    return resolved_records


def remove_tree(path: Path, repo: Path) -> None:
    """@brief Remove one validated transient build/install tree.

    @param path Work directory to remove when present.
    @param repo Repository root that must never be removed.
    @return None.
    @throws ValueError If path is the repository or one of its ancestors.
    @throws OSError If recursive removal fails.
    @note Every descendant under path is owned by this smoke.
    """

    if path == repo or path in repo.parents:
        raise ValueError(f"refusing destructive work path: {path}")
    if path.exists() or path.is_symlink():
        shutil.rmtree(path)


def cmake_cache_values(build: Path) -> dict[str, str]:
    """@brief Read exact key/value assignments from one CMake cache.

    @param build Existing producer build directory containing CMakeCache.txt.
    @return Mapping from cache keys to their final serialized values.
    @throws OSError If the cache cannot be read.
    @throws RuntimeError If the producer has no regular cache file.
    @note Comments and malformed lines are ignored; later assignments win.
    """

    cache_path = build / "CMakeCache.txt"
    if not cache_path.is_file():
        raise RuntimeError(f"reusable producer has no CMake cache: {cache_path}")
    values: dict[str, str] = {}
    for line in cache_path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith(("#", "//")) or "=" not in line:
            continue
        assignment, value = line.split("=", 1)
        if ":" not in assignment:
            continue
        key, _cache_type = assignment.split(":", 1)
        if key:
            values[key] = value
    return values


def validate_reusable_producer(repo: Path, build: Path, config: str) -> None:
    """@brief Validate an external dependency-disabled producer.

    @param repo Resolved Photospider source repository expected by the cache.
    @param build Resolved reusable producer build directory.
    @param config Requested single- or multi-config build configuration.
    @return None after identity and profile checks succeed.
    @throws OSError If cached paths cannot be read or resolved.
    @throws RuntimeError If identity, configuration, or capability state differs.
    @note Validation is fail-closed and never mutates the producer.
    """

    cache = cmake_cache_values(build)

    def require(key: str) -> str:
        """@brief Return one required serialized cache value.

        @param key Exact CMake cache key.
        @return Serialized value, including an intentional empty value.
        @throws RuntimeError If key is absent.
        @note Callers own profile-specific interpretation.
        """

        if key not in cache:
            raise RuntimeError(f"reusable producer cache is missing {key}")
        return cache[key]

    cached_source = Path(require("CMAKE_HOME_DIRECTORY")).resolve()
    cached_build = Path(require("CMAKE_CACHEFILE_DIR")).resolve()
    if cached_source != repo or cached_build != build:
        raise RuntimeError(
            "reusable producer identity mismatch: "
            f"source={cached_source}, build={cached_build}"
        )
    expected_values = {
        "BUILD_TESTING": "OFF",
        "PHOTOSPIDER_BUILD_IPC": "OFF",
        "PHOTOSPIDER_ENABLE_OPENCV": "OFF",
        "PHOTOSPIDER_ENABLE_YAML": "OFF",
        "PHOTOSPIDER_BUILD_GRAPH_CLI": "OFF",
        "PHOTOSPIDER_BUILD_OPENCV_OPERATION_PROVIDER": "OFF",
        "PHOTOSPIDER_BUILD_OPENCV_OPERATION_PLUGINS": "OFF",
        "CMAKE_DISABLE_FIND_PACKAGE_OpenCV": "ON",
        "CMAKE_DISABLE_FIND_PACKAGE_yaml-cpp": "ON",
    }
    for key, expected in expected_values.items():
        actual = require(key)
        if actual != expected:
            raise RuntimeError(
                f"reusable producer requires {key}={expected}, got {actual}"
            )

    configuration_types = cache.get("CMAKE_CONFIGURATION_TYPES", "")
    if configuration_types:
        if config not in configuration_types.split(";"):
            raise RuntimeError(
                f"requested configuration {config} is unavailable: "
                f"{configuration_types}"
            )
    elif require("CMAKE_BUILD_TYPE") != config:
        raise RuntimeError(
            f"reusable producer build type is not requested {config}"
        )


def write_component_probe(source: Path, *, required: bool) -> None:
    """@brief Write one unavailable operation_opencv component probe.

    @param source Source directory created for the probe.
    @param required Whether discovery must require the unavailable component.
    @return None.
    @throws OSError If source files cannot be written.
    @note Optional discovery must succeed without creating an imported target;
      required discovery is expected to fail during configure.
    """

    source.mkdir(parents=True)
    if required:
        body = [
            "cmake_minimum_required(VERSION 3.16)",
            "project(required_opencv_component LANGUAGES CXX)",
            "find_package(Photospider CONFIG REQUIRED",
            "  COMPONENTS operation_opencv)",
            "",
        ]
    else:
        body = [
            "cmake_minimum_required(VERSION 3.16)",
            "project(optional_opencv_component LANGUAGES CXX)",
            "find_package(Photospider CONFIG",
            "  OPTIONAL_COMPONENTS operation_opencv)",
            "if(NOT Photospider_FOUND)",
            '  message(FATAL_ERROR "optional component lookup failed package")',
            "endif()",
            "if(Photospider_operation_opencv_FOUND OR",
            "   TARGET Photospider::operation_opencv)",
            '  message(FATAL_ERROR "disabled OpenCV component was advertised")',
            "endif()",
            "",
        ]
    (source / "CMakeLists.txt").write_text("\n".join(body), encoding="utf-8")


def write_consumer(source: Path) -> None:
    """@brief Write the installed Host consumer and its CMake project.

    @param source Source directory created for the consumer.
    @return None.
    @throws OSError If source files cannot be written.
    @note One CMake target list owns validated executable creation, declaration
      order, and the configuration-specific ``$<TARGET_FILE_NAME:...>`` plus
      ``$<TARGET_FILE:...>`` manifest. Reserved dot spellings and typed
      ``_NOT_BUILT`` sentinels fail before target creation or serialization.
      The current executable verifies neutral allocation, empty-session
      lifecycle, and explicit persistence failure without parser or
      image-library APIs.
    """

    source.mkdir(parents=True)
    (source / "CMakeLists.txt").write_text(
        "\n".join(
            [
                "cmake_minimum_required(VERSION 3.16)",
                "project(dependency_disabled_consumer LANGUAGES CXX)",
                "find_package(Photospider CONFIG REQUIRED COMPONENTS embedded)",
                "set(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGETS",
                "  dependency_disabled_consumer)",
                "list(LENGTH",
                "  PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGETS",
                "  PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET_COUNT)",
                "if(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET_COUNT",
                "    EQUAL 0)",
                '  message(FATAL_ERROR "Consumer target list is empty")',
                "endif()",
                "set(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_SEEN_TARGETS",
                "  \"\")",
                "set(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_DECLARATION",
                '  "# target\\n")',
                "set(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET_FILES",
                (
                    '  "# target\\tconfigured executable filename\\t'
                    'configured executable\\n")'
                ),
                "foreach(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET",
                "    IN LISTS",
                "      PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGETS)",
                "  if(NOT",
                "      PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET",
                '      MATCHES "^[A-Za-z0-9_.+-]+$" OR',
                "     PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET",
                '      STREQUAL "." OR',
                "     PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET",
                '      STREQUAL ".." OR',
                "     PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET",
                '      MATCHES "_NOT_BUILT$")',
                '    message(FATAL_ERROR "Invalid consumer target name")',
                "  endif()",
                "  list(FIND",
                "    PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_SEEN_TARGETS",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\"",
                "    PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_DUPLICATE_INDEX)",
                "  if(NOT",
                "      PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_DUPLICATE_INDEX",
                "      EQUAL -1)",
                '    message(FATAL_ERROR "Duplicate consumer target name")',
                "  endif()",
                "  list(APPEND",
                "    PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_SEEN_TARGETS",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\")",
                "  add_executable(",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\"",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}.cpp\")",
                "  target_link_libraries(",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\"",
                "    PRIVATE Photospider::photospider)",
                "  string(APPEND",
                "    PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_DECLARATION",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\\n\")",
                "  string(APPEND",
                "    PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET_FILES",
                "    \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET}\\t\"",
                (
                    "    \"$<TARGET_FILE_NAME:${PHOTOSPIDER_DEPENDENCY_"
                    "DISABLED_CONSUMER_TARGET}>\\t\""
                ),
                (
                    "    \"$<TARGET_FILE:${PHOTOSPIDER_DEPENDENCY_DISABLED_"
                    "CONSUMER_TARGET}>\\n\")"
                ),
                "endforeach()",
                "set(PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_INVENTORY_DIR",
                "  \"${CMAKE_BINARY_DIR}/generated/ci_inventory\")",
                "file(MAKE_DIRECTORY",
                "  \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_INVENTORY_DIR}\")",
                "file(WRITE",
                (
                    "  \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_"
                    "INVENTORY_DIR}/consumer_targets.txt\""
                ),
                "  \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_DECLARATION}\")",
                "file(GENERATE OUTPUT",
                (
                    "  \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_"
                    "INVENTORY_DIR}/consumer_target_files-$<CONFIG>.tsv\""
                ),
                "  CONTENT",
                "  \"${PHOTOSPIDER_DEPENDENCY_DISABLED_CONSUMER_TARGET_FILES}\")",
                "",
            ]
        ),
        encoding="utf-8",
    )
    (source / "dependency_disabled_consumer.cpp").write_text(
        "\n".join(
            [
                "#include <filesystem>",
                "#include <fstream>",
                "#include <memory>",
                "#include <string>",
                "",
                "#include <photospider/core/graph_error.hpp>",
                "#include <photospider/core/image_buffer.hpp>",
                "#include <photospider/core/result_types.hpp>",
                "#include <photospider/host/host.hpp>",
                "",
                "int main(int argc, char** argv) {",
                "  if (argc != 2) return 10;",
                "  const std::filesystem::path root(argv[1]);",
                "  std::filesystem::create_directories(root);",
                "",
                "  ps::ImageBuffer image = ps::make_aligned_cpu_image_buffer(",
                "      3, 2, 4, ps::DataType::UINT8);",
                "  ps::validate_image_buffer(image);",
                "  if (!image.data || image.width != 3 || image.height != 2) {",
                "    return 11;",
                "  }",
                "",
                "  auto host = ps::create_embedded_host();",
                "  if (!host) return 12;",
                "  ps::GraphLoadRequest empty_request;",
                '  empty_request.session.value = "empty";',
                "  empty_request.root_dir = root.string();",
                "  auto loaded = host->load_graph(empty_request);",
                "  if (!loaded.status.ok) return 13;",
                "  auto closed = host->close_graph(loaded.value);",
                "  if (!closed.status.ok) return 14;",
                "",
                '  const auto document = root / "disabled.yaml";',
                "  std::ofstream(document) << \"nodes: []\\n\";",
                "  ps::GraphLoadRequest explicit_request;",
                '  explicit_request.session.value = "explicit";',
                "  explicit_request.root_dir = root.string();",
                "  explicit_request.yaml_path = document.string();",
                "  const auto rejected = host->load_graph(explicit_request);",
                "  const auto code = ps::checked_graph_error_code(",
                "      rejected.status);",
                "  if (rejected.status.ok || !code ||",
                "      *code != ps::GraphErrc::Io) {",
                "    return 15;",
                "  }",
                "  return 0;",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    """@brief Build, install, and consume the dependency-disabled profile.

    @return Zero only when the kernel aggregate and Host product build without
      OpenCV/YAML discovery, installation omits their public/export surfaces,
      optional/required component semantics are correct, and every consumer in
      the generated exact target inventory runs successfully.
    @throws OSError For filesystem or process-start failures.
    @throws subprocess.CalledProcessError For required command failures.
    @throws ValueError If transient paths overlap protected paths.
    @throws RuntimeError If any build, export, component, or runtime invariant
      contradicts the dependency-disabled profile.
    @note A validated ``--producer-build`` may be reused without configuration
      or compilation. Installation and consumer artifacts always remain under
      ``work`` and are removed before return. On Darwin, every child configure
      inherits the selected producer's meaningful
      ``CMAKE_OSX_ARCHITECTURES`` value as one argv element; other platforms
      receive no macOS-specific option. Target collection and path validation
      complete before the first consumer process starts.
    """

    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--work", required=True)
    parser.add_argument("--cmake-executable", default="cmake")
    parser.add_argument("--config", default="RelWithDebInfo")
    parser.add_argument("--producer-build", default="")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    work = Path(args.work).resolve()
    producer_build = (
        Path(args.producer_build).resolve() if args.producer_build else None
    )
    if producer_build is not None:
        if (
            producer_build == work
            or producer_build in work.parents
            or work in producer_build.parents
        ):
            raise ValueError(
                "reusable producer and transient work paths overlap: "
                f"{producer_build}, {work}"
            )
        validate_reusable_producer(repo, producer_build, args.config)

    remove_tree(work, repo)
    build = producer_build if producer_build is not None else work / "build"
    prefix = work / "install"
    optional_source = work / "optional-opencv"
    optional_build = work / "optional-opencv-build"
    required_source = work / "required-opencv"
    required_build = work / "required-opencv-build"
    invalid_provider_build = work / "invalid-provider-build"
    invalid_plugins_build = work / "invalid-plugins-build"
    invalid_cli_build = work / "invalid-cli-build"
    consumer_source = work / "consumer"
    consumer_build = work / "consumer-build"
    runtime_root = work / "runtime"
    try:
        if producer_build is None:
            run(
                [
                    args.cmake_executable,
                    "-S",
                    str(repo),
                    "-B",
                    str(build),
                    "-DBUILD_TESTING=OFF",
                    "-DPHOTOSPIDER_BUILD_IPC=OFF",
                    "-DPHOTOSPIDER_ENABLE_OPENCV=OFF",
                    "-DPHOTOSPIDER_ENABLE_YAML=OFF",
                    "-DCMAKE_DISABLE_FIND_PACKAGE_OpenCV=ON",
                    "-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON",
                    f"-DCMAKE_BUILD_TYPE={args.config}",
                ],
                repo,
            )
            run(
                [
                    args.cmake_executable,
                    "--build",
                    str(build),
                    "--target",
                    "photospider_kernel",
                    "photospider",
                    "--config",
                    args.config,
                    "--parallel",
                    "4",
                ],
                repo,
            )

        child_architecture_arguments = (
            producer_osx_architecture_arguments(build)
        )
        run(
            [
                args.cmake_executable,
                "--install",
                str(build),
                "--prefix",
                str(prefix),
                "--config",
                args.config,
            ],
            repo,
        )

        forbidden = [
            prefix / "include" / "photospider" / "plugin" / "opencv_adapter.hpp",
            *prefix.rglob("PhotospiderOpenCVTargets*.cmake"),
        ]
        existing_forbidden = [path for path in forbidden if path.exists()]
        if existing_forbidden:
            raise RuntimeError(
                "dependency-disabled install leaked OpenCV artifacts: "
                f"{existing_forbidden}"
            )
        embedded_exports = list(prefix.rglob("PhotospiderEmbeddedTargets*.cmake"))
        exported_text = "\n".join(
            path.read_text(encoding="utf-8") for path in embedded_exports
        )
        leaked_tokens = [
            token
            for token in (
                "Photospider::operation_opencv",
                "opencv_core",
                "opencv_imgproc",
                "opencv_imgcodecs",
                "yaml-cpp::yaml-cpp",
            )
            if token in exported_text
        ]
        if leaked_tokens:
            raise RuntimeError(
                f"dependency-disabled embedded export leaked: {leaked_tokens}"
            )

        write_component_probe(optional_source, required=False)
        run(
            [
                args.cmake_executable,
                "-S",
                str(optional_source),
                "-B",
                str(optional_build),
                f"-DCMAKE_PREFIX_PATH={prefix}",
                "-DCMAKE_DISABLE_FIND_PACKAGE_OpenCV=ON",
                "-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON",
                *child_architecture_arguments,
            ],
            repo,
        )

        write_component_probe(required_source, required=True)
        run_expect_failure(
            [
                args.cmake_executable,
                "-S",
                str(required_source),
                "-B",
                str(required_build),
                f"-DCMAKE_PREFIX_PATH={prefix}",
                "-DCMAKE_DISABLE_FIND_PACKAGE_OpenCV=ON",
                "-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON",
                *child_architecture_arguments,
            ],
            repo,
            "Photospider was built without the operation_opencv component",
        )

        common_disabled_configuration = [
            args.cmake_executable,
            "-S",
            str(repo),
            "-DBUILD_TESTING=OFF",
            "-DPHOTOSPIDER_BUILD_IPC=OFF",
            "-DPHOTOSPIDER_ENABLE_OPENCV=OFF",
            "-DPHOTOSPIDER_ENABLE_YAML=OFF",
            "-DCMAKE_DISABLE_FIND_PACKAGE_OpenCV=ON",
            "-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON",
            *child_architecture_arguments,
        ]
        run_expect_failure(
            [
                *common_disabled_configuration,
                "-B",
                str(invalid_provider_build),
                "-DPHOTOSPIDER_BUILD_OPENCV_OPERATION_PROVIDER=ON",
            ],
            repo,
            "PHOTOSPIDER_BUILD_OPENCV_OPERATION_PROVIDER=ON requires "
            "PHOTOSPIDER_ENABLE_OPENCV=ON",
        )
        run_expect_failure(
            [
                *common_disabled_configuration,
                "-B",
                str(invalid_plugins_build),
                "-DPHOTOSPIDER_BUILD_OPENCV_OPERATION_PLUGINS=ON",
            ],
            repo,
            "PHOTOSPIDER_BUILD_OPENCV_OPERATION_PLUGINS=ON requires "
            "PHOTOSPIDER_ENABLE_OPENCV=ON",
        )
        run_expect_failure(
            [
                *common_disabled_configuration,
                "-B",
                str(invalid_cli_build),
                "-DPHOTOSPIDER_BUILD_GRAPH_CLI=ON",
            ],
            repo,
            "PHOTOSPIDER_BUILD_GRAPH_CLI=ON requires "
            "PHOTOSPIDER_ENABLE_OPENCV=ON and PHOTOSPIDER_ENABLE_YAML=ON",
        )

        write_consumer(consumer_source)
        run(
            [
                args.cmake_executable,
                "-S",
                str(consumer_source),
                "-B",
                str(consumer_build),
                f"-DCMAKE_PREFIX_PATH={prefix}",
                "-DCMAKE_DISABLE_FIND_PACKAGE_OpenCV=ON",
                "-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON",
                f"-DCMAKE_BUILD_TYPE={args.config}",
                *child_architecture_arguments,
            ],
            repo,
        )
        run(
            [
                args.cmake_executable,
                "--build",
                str(consumer_build),
                "--config",
                args.config,
                "--parallel",
                "4",
            ],
            repo,
        )
        consumer_target_files = configured_consumer_target_files(
            consumer_build, args.config
        )
        for _target_name, executable in consumer_target_files:
            run([str(executable), str(runtime_root)], work)
        print("Dependency-disabled install smoke: PASS", flush=True)
        return 0
    finally:
        remove_tree(work, repo)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:  # noqa: BLE001 - CTest needs one diagnostic.
        print(
            f"Dependency-disabled install smoke: FAIL: {error}",
            file=sys.stderr,
        )
        raise
