/**
 * @file compute_service.cpp
 * @brief Implements the ComputeService facade for sequential, parallel, and
 * dirty update compute entry points.
 *
 * ComputeService keeps the public compute API and request orchestration. Node
 * execution, dirty ROI execution, HP-to-RT downsample refresh, task graph
 * dispatch, cache policy, input resolution, and metrics metadata are delegated
 * to the compute-service collaborators under
 * src/kernel/services/compute-service.
 */
#include "kernel/services/compute_service.hpp"

#include <chrono>
#include <functional>
#include <mutex>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

#include "benchmark/benchmark_types.hpp"
#include "kernel/graph_runtime.hpp"
#include "kernel/param_utils.hpp"
#include "kernel/services/compute-service/compute_cache_policy.hpp"
#include "kernel/services/compute-service/compute_metrics_recorder.hpp"
#include "kernel/services/compute-service/compute_task_dispatcher.hpp"
#include "kernel/services/compute-service/dirty_update_executor.hpp"
#include "kernel/services/compute-service/intent_update_coordinator.hpp"
#include "kernel/services/compute-service/node_executor.hpp"
#include "kernel/services/compute-service/node_input_resolver.hpp"
#include "kernel/services/compute-service/task_graph_planning.hpp"
#include "kernel/services/graph_cache_service.hpp"
#include "kernel/services/graph_event_service.hpp"
#include "kernel/services/graph_traversal_service.hpp"

namespace ps {

ComputeService::ComputeService(GraphTraversalService& traversal,
                               GraphCacheService& cache,
                               GraphEventService& events)
    : traversal_(traversal), cache_(cache), events_(events) {}

namespace {

/**
 * @brief Finalizes one produced node output through the shared metrics policy.
 *
 * @param output Output generated by an operation and stored in node cache.
 * @param inputs Image inputs used to derive debug and spatial metadata.
 * @param enable_timing Whether timing metadata should be attached.
 * @param execution_ms Measured node execution duration in milliseconds.
 * @throws Any exception propagated by ComputeMetricsRecorder.
 * @note This helper keeps the recursive sequential path aligned with the
 * dispatcher metadata policy.
 */
void finalize_output_metadata(NodeOutput& output,
                              const std::vector<const NodeOutput*>& inputs,
                              bool enable_timing, double execution_ms) {
  compute::ComputeMetricsRecorder::finalize_output_metadata(
      output, inputs, enable_timing, execution_ms);
}

/**
 * @brief Stores the latest compute plan and a bounded recent-plan history.
 *
 * @param graph Graph whose inspection state receives the plan snapshot.
 * @param compute_plan Plan produced for the current request.
 * @throws std::bad_alloc if history storage cannot grow.
 * @note The history cap is intentionally small because plans are diagnostic
 * state, not an unbounded runtime log.
 */
void remember_facade_compute_plan(GraphModel& graph,
                                  const compute::ComputePlan& compute_plan) {
  graph.last_compute_plan = compute_plan;
  graph.recent_compute_plans.push_back(compute_plan);
  if (graph.recent_compute_plans.size() > 16) {
    graph.recent_compute_plans.erase(graph.recent_compute_plans.begin());
  }
}

/**
 * @brief Builds the node/cache-pruned plan used by sequential compute.
 *
 * @param graph Graph that supplies topology, node metadata, and cache state.
 * @param request Intent, target node, and optional dirty ROI for the request.
 * @param execution_order Topological execution order for the target cone.
 * @return Compute plan pruned to request target and cache availability.
 * @throws GraphError from full task graph expansion or pruning.
 * @note Dirty update executors have their own same-boundary helper because
 * they also record dirty snapshots and materialized work sets.
 */
compute::ComputePlan prune_facade_node_cache_task_graph(
    const GraphModel& graph, const compute::ComputeRequest& request,
    const std::vector<int>& execution_order) {
  compute::FullTaskGraphExpander full_expander;
  compute::NodeCacheTaskGraphPruner node_cache_pruner;
  const compute::FullTaskGraph full_graph =
      full_expander.expand(graph, request.intent);
  return node_cache_pruner.prune(full_graph, request, execution_order, graph);
}

}  // namespace

/**
 * @brief Computes one node output through recursive sequential execution.
 *
 * The recursive path preserves the legacy single-threaded behavior: it checks
 * HP memory cache, optionally loads disk cache, detects cycles, resolves
 * parameter and image inputs, dispatches the selected HP operator through
 * NodeExecutor, commits the HP cache, records timing/events, and saves disk
 * cache when configured.
 *
 * @param graph Graph whose nodes and caches are read and mutated.
 * @param node_id Node id to compute.
 * @param cache_precision Cache precision label used for disk cache writes.
 * @param visiting Recursion state used to detect dependency cycles.
 * @param enable_timing Whether node timing should be stored on the graph.
 * @param allow_disk_cache Whether disk cache may be read before computation.
 * @param benchmark_events Optional sink for per-node benchmark timing.
 * @return Mutable HP output owned by the target node.
 * @throws GraphError when a cycle, missing dependency, missing operation, disk
 * cache failure, or compute failure occurs.
 * @note This method is used as the fallback for full parallel dispatch when no
 * scheduler task graph is available, so its cache semantics must stay aligned
 * with ComputeTaskDispatcher::execute.
 */
NodeOutput& ComputeService::compute_internal(
    GraphModel& graph, int node_id, const std::string& cache_precision,
    std::unordered_map<int, bool>& visiting, bool enable_timing,
    bool allow_disk_cache, std::vector<BenchmarkEvent>* benchmark_events) {
  auto& timing_results = graph.timing_results;
  auto& timing_mutex = graph.timing_mutex_;
  auto& target_node = graph.mutable_node(node_id);
  std::string result_source = "unknown";

  auto start_time_total = std::chrono::high_resolution_clock::now();

  BenchmarkEvent current_event;
  current_event.node_id = node_id;
  current_event.op_name = make_key(target_node.type, target_node.subtype);
  current_event.dependency_start_time = start_time_total;

  std::vector<const NodeOutput*> monolithic_inputs;
  do {
    if (compute::ComputeCachePolicy::has_reusable_output(target_node)) {
      result_source = "memory_cache";
      break;
    }
    if (allow_disk_cache &&
        cache_.try_load_from_disk_cache(graph, target_node)) {
      result_source = "disk_cache";
      break;
    }

    if (visiting[node_id]) {
      throw GraphError(GraphErrc::Cycle,
                       "Cycle detected: " + std::to_string(node_id));
    }
    visiting[node_id] = true;

    auto resolved_inputs = compute::NodeInputResolver::resolve(
        target_node,
        [&](int upstream_id) -> const NodeOutput* {
          return &compute_internal(graph, upstream_id, cache_precision,
                                   visiting, enable_timing, allow_disk_cache,
                                   benchmark_events);
        },
        "Sequential compute");
    monolithic_inputs = resolved_inputs.image_inputs;

    auto op_opt = OpRegistry::instance().resolve_for_intent(
        target_node.type, target_node.subtype,
        ComputeIntent::GlobalHighPrecision);
    if (!op_opt) {
      throw GraphError(GraphErrc::NoOperation, "No op for " + target_node.type +
                                                   ":" + target_node.subtype);
    }

    current_event.execution_start_time =
        std::chrono::high_resolution_clock::now();

    target_node.cached_output_high_precision = compute::NodeExecutor::execute(
        graph, target_node, *op_opt, monolithic_inputs);

    current_event.execution_end_time =
        std::chrono::high_resolution_clock::now();
    result_source = "computed";
    target_node.hp_version++;
    cache_.save_cache_if_configured(graph, target_node, cache_precision);
    visiting[node_id] = false;
  } while (false);

  auto end_time_total = std::chrono::high_resolution_clock::now();
  if (result_source == "computed") {
    current_event.execution_end_time = end_time_total;
  } else {
    current_event.execution_start_time = end_time_total;
    current_event.execution_end_time = end_time_total;
  }

  current_event.source = result_source;
  double execution_duration_ms =
      std::chrono::duration<double, std::milli>(
          current_event.execution_end_time - current_event.execution_start_time)
          .count();
  if (execution_duration_ms < 0) {
    execution_duration_ms = 0.0;
  }

  if (result_source == "computed" && target_node.cached_output_high_precision) {
    finalize_output_metadata(*target_node.cached_output_high_precision,
                             monolithic_inputs, enable_timing,
                             execution_duration_ms);
  }

  if (enable_timing) {
    {
      std::lock_guard lk(timing_mutex);
      timing_results.node_timings.push_back({target_node.id, target_node.name,
                                             execution_duration_ms,
                                             result_source});
    }
    events_.push(target_node.id, target_node.name, result_source,
                 execution_duration_ms);
  } else {
    events_.push(target_node.id, target_node.name, result_source, 0.0);
  }

  if (benchmark_events) {
    current_event.execution_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_end_time -
            current_event.execution_start_time)
            .count();
    current_event.dependency_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_start_time -
            current_event.dependency_start_time)
            .count();
    benchmark_events->push_back(current_event);
  }

  return *compute::ComputeCachePolicy::reusable_output(target_node);
}

/**
 * @brief Delegates HP dirty ROI execution to HighPrecisionDirtyExecutor.
 *
 * @param graph Graph whose HP dirty state and cache are updated.
 * @param runtime Optional runtime for scheduler-backed dirty task dispatch.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether HP dirty caches in the plan should be cleared.
 * @param enable_timing Whether timing was requested by the caller.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink from the facade request.
 * @param dirty_roi HP-space dirty region to execute.
 * @return Mutable target HP output stored in the graph.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation.
 * @note This method intentionally contains no node-level dirty execution logic;
 * ComputeService remains only the public orchestration boundary.
 */
NodeOutput& ComputeService::compute_high_precision_update(
    GraphModel& graph, GraphRuntime* runtime, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events,
    const cv::Rect& dirty_roi) {
  compute::HighPrecisionDirtyExecutor executor(traversal_, events_);
  return executor.execute(
      graph, runtime,
      compute::DirtyUpdateRequest{node_id, cache_precision, force_recache,
                                  enable_timing, disable_disk_cache,
                                  benchmark_events, dirty_roi});
}

/**
 * @brief Delegates RT dirty ROI execution to RealTimeDirtyExecutor.
 *
 * @param graph Graph whose RT dirty state and proxy cache are updated.
 * @param runtime Optional runtime for scheduler-backed dirty task dispatch.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether RT dirty caches in the plan should be cleared.
 * @param enable_timing Whether timing was requested by the caller.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink from the facade request.
 * @param dirty_roi HP-space dirty region to execute through the RT planner.
 * @return Mutable target RT output stored in the graph.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation.
 * @note RT dirty output stays transient and does not become reusable HP cache
 * authority.
 */
NodeOutput& ComputeService::compute_real_time_update(
    GraphModel& graph, GraphRuntime* runtime, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events,
    const cv::Rect& dirty_roi) {
  compute::RealTimeDirtyExecutor executor(traversal_, events_);
  return executor.execute(
      graph, runtime,
      compute::DirtyUpdateRequest{node_id, cache_precision, force_recache,
                                  enable_timing, disable_disk_cache,
                                  benchmark_events, dirty_roi});
}

/**
 * @brief Executes a full high-precision compute request through a scheduler.
 *
 * @param graph Graph being computed.
 * @param runtime Graph runtime that owns the HP scheduler.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label used for disk cache writes.
 * @param force_recache Whether planned HP memory caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink for node timing data.
 * @return Mutable target HP output stored in the graph.
 * @throws GraphError from scheduler lookup, task dispatch, fallback execution,
 * cache access, or missing target output.
 * @note Dirty ROI requests are routed through compute_intent_update_impl, not
 * this full-frame dispatcher entry.
 */
NodeOutput& ComputeService::compute_parallel(
    GraphModel& graph, GraphRuntime& runtime, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events) {
  compute::ComputeTaskDispatcher executor(traversal_, cache_, events_);
  SchedulerTaskRuntime& task_runtime = compute::ensure_scheduler_task_runtime(
      runtime, ComputeIntent::GlobalHighPrecision);
  return executor.execute(
      graph, task_runtime,
      compute::ComputeTaskDispatcher::ComputeDispatchRequest{
          node_id, cache_precision, force_recache, enable_timing,
          disable_disk_cache, benchmark_events},
      [this, &cache_precision, enable_timing, benchmark_events](
          GraphModel& fallback_graph, int fallback_node_id,
          bool allow_disk_cache) -> NodeOutput& {
        std::unordered_map<int, bool> visiting;
        return compute_internal(fallback_graph, fallback_node_id,
                                cache_precision, visiting, enable_timing,
                                allow_disk_cache, benchmark_events);
      });
}

/**
 * @brief Executes an intent-aware parallel request.
 *
 * @param graph Graph being computed.
 * @param runtime Runtime that owns intent-specific schedulers.
 * @param intent Compute intent selected by the caller.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether relevant caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @param dirty_roi Optional dirty ROI for dirty HP or RT update semantics.
 * @return Mutable output for the selected intent.
 * @throws GraphError from intent validation, scheduler lookup, or execution.
 * @note RealTimeUpdate with a dirty ROI intentionally bypasses coarse HP/RT
 * scheduler callbacks and delegates to dirty executors for each path.
 */
NodeOutput& ComputeService::compute_parallel(
    GraphModel& graph, GraphRuntime& runtime, ComputeIntent intent, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events,
    std::optional<cv::Rect> dirty_roi) {
  return compute_intent_update_impl(
      graph, &runtime, true, intent, node_id, cache_precision, force_recache,
      enable_timing, disable_disk_cache, benchmark_events, dirty_roi);
}

/**
 * @brief Coordinates intent semantics and binds ComputeService callbacks.
 *
 * @param graph Graph being computed.
 * @param runtime Optional runtime for scheduler-backed execution.
 * @param use_parallel_executor Whether full non-dirty work should use the
 * parallel dispatcher.
 * @param intent Compute intent selected by the caller.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether relevant caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @param dirty_roi Optional dirty ROI for HP dirty or RT dual-path updates.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws GraphError from intent validation, callback execution, scheduler
 * lookup, or missing target output.
 * @note The coordinator owns HP/RT dual-path semantics; ComputeService only
 * supplies the concrete execution callbacks.
 */
NodeOutput& ComputeService::compute_intent_update_impl(
    GraphModel& graph, GraphRuntime* runtime, bool use_parallel_executor,
    ComputeIntent intent, int node_id, const std::string& cache_precision,
    bool force_recache, bool enable_timing, bool disable_disk_cache,
    std::vector<BenchmarkEvent>* benchmark_events,
    std::optional<cv::Rect> dirty_roi) {
  compute::IntentUpdateCallbacks callbacks;
  const Node* coordinator_node = graph.find_node(node_id);
  const std::string coordinator_node_name =
      coordinator_node ? coordinator_node->name : std::string();
  callbacks.run_global_high_precision = [&]() -> NodeOutput& {
    if (use_parallel_executor) {
      if (!runtime) {
        throw GraphError(GraphErrc::ComputeError,
                         "Parallel HP compute requires a runtime.");
      }
      return compute_parallel(graph, *runtime, node_id, cache_precision,
                              force_recache, enable_timing, disable_disk_cache,
                              benchmark_events);
    }
    return compute(graph, node_id, cache_precision, force_recache,
                   enable_timing, disable_disk_cache, benchmark_events);
  };
  callbacks.run_global_high_precision_dirty_update = [&]() -> NodeOutput& {
    return compute_high_precision_update(
        graph, runtime, node_id, cache_precision, force_recache, enable_timing,
        disable_disk_cache, benchmark_events, *dirty_roi);
  };
  callbacks.run_high_precision_update = [&]() {
    compute_high_precision_update(graph, runtime, node_id, cache_precision,
                                  force_recache, enable_timing,
                                  disable_disk_cache, nullptr, *dirty_roi);
  };
  callbacks.run_real_time_update = [&]() -> NodeOutput& {
    return compute_real_time_update(
        graph, runtime, node_id, cache_precision, force_recache, enable_timing,
        disable_disk_cache, benchmark_events, *dirty_roi);
  };
  callbacks.real_time_output = [&]() -> NodeOutput& {
    Node& target = graph.mutable_node(node_id);
    if (!target.cached_output_real_time) {
      throw GraphError(GraphErrc::ComputeError,
                       "RT compute finished without target output.");
    }
    return *target.cached_output_real_time;
  };
  callbacks.record_stage = [&,
                            coordinator_node_name](const std::string& stage) {
    events_.push(node_id, coordinator_node_name, stage, 0.0);
  };

  SchedulerTaskRuntime* hp_task_runtime = nullptr;
  SchedulerTaskRuntime* rt_task_runtime = nullptr;
  if (use_parallel_executor && runtime) {
    const bool dirty_rt_update =
        intent == ComputeIntent::RealTimeUpdate && dirty_roi.has_value();
    if (!dirty_rt_update) {
      hp_task_runtime = &compute::ensure_scheduler_task_runtime(
          *runtime, ComputeIntent::GlobalHighPrecision);
      if (intent == ComputeIntent::RealTimeUpdate) {
        rt_task_runtime = &compute::ensure_scheduler_task_runtime(
            *runtime, ComputeIntent::RealTimeUpdate);
      }
    }
  }

  return compute::IntentUpdateCoordinator::coordinate_intent_update(
      intent, hp_task_runtime, rt_task_runtime, dirty_roi, callbacks);
}

/**
 * @brief Executes an intent-aware request without a GraphRuntime.
 *
 * @param graph Graph being computed.
 * @param intent Compute intent selected by the caller.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether relevant caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @param dirty_roi Optional dirty ROI for HP dirty or RT update semantics.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws GraphError from intent validation or execution.
 * @note Dirty HP and RT callbacks still use the dirty executors, but run node
 * work inline because no scheduler runtime is available.
 */
NodeOutput& ComputeService::compute_with_intent_impl(
    GraphModel& graph, ComputeIntent intent, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events,
    std::optional<cv::Rect> dirty_roi) {
  return compute_intent_update_impl(
      graph, nullptr, false, intent, node_id, cache_precision, force_recache,
      enable_timing, disable_disk_cache, benchmark_events, dirty_roi);
}

/**
 * @brief Public sequential high-precision compute entry point.
 *
 * @param graph Graph being computed.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label used for disk cache writes.
 * @param force_recache Whether planned HP memory caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @return Mutable target HP output stored in the graph.
 * @throws GraphError from validation, planning, recursive compute, or cache
 * operations.
 * @note This overload is the legacy non-intent facade and always executes the
 * GlobalHighPrecision path.
 */
NodeOutput& ComputeService::compute(
    GraphModel& graph, int node_id, const std::string& cache_precision,
    bool force_recache, bool enable_timing, bool disable_disk_cache,
    std::vector<BenchmarkEvent>* benchmark_events) {
  return compute_sequential_impl(graph, node_id, cache_precision, force_recache,
                                 enable_timing, disable_disk_cache,
                                 benchmark_events);
}

/**
 * @brief Implements sequential high-precision compute with plan inspection.
 *
 * @param graph Graph being computed.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label used for disk cache writes.
 * @param force_recache Whether planned HP memory caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @return Mutable target HP output stored in the graph.
 * @throws GraphError when the target is missing, topology is invalid, planning
 * fails, recursive compute fails, or target output is unavailable.
 * @note The method records the same node/cache-pruned plan shape used by the
 * parallel path before delegating to the recursive executor.
 */
NodeOutput& ComputeService::compute_sequential_impl(
    GraphModel& graph, int node_id, const std::string& cache_precision,
    bool force_recache, bool enable_timing, bool disable_disk_cache,
    std::vector<BenchmarkEvent>* benchmark_events) {
  if (!graph.has_node(node_id)) {
    throw GraphError(GraphErrc::NotFound, "Node " + std::to_string(node_id) +
                                              " not found in graph.");
  }

  if (benchmark_events) {
    benchmark_events->clear();
  }

  if (enable_timing) {
    clear_timing_results(graph);
  }

  std::vector<int> execution_order;
  try {
    execution_order = traversal_.topo_postorder_from(graph, node_id);
  } catch (const GraphError&) {
    throw;
  }
  const compute::ComputeRequest request{ComputeIntent::GlobalHighPrecision,
                                        node_id, false, std::nullopt};
  const compute::ComputePlan compute_plan =
      prune_facade_node_cache_task_graph(graph, request, execution_order);
  remember_facade_compute_plan(graph, compute_plan);
  execution_order = compute_plan.planned_nodes;

  if (force_recache) {
    std::lock_guard<std::mutex> lk(graph.graph_mutex_);
    for (int nid : execution_order) {
      auto& node = graph.mutable_node(nid);
      node.cached_output_high_precision.reset();
    }
  }

  std::unordered_map<int, bool> visiting;
  bool allow_disk_cache = !disable_disk_cache && !force_recache;
  NodeOutput& result =
      compute_internal(graph, node_id, cache_precision, visiting, enable_timing,
                       allow_disk_cache, benchmark_events);

  if (enable_timing) {
    double total = 0.0;
    {
      std::lock_guard<std::mutex> lk(graph.timing_mutex_);
      for (const auto& timing : graph.timing_results.node_timings) {
        total += timing.elapsed_ms;
      }
      graph.timing_results.total_ms = total;
    }
  }

  return result;
}

/**
 * @brief Public intent-aware compute entry point without GraphRuntime.
 *
 * @param graph Graph being computed.
 * @param intent Compute intent selected by the caller.
 * @param node_id Target node id.
 * @param cache_precision Cache precision label from the facade request.
 * @param force_recache Whether relevant caches should be cleared.
 * @param enable_timing Whether graph timing should be collected.
 * @param disable_disk_cache Whether disk cache reads are disabled.
 * @param benchmark_events Optional benchmark sink.
 * @param dirty_roi Optional dirty ROI for HP dirty or RT update semantics.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws GraphError from intent validation, planning, compute, or output
 * validation.
 * @note Realtime intent still requires a non-empty dirty ROI through
 * IntentUpdateCoordinator validation.
 */
NodeOutput& ComputeService::compute(
    GraphModel& graph, ComputeIntent intent, int node_id,
    const std::string& cache_precision, bool force_recache, bool enable_timing,
    bool disable_disk_cache, std::vector<BenchmarkEvent>* benchmark_events,
    std::optional<cv::Rect> dirty_roi) {
  return compute_with_intent_impl(
      graph, intent, node_id, cache_precision, force_recache, enable_timing,
      disable_disk_cache, benchmark_events, dirty_roi);
}

/**
 * @brief Clears timing results for one graph.
 *
 * @param graph Graph whose TimingCollector should be reset.
 * @throws Nothing directly.
 * @note The method holds graph.timing_mutex_ while mutating timing fields.
 */
void ComputeService::clear_timing_results(GraphModel& graph) {
  std::lock_guard<std::mutex> lk(graph.timing_mutex_);
  graph.timing_results.node_timings.clear();
  graph.timing_results.total_ms = 0.0;
}

}  // namespace ps
