#!/usr/bin/env python3
"""Generate finite IEEE binary32/binary64 multiply/divide RN-even golden bits.

Only Python integers and fractions.Fraction are used for the oracle. No native
float arithmetic, NumPy, SLEEF, or implementation-under-test code is involved.
Run from any directory; --check verifies the checked-in deterministic fixture.
"""
from __future__ import annotations

import argparse
from fractions import Fraction
from pathlib import Path
import random


def value(bits: int, fraction: int, exponent_bits: int) -> Fraction:
    bias = (1 << (exponent_bits - 1)) - 1
    sign = -1 if bits >> (fraction + exponent_bits) else 1
    exp = (bits >> fraction) & ((1 << exponent_bits) - 1)
    significand = bits & ((1 << fraction) - 1)
    if exp:
        significand |= 1 << fraction
    power = (exp if exp else 1) - bias - fraction
    return sign * Fraction(significand) * (Fraction(1 << power) if power >= 0 else Fraction(1, 1 << -power))


def round_bits(x: Fraction, fraction: int, exponent_bits: int, negative_zero: bool = False) -> int:
    sign = int(x < 0 or (x == 0 and negative_zero)) << (fraction + exponent_bits)
    if not x:
        return sign
    x = abs(x)
    n, d = x.numerator, x.denominator
    top = n.bit_length() - d.bit_length()
    if (n < d << top) if top >= 0 else (n << -top) < d:
        top -= 1
    bias = (1 << (exponent_bits - 1)) - 1
    quantum = max(1 - bias - fraction, top - fraction)
    if quantum >= 0:
        d <<= quantum
    else:
        n <<= -quantum
    q, r = divmod(n, d)
    if 2 * r > d or (2 * r == d and q & 1):
        q += 1
    if q == 1 << (fraction + 1):
        q >>= 1
        quantum += 1
    exponent = 0
    if q >= 1 << fraction:
        exponent = quantum + bias + fraction
        q -= 1 << fraction
    if exponent >= (1 << exponent_bits) - 1:
        exponent, q = (1 << exponent_bits) - 1, 0
    return sign | (exponent << fraction) | q


def cases(fraction: int, exponent_bits: int) -> list[tuple[int, int, int, int]]:
    sign = 1 << (fraction + exponent_bits)
    infinity = ((1 << exponent_bits) - 1) << fraction
    one = ((1 << (exponent_bits - 1)) - 1) << fraction
    boundary = [0, sign, 1, sign | 1, (1 << fraction) - 1, 1 << fraction,
                (1 << fraction) + 1, one - 1, one, one + 1, infinity - 1]
    operands = [(x, a) for x in boundary for a in boundary if a & (sign - 1)]
    rng = random.Random(0xF040500 + fraction)
    while len(operands) < 1024:
        x, a = rng.getrandbits(fraction + exponent_bits + 1), rng.getrandbits(fraction + exponent_bits + 1)
        if (x & (sign - 1)) < infinity and 0 < (a & (sign - 1)) < infinity:
            operands.append((x, a))
    result = []
    for x, a in operands:
        xv, av = value(x, fraction, exponent_bits), value(a, fraction, exponent_bits)
        neg = bool((x ^ a) & sign)
        result.append((x, a, round_bits(xv * av, fraction, exponent_bits, neg),
                       round_bits(xv / av, fraction, exponent_bits, neg)))
    return result


def render() -> str:
    out = ['// Generated by generate_alpha_golden.py; do not edit by hand.', '#pragma once',
           '#include <array>', '#include <cstdint>', 'namespace alpha_golden {',
           'struct Case { std::uint64_t x, alpha, multiply, divide; };']
    for name, f, e in [('binary32', 23, 8), ('binary64', 52, 11)]:
        rows = cases(f, e)
        out.append(f'inline constexpr std::array<Case, {len(rows)}> {name}{{{{')
        for row in rows:
            out.append('  {' + ', '.join(f'UINT64_C(0x{v:016x})' for v in row) + '},')
        out.append('}};')
    out.append('}  // namespace alpha_golden')
    return '\n'.join(out) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    destination = Path(__file__).with_name('alpha_golden.hpp')
    text = render()
    if args.check:
        if not destination.exists() or destination.read_text() != text:
            raise SystemExit('alpha golden fixture is missing or stale')
        print('alpha golden fixture verified: 2048 pairs, 4096 independent expected results')
    else:
        destination.write_text(text)
        print(destination)


if __name__ == '__main__':
    main()
