/**
 * @file compute_service.cpp
 * @brief Implements the ComputeService facade for sequential, parallel, and
 * dirty update compute entry points.
 *
 * ComputeService keeps its internal C++ member surface and request
 * orchestration. That member surface is private backend API, not the
 * installable product public API; frontends call `ps::Host`. Node execution,
 * dirty ROI execution, HP-to-RT downsample refresh, task graph dispatch, cache
 * policy, input resolution, and metrics metadata are delegated to the
 * compute-service collaborators under
 * src/kernel/services/compute-service.
 */
#include "kernel/services/compute_service.hpp"

#include <chrono>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "benchmark/benchmark_types.hpp"
#include "kernel/graph_runtime.hpp"
#include "kernel/param_utils.hpp"
#include "kernel/services/compute-service/compute_cache_policy.hpp"
#include "kernel/services/compute-service/compute_metrics_recorder.hpp"
#include "kernel/services/compute-service/compute_task_dispatcher.hpp"
#include "kernel/services/compute-service/dirty_sibling_commit_gate.hpp"
#include "kernel/services/compute-service/dirty_update_executor.hpp"
#include "kernel/services/compute-service/intent_update_coordinator.hpp"
#include "kernel/services/compute-service/node_executor.hpp"
#include "kernel/services/compute-service/node_input_resolver.hpp"
#include "kernel/services/compute-service/realtime_proxy_graph.hpp"
#include "kernel/services/compute-service/task_graph_planning.hpp"
#include "kernel/services/graph_cache_service.hpp"
#include "kernel/services/graph_event_service.hpp"
#include "kernel/services/graph_traversal_service.hpp"

namespace ps {

/**
 * @brief Constructs the internal compute orchestrator from borrowed services.
 *
 * @param traversal Traversal service used by planning and dirty execution.
 * @param cache Cache service used by sequential and scheduler HP paths.
 * @param events Event sink used by compute and dirty telemetry.
 * @throws Nothing directly.
 * @note All three services must outlive this ComputeService instance.
 */
ComputeService::ComputeService(GraphTraversalService& traversal,
                               GraphCacheService& cache,
                               GraphEventService& events)
    : traversal_(traversal), cache_(cache), events_(events) {}

/**
 * @brief Destroys service-owned inline RT proxy graph storage.
 *
 * @throws Nothing.
 * @note Runtime-owned proxy graphs and all borrowed services remain untouched.
 */
ComputeService::~ComputeService() = default;

namespace {

/**
 * @brief Finalizes one produced node output through the shared metrics policy.
 *
 * @param output Output generated by an operation and stored in node cache.
 * @param inputs Image inputs used to derive debug and spatial metadata.
 * @param enable_timing Whether timing metadata should be attached.
 * @param execution_ms Measured node execution duration in milliseconds.
 * @return Nothing.
 * @throws std::bad_alloc unchanged when metadata or debug storage exhausts
 * memory.
 * @throws Any other exception propagated by ComputeMetricsRecorder.
 * @note This helper keeps the recursive sequential path aligned with the
 * dispatcher metadata policy.
 */
void finalize_output_metadata(NodeOutput& output,
                              const std::vector<const NodeOutput*>& inputs,
                              bool enable_timing, double execution_ms) {
  compute::ComputeMetricsRecorder::finalize_output_metadata(
      output, inputs, enable_timing, execution_ms);
}

/**
 * @brief Stores the latest compute plan and bounded summary history.
 *
 * @param graph Graph whose inspection state receives the plan snapshot.
 * @param compute_plan Plan produced for the current request.
 * @throws std::bad_alloc if summary history storage cannot grow.
 * @note Full ComputePlan data is kept only for the latest request so
 * inspection history does not copy large task graphs repeatedly.
 */
void remember_facade_compute_plan(GraphModel& graph,
                                  const compute::ComputePlan& compute_plan) {
  graph.last_compute_plan = compute_plan;
  graph.last_compute_plan_summary =
      compute::summarize_compute_plan(graph, compute_plan);
  graph.recent_compute_plan_summaries.push_back(
      *graph.last_compute_plan_summary);
  if (graph.recent_compute_plan_summaries.size() > 16) {
    graph.recent_compute_plan_summaries.erase(
        graph.recent_compute_plan_summaries.begin());
  }
}

/**
 * @brief Selects the planning intent for a ComputeService facade request.
 *
 * @param request Service request whose optional intent may preserve legacy HP
 * behavior.
 * @return Requested intent, or GlobalHighPrecision when the legacy path was
 * selected.
 * @throws Nothing directly.
 * @note A missing intent is only an internal compatibility signal; planning
 * still
 * needs an explicit single-domain compute intent.
 */
ComputeIntent planning_intent_for_request(
    const ComputeService::Request& request) {
  return request.intent.value_or(ComputeIntent::GlobalHighPrecision);
}

/**
 * @brief Builds a planning-layer request from a ComputeService request.
 *
 * @param request Service request carrying target node, intent, and dirty ROI.
 * @param use_parallel_executor Whether the caller selected scheduler-backed
 * execution for this service call.
 * @return Narrow compute::ComputeRequest used by task graph planning.
 * @throws Nothing directly.
 * @note Planning uses only semantic target/domain data and the selected
 * execution mode; cache and telemetry options are consumed later by execution.
 */
compute::ComputeRequest make_planning_request(
    const ComputeService::Request& request, bool use_parallel_executor) {
  return compute::ComputeRequest{planning_intent_for_request(request),
                                 request.node_id, use_parallel_executor,
                                 request.dirty_roi};
}

/**
 * @brief Builds a dispatcher request for full HP task execution.
 *
 * @param request Service request whose cache and telemetry options are used by
 * the dispatcher.
 * @return Immutable dispatcher options for one GlobalHighPrecision run.
 * @throws std::bad_alloc if copying the cache precision string allocates.
 * @note Dirty ROI and intent are intentionally ignored here; dirty and RT
 * semantics are coordinated before this full-frame dispatcher path is invoked.
 */
compute::ComputeTaskDispatcher::ComputeDispatchRequest make_dispatch_request(
    const ComputeService::Request& request) {
  return compute::ComputeTaskDispatcher::ComputeDispatchRequest{
      request.node_id,
      request.cache.precision,
      request.cache.force_recache,
      request.telemetry.enable_timing,
      request.cache.disable_disk_cache,
      request.telemetry.benchmark_events};
}

/**
 * @brief Builds a dirty-executor request from a service request.
 *
 * @param request Service request validated by IntentUpdateCoordinator.
 * @param suppress_graph_downsample Whether HP dirty execution should skip
 * direct HP-to-RT graph downsample writes for this request.
 * @return DirtyUpdateRequest with the requested dirty ROI.
 * @throws std::bad_alloc if copying request cache precision or gate storage
 * exhausts memory.
 * @throws std::bad_optional_access if called before dirty_roi validation.
 * @note Intent-specific executor selection happens in ComputeService; this
 * request only carries the knobs shared by HP and RT dirty executors.
 */
compute::DirtyUpdateRequest make_dirty_update_request(
    const ComputeService::Request& request,
    bool suppress_graph_downsample = false,
    std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate =
        nullptr) {
  return compute::DirtyUpdateRequest{request.node_id,
                                     request.cache.precision,
                                     request.cache.force_recache,
                                     request.telemetry.enable_timing,
                                     request.cache.disable_disk_cache,
                                     request.telemetry.benchmark_events,
                                     request.dirty_roi.value(),
                                     suppress_graph_downsample,
                                     std::move(sibling_commit_gate)};
}

/**
 * @brief Creates the legacy HP-only request used inside intent callbacks.
 *
 * @param request Intent-aware request being coordinated.
 * @return Copy of request with intent and dirty ROI cleared.
 * @throws std::bad_alloc if copying cache precision allocates.
 * @note IntentUpdateCoordinator calls this through HP fallback callbacks; the
 * cleared intent prevents recursion back into intent coordination.
 */
ComputeService::Request make_global_high_precision_request(
    const ComputeService::Request& request) {
  ComputeService::Request hp_request = request;
  hp_request.intent = std::nullopt;
  hp_request.dirty_roi = std::nullopt;
  return hp_request;
}

/**
 * @brief Creates an HP dirty update request that suppresses benchmark output.
 *
 * @param request Dirty intent request whose semantic and cache options are
 * preserved.
 * @return Request copy with benchmark_events cleared.
 * @throws std::bad_alloc if copying cache precision allocates.
 * @note The old HP side-update callback passed nullptr for benchmark_events;
 * keeping that behavior avoids double-counting benchmark records in RT updates.
 */
ComputeService::Request make_silent_dirty_request(
    const ComputeService::Request& request) {
  ComputeService::Request silent_request = request;
  silent_request.telemetry.benchmark_events = nullptr;
  return silent_request;
}

/**
 * @brief Builds the node/cache-pruned plan used by sequential compute.
 *
 * @param graph Graph that supplies topology, node metadata, and cache state.
 * @param request Intent, target node, and optional dirty ROI for the request.
 * @param execution_order Topological execution order for the target cone.
 * @return Compute plan pruned to request target and cache availability.
 * @throws std::bad_alloc unchanged when graph expansion or plan storage
 * exhausts memory.
 * @throws GraphError from full task graph expansion or pruning.
 * @note Dirty update executors have their own same-boundary helper because
 * they also record dirty snapshots and materialized work sets.
 */
compute::ComputePlan prune_facade_node_cache_task_graph(
    GraphModel& graph, const compute::ComputeRequest& request,
    const std::vector<int>& execution_order) {
  compute::NodeCacheTaskGraphPruner node_cache_pruner;
  const std::shared_ptr<const compute::FullTaskGraph> full_graph =
      compute::get_or_expand_full_task_graph(graph, request.intent);
  return node_cache_pruner.prune(*full_graph, request, execution_order, graph);
}

}  // namespace

/**
 * @brief Computes one node output through recursive sequential execution.
 *
 * The recursive path preserves the legacy single-threaded behavior: it checks
 * HP memory cache, optionally loads disk cache, detects cycles, resolves
 * parameter and image inputs, dispatches the selected HP operator through
 * NodeExecutor, commits the HP cache, records timing/events, and saves disk
 * cache when configured.
 *
 * @param graph Graph whose nodes and caches are read and mutated.
 * @param node_id Node id to compute.
 * @param context Request-wide cache, timing, disk-cache, benchmark, and cycle
 * detection state shared by all recursive calls.
 * @return Mutable HP output owned by the target node.
 * @throws std::bad_alloc unchanged when dependency, operation, cache,
 * telemetry, or result storage exhausts memory.
 * @throws GraphError when a cycle, missing dependency, missing operation, disk
 * cache failure, or compute failure occurs.
 * @note This method is used only by the sequential HP path and HP callbacks
 * that explicitly select sequential execution. Scheduler-backed dispatch does
 * not call this method as a compatibility fallback.
 */
NodeOutput& ComputeService::compute_internal(
    GraphModel& graph, int node_id, const RecursiveComputeContext& context) {
  auto& timing_results = graph.timing_results;
  auto& timing_mutex = graph.timing_mutex_;
  auto& target_node = graph.mutable_node(node_id);
  std::string result_source = "unknown";

  auto start_time_total = std::chrono::high_resolution_clock::now();

  BenchmarkEvent current_event;
  current_event.node_id = node_id;
  current_event.op_name = make_key(target_node.type, target_node.subtype);
  current_event.dependency_start_time = start_time_total;

  std::vector<const NodeOutput*> monolithic_inputs;
  do {
    if (compute::ComputeCachePolicy::has_reusable_output(target_node)) {
      result_source = "memory_cache";
      break;
    }
    if (context.allow_disk_cache &&
        cache_.try_load_from_disk_cache(graph, target_node)) {
      result_source = "disk_cache";
      break;
    }

    if (context.visiting[node_id]) {
      throw GraphError(GraphErrc::Cycle,
                       "Cycle detected: " + std::to_string(node_id));
    }
    context.visiting[node_id] = true;

    auto resolved_inputs = compute::NodeInputResolver::resolve(
        target_node,
        [&](int upstream_id) -> const NodeOutput* {
          return &compute_internal(graph, upstream_id, context);
        },
        "Sequential compute");
    monolithic_inputs = resolved_inputs.image_inputs;

    auto op_opt = OpRegistry::instance().resolve_for_intent(
        target_node.type, target_node.subtype,
        ComputeIntent::GlobalHighPrecision);
    if (!op_opt) {
      throw GraphError(GraphErrc::NoOperation, "No op for " + target_node.type +
                                                   ":" + target_node.subtype);
    }

    current_event.execution_start_time =
        std::chrono::high_resolution_clock::now();

    target_node.cached_output_high_precision = compute::NodeExecutor::execute(
        graph, target_node, *op_opt, monolithic_inputs);

    current_event.execution_end_time =
        std::chrono::high_resolution_clock::now();
    result_source = "computed";
    target_node.hp_version++;
    cache_.save_cache_if_configured(graph, target_node,
                                    context.cache_precision);
    context.visiting[node_id] = false;
  } while (false);

  auto end_time_total = std::chrono::high_resolution_clock::now();
  if (result_source == "computed") {
    current_event.execution_end_time = end_time_total;
  } else {
    current_event.execution_start_time = end_time_total;
    current_event.execution_end_time = end_time_total;
  }

  current_event.source = result_source;
  double execution_duration_ms =
      std::chrono::duration<double, std::milli>(
          current_event.execution_end_time - current_event.execution_start_time)
          .count();
  if (execution_duration_ms < 0) {
    execution_duration_ms = 0.0;
  }

  if (result_source == "computed" && target_node.cached_output_high_precision) {
    finalize_output_metadata(*target_node.cached_output_high_precision,
                             monolithic_inputs, context.enable_timing,
                             execution_duration_ms);
  }

  if (context.enable_timing) {
    {
      std::lock_guard lk(timing_mutex);
      timing_results.node_timings.push_back({target_node.id, target_node.name,
                                             execution_duration_ms,
                                             result_source});
    }
    events_.push(target_node.id, target_node.name, result_source,
                 execution_duration_ms);
  } else {
    events_.push(target_node.id, target_node.name, result_source, 0.0);
  }

  if (context.benchmark_events) {
    current_event.execution_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_end_time -
            current_event.execution_start_time)
            .count();
    current_event.dependency_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_start_time -
            current_event.dependency_start_time)
            .count();
    context.benchmark_events->push_back(current_event);
  }

  return *compute::ComputeCachePolicy::reusable_output(target_node);
}

/**
 * @brief Delegates HP dirty ROI execution to HighPrecisionDirtyExecutor.
 *
 * @param graph Graph whose HP dirty state and cache are updated.
 * @param proxy_graph RT proxy graph that may receive GlobalHighPrecision
 * downsample output after HP commit.
 * @param strategy Execution strategy that may supply a scheduler runtime.
 * @param request Request carrying target, cache, telemetry, and dirty ROI.
 * @param sibling_commit_gate Optional RealTimeUpdate gate that delays HP graph
 * commit until RT proxy commit succeeds.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when dirty planning, task, cache, or output
 * storage exhausts memory.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation; std::bad_optional_access if dirty_roi is missing
 * before coordinator validation.
 * @note This method intentionally contains no node-level dirty execution logic;
 * ComputeService remains only the internal orchestration boundary; C++
 * `public:` access on its backend members does not make them product Host API.
 */
NodeOutput& ComputeService::compute_high_precision_update(
    GraphModel& graph, compute::RealtimeProxyGraph& proxy_graph,
    const ExecutionStrategy& strategy, const Request& request,
    std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate) {
  compute::HighPrecisionDirtyExecutor executor(traversal_, events_);
  return executor.execute(graph, proxy_graph, strategy.runtime,
                          make_dirty_update_request(
                              request, false, std::move(sibling_commit_gate)));
}

/**
 * @brief Delegates RT dirty ROI execution to RealTimeDirtyExecutor.
 *
 * @param graph Graph used for topology, parameters, and HP fallback output.
 * @param proxy_graph RT proxy graph whose low-resolution state is updated.
 * @param strategy Execution strategy that may supply a scheduler runtime.
 * @param request Request carrying target, cache, telemetry, and dirty ROI.
 * @return Mutable target RT output stored in the proxy graph.
 * @throws std::bad_alloc unchanged when dirty planning, task, proxy, or output
 * storage exhausts memory.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation; std::bad_optional_access if dirty_roi is missing
 * before coordinator validation.
 * @note RT dirty output stays outside GraphModel and does not become reusable
 * HP cache authority.
 */
NodeOutput& ComputeService::compute_real_time_update(
    GraphModel& graph, compute::RealtimeProxyGraph& proxy_graph,
    const ExecutionStrategy& strategy, const Request& request) {
  compute::RealTimeDirtyExecutor executor(traversal_, events_);
  return executor.execute(graph, proxy_graph, strategy.runtime,
                          make_dirty_update_request(request));
}

/**
 * @brief Resolves runtime-owned or service-owned RT proxy graph storage.
 *
 * @param graph Graph address used as the inline proxy map key.
 * @param strategy Strategy that may provide GraphRuntime ownership.
 * @return Runtime proxy when available, otherwise an inline service proxy.
 * @throws std::bad_alloc unchanged if inline proxy map or object allocation
 * exhausts memory.
 * @note Inline map access is serialized by inline_rt_proxy_graphs_mutex_.
 */
compute::RealtimeProxyGraph& ComputeService::realtime_proxy_graph_for(
    GraphModel& graph, const ExecutionStrategy& strategy) {
  if (strategy.runtime) {
    return strategy.runtime->realtime_proxy_graph();
  }
  std::lock_guard<std::mutex> lock(inline_rt_proxy_graphs_mutex_);
  auto& proxy = inline_rt_proxy_graphs_[&graph];
  if (!proxy) {
    proxy = std::make_unique<compute::RealtimeProxyGraph>();
  }
  return *proxy;
}

/**
 * @brief Executes a full high-precision compute request through a scheduler.
 *
 * @param graph Graph being computed.
 * @param runtime Graph runtime that owns the HP scheduler.
 * @param request Service request carrying target, cache, telemetry, and
 * optional intent semantics.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when planning, task dispatch, operation,
 * cache, telemetry, or result storage exhausts memory.
 * @throws GraphError from scheduler lookup, task dispatch, cache access, or
 * missing target output.
 * @note Legacy HP requests run the full-frame dispatcher directly. Requests
 * with intent are routed through compute_intent_update_impl.
 */
NodeOutput& ComputeService::compute_parallel(GraphModel& graph,
                                             GraphRuntime& runtime,
                                             const Request& request) {
  if (request.intent) {
    return compute_intent_update_impl(graph, ExecutionStrategy{&runtime, true},
                                      request);
  }

  compute::ComputeTaskDispatcher executor(traversal_, cache_, events_);
  SchedulerTaskRuntime& task_runtime = compute::ensure_scheduler_task_runtime(
      runtime, ComputeIntent::GlobalHighPrecision);
  return executor.execute(graph, task_runtime, make_dispatch_request(request));
}

/**
 * @brief Coordinates intent semantics and binds ComputeService callbacks.
 *
 * @param graph Graph being computed.
 * @param strategy Runtime and scheduler-backed execution policy.
 * @param request Intent-aware request carrying target, cache, telemetry, and
 * optional dirty ROI.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws std::bad_alloc unchanged when callback, scheduler, dirty, cache, or
 * output storage exhausts memory.
 * @throws GraphError from intent validation, callback execution, scheduler
 * lookup, or missing target output.
 * @note The coordinator owns HP/RT dual-path semantics; ComputeService only
 * supplies the concrete execution callbacks.
 */
NodeOutput& ComputeService::compute_intent_update_impl(
    GraphModel& graph, const ExecutionStrategy& strategy,
    const Request& request) {
  compute::IntentUpdateCallbacks callbacks;
  const ComputeIntent intent = request.intent.value();
  compute::RealtimeProxyGraph& rt_proxy_graph =
      realtime_proxy_graph_for(graph, strategy);
  std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate;
  if (intent == ComputeIntent::RealTimeUpdate) {
    sibling_commit_gate = std::make_shared<compute::DirtySiblingCommitGate>();
    callbacks.sibling_commit_gate = sibling_commit_gate;
  }
  const Node* coordinator_node = graph.find_node(request.node_id);
  const std::string coordinator_node_name =
      coordinator_node ? coordinator_node->name : std::string();
  callbacks.run_global_high_precision = [&]() -> NodeOutput& {
    const Request hp_request = make_global_high_precision_request(request);
    if (strategy.use_parallel_executor) {
      if (!strategy.runtime) {
        throw GraphError(GraphErrc::ComputeError,
                         "Parallel HP compute requires a runtime.");
      }
      return compute_parallel(graph, *strategy.runtime, hp_request);
    }
    return compute(graph, hp_request);
  };
  callbacks.run_global_high_precision_dirty_update = [&]() -> NodeOutput& {
    return compute_high_precision_update(graph, rt_proxy_graph, strategy,
                                         request);
  };
  callbacks.run_high_precision_update = [&]() {
    const Request silent_request = make_silent_dirty_request(request);
    compute::HighPrecisionDirtyExecutor executor(traversal_, events_);
    executor.execute(
        graph, rt_proxy_graph, strategy.runtime,
        make_dirty_update_request(silent_request, true, sibling_commit_gate));
  };
  callbacks.run_real_time_update = [&]() -> NodeOutput& {
    NodeOutput& output =
        compute_real_time_update(graph, rt_proxy_graph, strategy, request);
    if (sibling_commit_gate) {
      sibling_commit_gate->mark_rt_committed();
    }
    return output;
  };
  callbacks.real_time_output = [&]() -> NodeOutput& {
    return rt_proxy_graph.require_output(request.node_id);
  };
  callbacks.record_stage = [&,
                            coordinator_node_name](const std::string& stage) {
    events_.push(request.node_id, coordinator_node_name, stage, 0.0);
  };

  SchedulerTaskRuntime* hp_task_runtime = nullptr;
  SchedulerTaskRuntime* rt_task_runtime = nullptr;
  if (strategy.use_parallel_executor && strategy.runtime) {
    hp_task_runtime = &compute::ensure_scheduler_task_runtime(
        *strategy.runtime, ComputeIntent::GlobalHighPrecision);
    if (intent == ComputeIntent::RealTimeUpdate) {
      rt_task_runtime = &compute::ensure_scheduler_task_runtime(
          *strategy.runtime, ComputeIntent::RealTimeUpdate);
    }
  }

  return compute::IntentUpdateCoordinator::coordinate_intent_update(
      intent, hp_task_runtime, rt_task_runtime, request.dirty_roi, callbacks);
}

/**
 * @brief Executes an intent-aware request without a GraphRuntime.
 *
 * @param graph Graph being computed.
 * @param request Intent-aware request carrying target, cache, telemetry, and
 * optional dirty ROI.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws std::bad_alloc unchanged when coordination, dirty execution, cache,
 * or output storage exhausts memory.
 * @throws GraphError from intent validation or execution.
 * @note Dirty HP and RT callbacks still use the dirty executors, but run node
 * work inline because no scheduler runtime is available.
 */
NodeOutput& ComputeService::compute_with_intent_impl(GraphModel& graph,
                                                     const Request& request) {
  return compute_intent_update_impl(graph, ExecutionStrategy{}, request);
}

/**
 * @brief Internal non-parallel ComputeService entry point.
 *
 * @param graph Graph being computed.
 * @param request Service request carrying target, cache, telemetry, and
 * optional intent semantics.
 * @return Mutable output selected by the request.
 * @throws std::bad_alloc unchanged when any Host-reachable compute stage
 * exhausts memory.
 * @throws GraphError from validation, planning, recursive compute, or cache
 * operations.
 * @note A missing intent selects the legacy GlobalHighPrecision path.
 */
NodeOutput& ComputeService::compute(GraphModel& graph, const Request& request) {
  if (request.intent) {
    return compute_with_intent_impl(graph, request);
  }
  return compute_sequential_impl(graph, request);
}

/**
 * @brief Implements sequential high-precision compute with plan inspection.
 *
 * @param graph Graph being computed.
 * @param request Legacy HP request with target, cache, and telemetry options.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when planning, recursion, cache, telemetry,
 * or result storage exhausts memory.
 * @throws GraphError when the target is missing, topology is invalid, planning
 * fails, recursive compute fails, or target output is unavailable.
 * @note The method records the same node/cache-pruned plan shape used by the
 * parallel path before delegating to the recursive executor.
 */
NodeOutput& ComputeService::compute_sequential_impl(GraphModel& graph,
                                                    const Request& request) {
  if (!graph.has_node(request.node_id)) {
    throw GraphError(
        GraphErrc::NotFound,
        "Node " + std::to_string(request.node_id) + " not found in graph.");
  }

  if (request.telemetry.benchmark_events) {
    request.telemetry.benchmark_events->clear();
  }

  if (request.telemetry.enable_timing) {
    clear_timing_results(graph);
  }

  if (request.cache.force_recache) {
    graph.clear_full_task_graph_cache();
  }

  std::vector<int> execution_order;
  try {
    execution_order = traversal_.topo_postorder_from(graph, request.node_id);
  } catch (const GraphError&) {
    throw;
  }
  const compute::ComputeRequest planning_request =
      make_planning_request(request, false);
  const compute::ComputePlan compute_plan = prune_facade_node_cache_task_graph(
      graph, planning_request, execution_order);
  remember_facade_compute_plan(graph, compute_plan);
  execution_order = compute_plan.planned_nodes;

  if (request.cache.force_recache) {
    std::lock_guard<std::mutex> lk(graph.graph_mutex_);
    for (int nid : execution_order) {
      auto& node = graph.mutable_node(nid);
      node.cached_output_high_precision.reset();
    }
  }

  std::unordered_map<int, bool> visiting;
  const bool allow_disk_cache =
      !request.cache.disable_disk_cache && !request.cache.force_recache;
  const RecursiveComputeContext context{
      request.cache.precision, visiting, request.telemetry.enable_timing,
      allow_disk_cache, request.telemetry.benchmark_events};
  NodeOutput& result = compute_internal(graph, request.node_id, context);

  if (request.telemetry.enable_timing) {
    double total = 0.0;
    {
      std::lock_guard<std::mutex> lk(graph.timing_mutex_);
      for (const auto& timing : graph.timing_results.node_timings) {
        total += timing.elapsed_ms;
      }
      graph.timing_results.total_ms = total;
    }
  }

  return result;
}

/**
 * @brief Clears timing results for one graph.
 *
 * @param graph Graph whose TimingCollector should be reset.
 * @return Nothing.
 * @throws Nothing directly.
 * @note The method holds graph.timing_mutex_ while mutating timing fields.
 */
void ComputeService::clear_timing_results(GraphModel& graph) {
  std::lock_guard<std::mutex> lk(graph.timing_mutex_);
  graph.timing_results.node_timings.clear();
  graph.timing_results.total_ms = 0.0;
}

}  // namespace ps
