/**
 * @file compute_service.cpp
 * @brief Implements the ComputeService facade for sequential, parallel, and
 * dirty update compute entry points.
 *
 * ComputeService keeps its internal C++ member surface and request
 * orchestration. That member surface is private backend API, not the
 * installable product public API; frontends call `ps::Host`. Node execution,
 * dirty ROI execution, HP-to-RT downsample refresh, task graph dispatch, cache
 * policy, input resolution, and metrics metadata are delegated to the
 * compute-service collaborators under
 * src/lib/compute/.
 */
#include "compute/compute_service.hpp"

#include <chrono>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "benchmark/benchmark_types.hpp"
#include "compute/compute_cache_policy.hpp"
#include "compute/compute_metrics_recorder.hpp"
#include "compute/compute_run.hpp"
#include "compute/compute_task_dispatcher.hpp"
#include "compute/dirty_sibling_commit_gate.hpp"
#include "compute/dirty_update_executor.hpp"
#include "compute/execution_service.hpp"
#include "compute/intent_update_coordinator.hpp"
#include "compute/node_executor.hpp"
#include "compute/node_input_resolver.hpp"
#include "compute/realtime_proxy_graph.hpp"
#include "compute/task_graph_planning.hpp"
#include "core/param_utils.hpp"
#include "graph/graph_cache_service.hpp"
#include "graph/graph_traversal_service.hpp"
#include "runtime/graph_event_service.hpp"
#include "runtime/graph_runtime.hpp"

namespace ps {

/**
 * @brief Constructs the internal compute orchestrator from borrowed services.
 *
 * @param traversal Traversal service used by planning and dirty execution.
 * @param cache Cache service used by sequential and scheduler HP paths.
 * @param events Event sink used by compute and dirty telemetry.
 * @param execution_service Explicit process CPU execution owner.
 * @throws Nothing directly.
 * @note All four services must outlive this ComputeService instance.
 */
ComputeService::ComputeService(GraphTraversalService& traversal,
                               GraphCacheService& cache,
                               GraphEventService& events,
                               compute::ExecutionService& execution_service)
    : traversal_(traversal),
      cache_(cache),
      events_(events),
      execution_service_(execution_service) {
}  // NOLINT(whitespace/indent_namespace)

/**
 * @brief Destroys service-owned inline RT proxy graph storage.
 *
 * @throws Nothing.
 * @note Runtime-owned proxy graphs and all borrowed services remain untouched.
 */
ComputeService::~ComputeService() = default;

namespace {

/**
 * @brief Finalizes one produced node output through the shared metrics policy.
 *
 * @param output Output generated by an operation and stored in node cache.
 * @param inputs Image inputs used to derive debug and spatial metadata.
 * @param enable_timing Whether timing metadata should be attached.
 * @param execution_ms Measured node execution duration in milliseconds.
 * @return Nothing.
 * @throws std::bad_alloc unchanged when metadata or debug storage exhausts
 * memory.
 * @throws Any other exception propagated by ComputeMetricsRecorder.
 * @note This helper keeps the recursive sequential path aligned with the
 * dispatcher metadata policy.
 */
void finalize_output_metadata(NodeOutput& output,
                              const std::vector<const NodeOutput*>& inputs,
                              bool enable_timing, double execution_ms) {
  compute::ComputeMetricsRecorder::finalize_output_metadata(
      output, inputs, enable_timing, execution_ms);
}

/**
 * @brief Stores the latest compute plan and bounded summary history.
 *
 * @param graph Graph whose inspection state receives the plan snapshot.
 * @param compute_plan Plan produced for the current request.
 * @throws std::bad_alloc if summary history storage cannot grow.
 * @note Full ComputePlan data is kept only for the latest request so
 * inspection history does not copy large task graphs repeatedly.
 */
void remember_facade_compute_plan(GraphModel& graph,
                                  const compute::ComputePlan& compute_plan) {
  graph.last_compute_plan = compute_plan;
  graph.last_compute_plan_summary =
      compute::summarize_compute_plan(graph, compute_plan);
  graph.recent_compute_plan_summaries.push_back(
      *graph.last_compute_plan_summary);
  if (graph.recent_compute_plan_summaries.size() > 16) {
    graph.recent_compute_plan_summaries.erase(
        graph.recent_compute_plan_summaries.begin());
  }
}

/**
 * @brief Selects the planning intent for a ComputeService facade request.
 *
 * @param request Service request whose optional intent may preserve legacy HP
 * behavior.
 * @return Requested intent, or GlobalHighPrecision when the legacy path was
 * selected.
 * @throws Nothing directly.
 * @note A missing intent is only an internal compatibility signal; planning
 * still
 * needs an explicit single-domain compute intent.
 */
ComputeIntent planning_intent_for_request(
    const ComputeService::Request& request) {
  return request.intent.value_or(ComputeIntent::GlobalHighPrecision);
}

/**
 * @brief Builds a planning-layer request from a ComputeService request.
 *
 * @param request Service request carrying target node, intent, and dirty ROI.
 * @param use_parallel_executor Whether the caller selected scheduler-backed
 * execution for this service call.
 * @return Narrow compute::ComputeRequest used by task graph planning.
 * @throws Nothing directly.
 * @note Planning uses only semantic target/domain data and the selected
 * execution mode; cache and telemetry options are consumed later by execution.
 */
compute::ComputeRequest make_planning_request(
    const ComputeService::Request& request, bool use_parallel_executor) {
  return compute::ComputeRequest{planning_intent_for_request(request),
                                 request.node_id, use_parallel_executor,
                                 request.dirty_roi};
}

/**
 * @brief Builds a dispatcher request for full HP task execution.
 *
 * @param request Service request whose cache and telemetry options are used by
 * the dispatcher.
 * @return Immutable dispatcher options for one GlobalHighPrecision run.
 * @throws std::bad_alloc if copying the cache precision string allocates.
 * @note Dirty ROI and intent are intentionally ignored here; dirty and RT
 * semantics are coordinated before this full-frame dispatcher path is invoked.
 */
compute::ComputeTaskDispatcher::ComputeDispatchRequest make_dispatch_request(
    const ComputeService::Request& request) {
  return compute::ComputeTaskDispatcher::ComputeDispatchRequest{
      request.node_id,
      request.cache.precision,
      request.cache.force_recache,
      request.telemetry.enable_timing,
      request.cache.disable_disk_cache,
      request.telemetry.benchmark_events};
}

/**
 * @brief Builds a dirty-executor request from a service request.
 *
 * @param request Service request validated by IntentUpdateCoordinator.
 * @param suppress_graph_downsample Whether HP dirty execution should skip
 * direct HP-to-RT graph downsample writes for this request.
 * @param sibling_commit_gate Optional HP commit gate shared with the RT
 * sibling.
 * @param stabilized_parameters Optional immutable connected-parameter snapshot.
 * @param node_synchronization Optional per-node critical sections shared by the
 * concurrent HP and RT siblings of one RealTimeUpdate transaction.
 * @return DirtyUpdateRequest with the requested dirty ROI.
 * @throws std::bad_alloc if copying request cache precision or gate storage
 * exhausts memory.
 * @throws std::bad_optional_access if called before dirty_roi validation.
 * @note Intent-specific executor selection happens in ComputeService; this
 * request only carries the knobs shared by HP and RT dirty executors.
 */
compute::DirtyUpdateRequest make_dirty_update_request(
    const ComputeService::Request& request,
    bool suppress_graph_downsample = false,
    std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate =
        nullptr,
    std::shared_ptr<const compute::StabilizedDirtyParameters>
        stabilized_parameters = nullptr,
    std::shared_ptr<compute::DirtyNodeSynchronization> node_synchronization =
        nullptr) {
  return compute::DirtyUpdateRequest{request.node_id,
                                     request.cache.precision,
                                     request.cache.force_recache,
                                     request.telemetry.enable_timing,
                                     request.cache.disable_disk_cache,
                                     request.telemetry.benchmark_events,
                                     request.dirty_roi.value(),
                                     suppress_graph_downsample,
                                     std::move(sibling_commit_gate),
                                     std::move(stabilized_parameters),
                                     std::move(node_synchronization)};
}

/**
 * @brief Creates the legacy HP-only request used inside intent callbacks.
 *
 * @param request Intent-aware request being coordinated.
 * @return Copy of request with intent and dirty ROI cleared.
 * @throws std::bad_alloc if copying cache precision allocates.
 * @note IntentUpdateCoordinator calls this through HP fallback callbacks; the
 * cleared intent prevents recursion back into intent coordination.
 */
ComputeService::Request make_global_high_precision_request(
    const ComputeService::Request& request) {
  ComputeService::Request hp_request = request;
  hp_request.intent = std::nullopt;
  hp_request.dirty_roi = std::nullopt;
  return hp_request;
}

/**
 * @brief Creates an HP dirty update request that suppresses benchmark output.
 *
 * @param request Dirty intent request whose semantic and cache options are
 * preserved.
 * @return Request copy with benchmark_events cleared.
 * @throws std::bad_alloc if copying cache precision allocates.
 * @note The old HP side-update callback passed nullptr for benchmark_events;
 * keeping that behavior avoids double-counting benchmark records in RT updates.
 */
ComputeService::Request make_silent_dirty_request(
    const ComputeService::Request& request) {
  ComputeService::Request silent_request = request;
  silent_request.telemetry.benchmark_events = nullptr;
  return silent_request;
}

/**
 * @brief Builds the node/cache-pruned plan used by sequential compute.
 *
 * @param graph Graph that supplies topology, node metadata, and cache state.
 * @param request Intent, target node, and optional dirty ROI for the request.
 * @param execution_order Topological execution order for the target cone.
 * @return Compute plan pruned to request target and cache availability.
 * @throws std::bad_alloc unchanged when graph expansion or plan storage
 * exhausts memory.
 * @throws GraphError from full task graph expansion or pruning.
 * @note Dirty update executors have their own same-boundary helper because
 * they also record dirty snapshots and materialized work sets.
 */
compute::ComputePlan prune_facade_node_cache_task_graph(
    GraphModel& graph, const compute::ComputeRequest& request,
    const std::vector<int>& execution_order) {
  compute::NodeCacheTaskGraphPruner node_cache_pruner;
  const std::shared_ptr<const compute::FullTaskGraph> full_graph =
      compute::get_or_expand_full_task_graph(graph, request.intent);
  return node_cache_pruner.prune(*full_graph, request, execution_order, graph);
}

/**
 * @brief Reports whether one service request belongs to paired realtime work.
 *
 * @param request Request whose optional intent selects the domain.
 * @return true only for explicit RealTimeUpdate.
 * @throws Nothing.
 * @note Missing intent and explicit GlobalHighPrecision are both non-realtime
 * HP requests and receive one request-owned ComputeRun.
 */
bool is_realtime_request(const ComputeService::Request& request) {
  return request.intent == ComputeIntent::RealTimeUpdate;
}

/**
 * @brief Captures immutable single-domain Run inputs before service planning.
 *
 * @param graph Graph supplying authoritative instance identity and revision.
 * @param request Service request supplying graph identity, target, and QoS.
 * @param intent HP or RT domain owned by the new Run.
 * @return Owned descriptor inputs for one single-domain ComputeRun.
 * @throws std::bad_alloc if graph identity copying allocates.
 * @throws std::invalid_argument if intent is not HP or RT.
 * @note Topology generation remains a separate planning-cache key and is not
 * stored in the Run descriptor.
 */
compute::ComputeRunSubmission make_run_submission(
    const GraphModel& graph, const ComputeService::Request& request,
    ComputeIntent intent) {
  if (intent != ComputeIntent::GlobalHighPrecision &&
      intent != ComputeIntent::RealTimeUpdate) {
    throw std::invalid_argument(
        "ComputeService Run submission requires HP or RT intent.");
  }
  return compute::ComputeRunSubmission{
      request.graph_identity,
      graph.instance_id(),
      graph.revision(),
      request.node_id,
      intent,
      intent == ComputeIntent::RealTimeUpdate
          ? compute::ComputeRunQuality::Interactive
          : compute::ComputeRunQuality::Full,
      request.qos};
}

/**
 * @brief Advances a normally executing Run to the visible-commit boundary.
 * @param run HP or RT Run whose local domain output has been validated.
 * @return Nothing.
 * @throws GraphError when the Run is already terminal or cannot reach
 *         CommitPending on the current success path.
 * @note Full and dirty dispatchers may already publish CommitPending. The
 *       helper makes sequential and every product wrapper follow the same
 *       terminal ordering without treating an idempotent phase as failure.
 */
void require_commit_pending(compute::ComputeRun& run) {
  if (run.phase() == compute::ComputeRunPhase::CommitPending) {
    return;
  }
  if (!run.advance_to(compute::ComputeRunPhase::CommitPending)) {
    throw GraphError(GraphErrc::ComputeError,
                     "ComputeRun cannot enter staged commit.");
  }
}

/**
 * @brief Invokes the optional product HP commit policy.
 * @param run Commit-pending HP Run.
 * @param graph Exact staged Graph used by execution.
 * @param proxy Optional staged proxy modified by the HP domain.
 * @param request Request carrying the private product policy.
 * @return Nothing after policy publication, or immediately without a policy.
 * @throws Any exact policy validation or persistence failure unchanged.
 */
void commit_high_precision_if_requested(
    const compute::ComputeRun& run, GraphModel& graph,
    compute::RealtimeProxyGraph* proxy,
    const ComputeService::Request& request) {
  if (request.commit_policy) {
    request.commit_policy->commit_high_precision(run, graph, proxy);
  }
}

/**
 * @brief Invokes the optional product RT commit policy.
 * @param run Commit-pending RT child Run.
 * @param graph Exact staged Graph used for request planning.
 * @param proxy Exact staged RT proxy used by execution.
 * @param request Request carrying the private product policy.
 * @return Nothing after policy publication, or immediately without a policy.
 * @throws Any exact policy validation failure unchanged.
 */
void commit_real_time_if_requested(const compute::ComputeRun& run,
                                   GraphModel& graph,
                                   compute::RealtimeProxyGraph& proxy,
                                   const ComputeService::Request& request) {
  if (request.commit_policy) {
    request.commit_policy->commit_real_time(run, graph, proxy);
  }
}

/**
 * @brief Settles one request-owned HP Run around an execution callback.
 *
 * @tparam Execute Callable returning the validated target NodeOutput reference.
 * @tparam Commit Callable publishing the staged HP domain after execution.
 * @param run Run whose admission and exactly-one terminal outcome are owned by
 * this wrapper.
 * @param execute Sequential, full scheduler, or standalone dirty HP callback.
 * @param commit Commit-policy callback invoked only after CommitPending.
 * @return Mutable target output returned by execute.
 * @throws Rethrows the exact callback exception after publishing Run failure.
 * @throws GraphError if another terminal claimant unexpectedly wins before a
 * normal current-path return.
 * @note A normal return publishes success only after the callback has validated
 * committed or reusable target output. Failure publication retains the
 * original std::exception_ptr before rethrow.
 */
template <typename Execute, typename Commit>
NodeOutput& execute_request_owned_hp_run(compute::ComputeRun& run,
                                         Execute&& execute, Commit&& commit) {
  try {
    run.advance_to(compute::ComputeRunPhase::Admitted);
    NodeOutput& output = std::forward<Execute>(execute)();
    require_commit_pending(run);
    std::forward<Commit>(commit)();
    if (!run.publish_succeeded()) {
      throw GraphError(
          GraphErrc::ComputeError,
          "ComputeRun terminal outcome was claimed before HP success.");
    }
    return output;
  } catch (...) {
    const std::exception_ptr failure = std::current_exception();
    (void)run.publish_failed(failure);
    std::rethrow_exception(failure);
  }
}

/**
 * @brief Settles one realtime child Run around its domain callback.
 *
 * @tparam Execute Callable returning the committed child-domain output.
 * @tparam Commit Callable publishing the staged child domain after execution.
 * @param run Already admitted HP or RT child Run.
 * @param execute Dirty executor callback for that child's single domain.
 * @param commit Commit-policy callback invoked only after CommitPending.
 * @return Mutable domain output returned by execute.
 * @throws Rethrows the exact callback exception after publishing child
 * failure.
 * @throws GraphError if another terminal claimant wins before normal return.
 * @note This wrapper does not admit the Run because the paired request wrapper
 * admits both children before any shared preflight or sibling launch.
 */
template <typename Execute, typename Commit>
NodeOutput& execute_realtime_child_run(compute::ComputeRun& run,
                                       Execute&& execute, Commit&& commit) {
  try {
    NodeOutput& output = std::forward<Execute>(execute)();
    require_commit_pending(run);
    std::forward<Commit>(commit)();
    if (!run.publish_succeeded()) {
      throw GraphError(
          GraphErrc::ComputeError,
          "ComputeRun terminal outcome was claimed before child success.");
    }
    return output;
  } catch (...) {
    const std::exception_ptr failure = std::current_exception();
    (void)run.publish_failed(failure);
    std::rethrow_exception(failure);
  }
}

/**
 * @brief Admits and failure-contains one paired realtime request.
 *
 * @tparam Execute Callable coordinating the separate HP and RT children.
 * @param hp_run GlobalHighPrecision child Run.
 * @param rt_run RealTimeUpdate child Run.
 * @param execute Callback that runs shared preflight and sibling coordination.
 * @return Mutable committed RT output returned by execute.
 * @throws Rethrows the exact coordinator exception after best-effort failure
 * publication for every child that did not already settle.
 * @throws GraphError if normal return leaves either child unsettled.
 * @note The children remain independent terminal domains; this helper is not a
 * RunGroup and provides no cancellation, supersession, or revision policy.
 */
template <typename Execute>
NodeOutput& execute_request_owned_realtime_runs(compute::ComputeRun& hp_run,
                                                compute::ComputeRun& rt_run,
                                                Execute&& execute) {
  try {
    hp_run.advance_to(compute::ComputeRunPhase::Admitted);
    rt_run.advance_to(compute::ComputeRunPhase::Admitted);
    NodeOutput& output = std::forward<Execute>(execute)();
    if (!hp_run.is_terminal() || !rt_run.is_terminal()) {
      throw GraphError(
          GraphErrc::ComputeError,
          "Realtime coordination returned before both child Runs settled.");
    }
    return output;
  } catch (...) {
    const std::exception_ptr failure = std::current_exception();
    if (!hp_run.is_terminal()) {
      (void)hp_run.publish_failed(failure);
    }
    if (!rt_run.is_terminal()) {
      (void)rt_run.publish_failed(failure);
    }
    std::rethrow_exception(failure);
  }
}

}  // namespace

/**
 * @brief Computes one node output through recursive sequential execution.
 *
 * The recursive path preserves the legacy single-threaded behavior: it checks
 * HP memory cache, optionally loads disk cache, detects cycles, resolves
 * parameter and image inputs on a request-local Node snapshot, dispatches that
 * snapshot to the selected HP operator through NodeExecutor, commits the HP
 * cache, records timing/events, and saves disk cache when configured. Effective
 * runtime parameters are never written into the graph-owned Node.
 *
 * @param graph Graph whose nodes and caches are read and mutated.
 * @param node_id Node id to compute.
 * @param context Request-wide cache, timing, disk-cache, benchmark, and cycle
 * detection state shared by all recursive calls.
 * @return Mutable HP output owned by the target node.
 * @throws std::bad_alloc unchanged when dependency, operation, cache,
 * telemetry, or result storage exhausts memory.
 * @throws GraphError when a cycle, missing dependency, missing operation, disk
 * cache failure, or compute failure occurs.
 * @note This method is used only by the sequential HP path and HP callbacks
 * that explicitly select sequential execution. Scheduler-backed dispatch does
 * not call this method as a compatibility fallback. The resolved input-size
 * hint retains its existing Graph state behavior, while runtime parameters and
 * other operation-facing state remain request-local.
 */
NodeOutput& ComputeService::compute_internal(
    GraphModel& graph, int node_id, const RecursiveComputeContext& context) {
  auto& timing_results = graph.timing_results;
  auto& timing_mutex = graph.timing_mutex_;
  auto& target_node = graph.mutable_node(node_id);
  std::string result_source = "unknown";

  auto start_time_total = std::chrono::high_resolution_clock::now();

  BenchmarkEvent current_event;
  current_event.node_id = node_id;
  current_event.op_name = make_key(target_node.type, target_node.subtype);
  current_event.dependency_start_time = start_time_total;

  std::vector<const NodeOutput*> monolithic_inputs;
  do {
    if (compute::ComputeCachePolicy::has_reusable_output(target_node)) {
      result_source = "memory_cache";
      break;
    }
    if (context.allow_disk_cache &&
        cache_.try_load_from_disk_cache(graph, target_node)) {
      result_source = "disk_cache";
      break;
    }

    if (context.visiting[node_id]) {
      throw GraphError(GraphErrc::Cycle,
                       "Cycle detected: " + std::to_string(node_id));
    }
    context.visiting[node_id] = true;

    Node execution_node = target_node;
    auto resolved_inputs = compute::NodeInputResolver::resolve(
        execution_node,
        [&](int upstream_id) -> const NodeOutput* {
          return &compute_internal(graph, upstream_id, context);
        },
        "Sequential compute");
    target_node.last_input_size_hp = execution_node.last_input_size_hp;
    monolithic_inputs = resolved_inputs.image_inputs;

    auto op_opt = OpRegistry::instance().resolve_for_intent(
        execution_node.type, execution_node.subtype,
        ComputeIntent::GlobalHighPrecision);
    if (!op_opt) {
      throw GraphError(
          GraphErrc::NoOperation,
          "No op for " + execution_node.type + ":" + execution_node.subtype);
    }

    current_event.execution_start_time =
        std::chrono::high_resolution_clock::now();

    target_node.cached_output_high_precision = compute::NodeExecutor::execute(
        graph, execution_node, *op_opt, monolithic_inputs);

    current_event.execution_end_time =
        std::chrono::high_resolution_clock::now();
    result_source = "computed";
    target_node.hp_version++;
    cache_.save_cache_if_configured(graph, target_node,
                                    context.cache_precision);
    context.visiting[node_id] = false;
  } while (false);

  auto end_time_total = std::chrono::high_resolution_clock::now();
  if (result_source == "computed") {
    current_event.execution_end_time = end_time_total;
  } else {
    current_event.execution_start_time = end_time_total;
    current_event.execution_end_time = end_time_total;
  }

  current_event.source = result_source;
  double execution_duration_ms =
      std::chrono::duration<double, std::milli>(
          current_event.execution_end_time - current_event.execution_start_time)
          .count();
  if (execution_duration_ms < 0) {
    execution_duration_ms = 0.0;
  }

  if (result_source == "computed" && target_node.cached_output_high_precision) {
    finalize_output_metadata(*target_node.cached_output_high_precision,
                             monolithic_inputs, context.enable_timing,
                             execution_duration_ms);
  }

  if (context.enable_timing) {
    {
      std::lock_guard lk(timing_mutex);
      timing_results.node_timings.push_back({target_node.id, target_node.name,
                                             execution_duration_ms,
                                             result_source});
    }
    events_.push(target_node.id, target_node.name, result_source,
                 execution_duration_ms);
  } else {
    events_.push(target_node.id, target_node.name, result_source, 0.0);
  }

  if (context.benchmark_events) {
    current_event.execution_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_end_time -
            current_event.execution_start_time)
            .count();
    current_event.dependency_duration_ms =
        std::chrono::duration<double, std::milli>(
            current_event.execution_start_time -
            current_event.dependency_start_time)
            .count();
    context.benchmark_events->push_back(current_event);
  }

  return *compute::ComputeCachePolicy::reusable_output(target_node);
}

/**
 * @brief Delegates HP dirty ROI execution to HighPrecisionDirtyExecutor.
 *
 * @param graph Graph whose HP dirty state and cache are updated.
 * @param proxy_graph RT proxy graph that may receive GlobalHighPrecision
 * downsample output after HP commit.
 * @param strategy Execution strategy that may supply a scheduler runtime.
 * @param request Request carrying target, cache, telemetry, and dirty ROI.
 * @param sibling_commit_gate Optional RealTimeUpdate gate that delays HP graph
 * commit until RT proxy commit succeeds.
 * @param stabilized_parameters Optional immutable connected-parameter snapshot.
 * @param run GlobalHighPrecision Run that owns dirty HP staging, task leases,
 * and phase state.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when dirty planning, task, cache, or output
 * storage exhausts memory.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation; std::bad_optional_access if dirty_roi is missing
 * before coordinator validation.
 * @note This method intentionally contains no node-level dirty execution logic;
 * ComputeService remains only the internal orchestration boundary; C++
 * `public:` access on its backend members does not make them product Host API.
 */
NodeOutput& ComputeService::compute_high_precision_update(
    GraphModel& graph, compute::RealtimeProxyGraph& proxy_graph,
    const ExecutionStrategy& strategy, const Request& request,
    std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate,
    std::shared_ptr<const compute::StabilizedDirtyParameters>
        stabilized_parameters,
    compute::ComputeRun* run) {
  compute::ExecutionService* cpu_service = nullptr;
  if (strategy.use_parallel_executor) {
    if (!strategy.runtime) {
      throw GraphError(GraphErrc::ComputeError,
                       "Parallel HP dirty compute requires a runtime.");
    }
    const GraphRuntime::SchedulerExecutionRoute route =
        strategy.runtime->get_scheduler_execution_route(
            ComputeIntent::GlobalHighPrecision);
    if (route.domain ==
        GraphRuntime::SchedulerExecutionRoute::Domain::ProcessCpuService) {
      if (!run || !execution_service_.is_configured()) {
        throw GraphError(
            GraphErrc::ComputeError,
            "HP process-service route requires a configured service and Run.");
      }
      cpu_service = &execution_service_;
    }
  }
  compute::HighPrecisionDirtyExecutor executor(traversal_, events_);
  return executor.execute(
      graph, proxy_graph, strategy.runtime,
      make_dirty_update_request(request, false, std::move(sibling_commit_gate),
                                std::move(stabilized_parameters)),
      run, cpu_service);
}

/**
 * @brief Delegates RT dirty ROI execution to RealTimeDirtyExecutor.
 *
 * @param graph Graph used for topology, parameters, and HP fallback output.
 * @param proxy_graph RT proxy graph whose low-resolution state is updated.
 * @param strategy Execution strategy that may supply a scheduler runtime.
 * @param request Request carrying target, cache, telemetry, and dirty ROI.
 * @param stabilized_parameters Optional immutable connected-parameter snapshot.
 * @param node_synchronization Optional per-node critical sections shared with
 * the concurrent HP sibling of the same RealTimeUpdate transaction.
 * @param run RealTimeUpdate child Run owning task leases and lifecycle state.
 * @return Mutable target RT output stored in the proxy graph.
 * @throws std::bad_alloc unchanged when dirty planning, task, proxy, or output
 * storage exhausts memory.
 * @throws GraphError from dirty planning, execution, scheduler dispatch, or
 * target output validation; std::bad_optional_access if dirty_roi is missing
 * before coordinator validation.
 * @note RT dirty output stays outside GraphModel and does not become reusable
 * HP cache authority. The synchronization owner is request-scoped and is not
 * stored in GraphModel, GraphRuntime, or process state.
 */
NodeOutput& ComputeService::compute_real_time_update(
    GraphModel& graph, compute::RealtimeProxyGraph& proxy_graph,
    const ExecutionStrategy& strategy, const Request& request,
    std::shared_ptr<const compute::StabilizedDirtyParameters>
        stabilized_parameters,
    std::shared_ptr<compute::DirtyNodeSynchronization> node_synchronization,
    compute::ComputeRun* run) {
  compute::ExecutionService* cpu_service = nullptr;
  if (strategy.use_parallel_executor) {
    if (!strategy.runtime) {
      throw GraphError(GraphErrc::ComputeError,
                       "Parallel RT dirty compute requires a runtime.");
    }
    const GraphRuntime::SchedulerExecutionRoute route =
        strategy.runtime->get_scheduler_execution_route(
            ComputeIntent::RealTimeUpdate);
    if (route.domain ==
        GraphRuntime::SchedulerExecutionRoute::Domain::ProcessCpuService) {
      if (!run || !execution_service_.is_configured()) {
        throw GraphError(
            GraphErrc::ComputeError,
            "RT process-service route requires a configured service and Run.");
      }
      cpu_service = &execution_service_;
    }
  }
  compute::RealTimeDirtyExecutor executor(traversal_, events_);
  return executor.execute(
      graph, proxy_graph, strategy.runtime,
      make_dirty_update_request(request, false, nullptr,
                                std::move(stabilized_parameters),
                                std::move(node_synchronization)),
      run, cpu_service);
}

/**
 * @brief Resolves runtime-owned or service-owned RT proxy graph storage.
 *
 * @param graph Graph address used as the inline proxy map key.
 * @param strategy Strategy that may provide GraphRuntime ownership.
 * @param request Request that may provide a staged proxy override.
 * @return Staged override, runtime proxy, or inline service proxy.
 * @throws std::bad_alloc unchanged if inline proxy map or object allocation
 * exhausts memory.
 * @note Inline map access is serialized by inline_rt_proxy_graphs_mutex_.
 */
compute::RealtimeProxyGraph& ComputeService::realtime_proxy_graph_for(
    GraphModel& graph, const ExecutionStrategy& strategy,
    const Request& request) {
  if (request.staged_realtime_proxy) {
    return *request.staged_realtime_proxy;
  }
  if (strategy.runtime) {
    return strategy.runtime->realtime_proxy_graph();
  }
  std::lock_guard<std::mutex> lock(inline_rt_proxy_graphs_mutex_);
  auto& proxy = inline_rt_proxy_graphs_[&graph];
  if (!proxy) {
    proxy = std::make_unique<compute::RealtimeProxyGraph>();
  }
  return *proxy;
}

/**
 * @brief Executes one full execution-bound HP request through its Run.
 *
 * @param graph Graph being computed.
 * @param runtime Graph runtime that publishes the HP execution binding:
 * ownerless process CPU service or an owned legacy scheduler.
 * @param request Full HP target, cache, and telemetry options.
 * @param run Request observer for leased plan, runner, callback, temporary
 * result, exception, and lifecycle state.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when planning, task dispatch, operation,
 * cache, telemetry, Run storage, or result storage exhausts memory.
 * @throws GraphError from scheduler lookup, task dispatch, cache access, or
 * missing target output.
 * @note Built-in CPU planning routes ready submissions through the injected
 * ExecutionService; plugin, GPU, and serial planning retain the Graph-owned
 * scheduler path. Both routes synchronously settle while full-HP callbacks own
 * Run leases and composite identity without borrowed TaskExecutor pointers.
 */
NodeOutput& ComputeService::compute_parallel_hp_impl(GraphModel& graph,
                                                     GraphRuntime& runtime,
                                                     const Request& request,
                                                     compute::ComputeRun& run) {
  compute::ComputeTaskDispatcher executor(traversal_, cache_, events_);
  const GraphRuntime::SchedulerExecutionRoute execution_route =
      runtime.get_scheduler_execution_route(ComputeIntent::GlobalHighPrecision);
  if (execution_route.domain ==
      GraphRuntime::SchedulerExecutionRoute::Domain::ProcessCpuService) {
    return executor.execute(graph, execution_service_, runtime,
                            make_dispatch_request(request), run);
  }
  IScheduler& scheduler = compute::ensure_running_scheduler(
      runtime, ComputeIntent::GlobalHighPrecision);
  return executor.execute(graph, scheduler, make_dispatch_request(request),
                          run);
}

/**
 * @brief Executes an execution-bound compute request through the selected
 * domain boundary.
 *
 * @param graph Graph being computed.
 * @param runtime Graph runtime that publishes each intent's execution binding:
 * ownerless process CPU service or an owned legacy scheduler.
 * @param request Service request carrying target, cache, telemetry, intent,
 * dirty ROI, graph identity, and QoS.
 * @return Mutable target output selected by the request.
 * @throws std::bad_alloc unchanged when Run construction, planning, task
 * dispatch, operation, cache, telemetry, or result storage exhausts memory.
 * @throws GraphError from scheduler lookup, planning, task dispatch, dirty
 * execution, cache access, or missing target output.
 * @note Every non-realtime HP request creates exactly one Run before planning.
 * RealTimeUpdate creates separate HP and RT child Runs before preflight; no
 * mixed-domain Run or final RunGroup policy is introduced here.
 */
NodeOutput& ComputeService::compute_parallel(GraphModel& graph,
                                             GraphRuntime& runtime,
                                             const Request& request) {
  if (is_realtime_request(request)) {
    compute::ComputeRun hp_run(make_run_submission(
        graph, request, ComputeIntent::GlobalHighPrecision));
    compute::ComputeRun rt_run(
        make_run_submission(graph, request, ComputeIntent::RealTimeUpdate));
    return execute_request_owned_realtime_runs(
        hp_run, rt_run, [&]() -> NodeOutput& {
          return compute_intent_update_impl(graph,
                                            ExecutionStrategy{&runtime, true},
                                            request, &hp_run, &rt_run);
        });
  }

  compute::ComputeRun run(
      make_run_submission(graph, request, ComputeIntent::GlobalHighPrecision));
  return execute_request_owned_hp_run(
      run,
      [&]() -> NodeOutput& {
        if (request.intent) {
          return compute_intent_update_impl(
              graph, ExecutionStrategy{&runtime, true}, request, &run, nullptr);
        }
        return compute_parallel_hp_impl(graph, runtime, request, run);
      },
      [&] {
        commit_high_precision_if_requested(
            run, graph, request.staged_realtime_proxy, request);
      });
}

/**
 * @brief Coordinates intent semantics and binds ComputeService callbacks.
 *
 * @param graph Graph being computed.
 * @param strategy Runtime and scheduler-backed execution policy.
 * @param request Intent-aware request carrying target, cache, telemetry, and
 * optional dirty ROI.
 * @param hp_run Request-owned HP Run. Realtime requests supply their HP child.
 * @param rt_run Request-owned RT child Run, or null for
 * GlobalHighPrecision.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws std::bad_alloc unchanged when callback, scheduler, dirty, cache, or
 * output storage exhausts memory.
 * @throws GraphError from intent validation, callback execution, scheduler
 * lookup, or missing target output.
 * @note The coordinator owns HP/RT dual-path semantics; ComputeService only
 * supplies the concrete execution callbacks. Explicit GlobalHighPrecision
 * callbacks reuse hp_run and never recurse through a Run-creating public
 * entry. Realtime callbacks settle separate HP and RT children.
 */
NodeOutput& ComputeService::compute_intent_update_impl(
    GraphModel& graph, const ExecutionStrategy& strategy,
    const Request& request, compute::ComputeRun* hp_run,
    compute::ComputeRun* rt_run) {
  compute::IntentUpdateCallbacks callbacks;
  const ComputeIntent intent = request.intent.value();
  compute::IntentUpdateCoordinator::validate(intent, request.dirty_roi);
  if (intent == ComputeIntent::GlobalHighPrecision &&
      (hp_run == nullptr || rt_run != nullptr)) {
    throw GraphError(
        GraphErrc::ComputeError,
        "GlobalHighPrecision intent requires only its HP ComputeRun.");
  }
  if (intent == ComputeIntent::RealTimeUpdate &&
      (hp_run == nullptr || rt_run == nullptr)) {
    throw GraphError(GraphErrc::ComputeError,
                     "RealTimeUpdate requires separate HP and RT child Runs.");
  }

  IScheduler* hp_scheduler = nullptr;
  IScheduler* rt_scheduler = nullptr;
  bool hp_uses_process_service = false;
  bool rt_uses_process_service = false;
  bool can_submit_concurrently = false;
  if (strategy.use_parallel_executor) {
    if (!strategy.runtime) {
      throw GraphError(GraphErrc::ComputeError,
                       "Parallel intent compute requires a runtime.");
    }

    const GraphRuntime::SchedulerExecutionRoute hp_route =
        strategy.runtime->get_scheduler_execution_route(
            ComputeIntent::GlobalHighPrecision);
    hp_uses_process_service =
        hp_route.domain ==
        GraphRuntime::SchedulerExecutionRoute::Domain::ProcessCpuService;
    if (hp_uses_process_service) {
      if (!execution_service_.is_configured()) {
        throw GraphError(
            GraphErrc::ComputeError,
            "HP process-service route requires a configured service.");
      }
    } else {
      hp_scheduler = &compute::ensure_running_scheduler(
          *strategy.runtime, ComputeIntent::GlobalHighPrecision);
    }

    if (intent == ComputeIntent::RealTimeUpdate) {
      const GraphRuntime::SchedulerExecutionRoute rt_route =
          strategy.runtime->get_scheduler_execution_route(
              ComputeIntent::RealTimeUpdate);
      rt_uses_process_service =
          rt_route.domain ==
          GraphRuntime::SchedulerExecutionRoute::Domain::ProcessCpuService;
      if (rt_uses_process_service) {
        if (!execution_service_.is_configured()) {
          throw GraphError(
              GraphErrc::ComputeError,
              "RT process-service route requires a configured service.");
        }
      } else {
        rt_scheduler = &compute::ensure_running_scheduler(
            *strategy.runtime, ComputeIntent::RealTimeUpdate);
      }
      const bool hp_available =
          hp_uses_process_service ||
          (hp_scheduler != nullptr && hp_scheduler->is_running());
      const bool rt_available =
          rt_uses_process_service ||
          (rt_scheduler != nullptr && rt_scheduler->is_running());
      can_submit_concurrently = hp_available && rt_available;
    }
  }

  std::shared_ptr<const compute::StabilizedDirtyParameters>
      stabilized_parameters;
  std::shared_ptr<compute::DirtyNodeSynchronization> node_synchronization;
  if (request.dirty_roi && request.dirty_roi->width > 0 &&
      request.dirty_roi->height > 0) {
    SchedulerTaskRuntime* preflight_runtime = nullptr;
    compute::ExecutionService* preflight_service = nullptr;
    SchedulerHostContext* preflight_host = nullptr;
    if (hp_uses_process_service) {
      preflight_service = &execution_service_;
      preflight_host = strategy.runtime;
    } else if (strategy.use_parallel_executor) {
      preflight_runtime = hp_scheduler;
    }
    uint64_t request_generation = 0;
    uint64_t topology_generation = 0;
    {
      std::lock_guard<std::mutex> lock(graph.graph_mutex_);
      request_generation = ++graph.dirty_generation_counter;
      topology_generation = graph.topology_generation();
      if (intent == ComputeIntent::RealTimeUpdate && can_submit_concurrently) {
        node_synchronization =
            std::make_shared<compute::DirtyNodeSynchronization>(
                graph.node_ids());
      }
    }
    stabilized_parameters = compute::stabilize_connected_dirty_parameters(
        graph, traversal_, request.node_id, request_generation,
        topology_generation, preflight_runtime, preflight_service,
        preflight_host, hp_run);
  }

  compute::RealtimeProxyGraph& rt_proxy_graph =
      realtime_proxy_graph_for(graph, strategy, request);
  std::shared_ptr<compute::DirtySiblingCommitGate> sibling_commit_gate;
  if (intent == ComputeIntent::RealTimeUpdate) {
    sibling_commit_gate = std::make_shared<compute::DirtySiblingCommitGate>();
    callbacks.sibling_commit_gate = sibling_commit_gate;
  }
  const Node* coordinator_node = graph.find_node(request.node_id);
  const std::string coordinator_node_name =
      coordinator_node ? coordinator_node->name : std::string();
  callbacks.run_global_high_precision = [&]() -> NodeOutput& {
    const Request hp_request = make_global_high_precision_request(request);
    if (!hp_run) {
      throw GraphError(
          GraphErrc::ComputeError,
          "GlobalHighPrecision callback has no request-owned ComputeRun.");
    }
    if (strategy.use_parallel_executor) {
      if (!strategy.runtime) {
        throw GraphError(GraphErrc::ComputeError,
                         "Parallel HP compute requires a runtime.");
      }
      return compute_parallel_hp_impl(graph, *strategy.runtime, hp_request,
                                      *hp_run);
    }
    return compute_sequential_impl(graph, hp_request, *hp_run);
  };
  callbacks.run_global_high_precision_dirty_update = [&]() -> NodeOutput& {
    return compute_high_precision_update(graph, rt_proxy_graph, strategy,
                                         request, nullptr,
                                         stabilized_parameters, hp_run);
  };
  callbacks.run_high_precision_update = [&]() {
    if (!hp_run) {
      throw GraphError(GraphErrc::ComputeError,
                       "Realtime HP callback has no child Run.");
    }
    const Request silent_request = make_silent_dirty_request(request);
    (void)execute_realtime_child_run(
        *hp_run,
        [&]() -> NodeOutput& {
          compute::HighPrecisionDirtyExecutor executor(traversal_, events_);
          return executor.execute(
              graph, rt_proxy_graph, strategy.runtime,
              make_dirty_update_request(
                  silent_request, true, sibling_commit_gate,
                  stabilized_parameters, node_synchronization),
              hp_run, hp_uses_process_service ? &execution_service_ : nullptr);
        },
        [&] {
          commit_high_precision_if_requested(*hp_run, graph, &rt_proxy_graph,
                                             request);
        });
  };
  callbacks.run_real_time_update = [&]() -> NodeOutput& {
    if (!rt_run) {
      throw GraphError(GraphErrc::ComputeError,
                       "Realtime RT callback has no child Run.");
    }
    NodeOutput& output = execute_realtime_child_run(
        *rt_run,
        [&]() -> NodeOutput& {
          return compute_real_time_update(graph, rt_proxy_graph, strategy,
                                          request, stabilized_parameters,
                                          node_synchronization, rt_run);
        },
        [&] {
          commit_real_time_if_requested(*rt_run, graph, rt_proxy_graph,
                                        request);
        });
    if (sibling_commit_gate) {
      sibling_commit_gate->mark_rt_committed();
    }
    return output;
  };
  callbacks.real_time_output = [&]() -> NodeOutput& {
    return rt_proxy_graph.require_output(request.node_id);
  };
  callbacks.record_stage = [&,
                            coordinator_node_name](const std::string& stage) {
    events_.push(request.node_id, coordinator_node_name, stage, 0.0);
  };

  return compute::IntentUpdateCoordinator::coordinate_intent_update(
      intent, can_submit_concurrently, request.dirty_roi, callbacks);
}

/**
 * @brief Executes an intent-aware request without a GraphRuntime.
 *
 * @param graph Graph being computed.
 * @param request Intent-aware request carrying target, cache, telemetry, and
 * optional dirty ROI.
 * @param hp_run Request-owned HP Run. Realtime requests supply their HP child.
 * @param rt_run Request-owned RT child Run, or null for
 * GlobalHighPrecision.
 * @return Mutable output selected by IntentUpdateCoordinator.
 * @throws std::bad_alloc unchanged when coordination, dirty execution, cache,
 * or output storage exhausts memory.
 * @throws GraphError from intent validation or execution.
 * @note Dirty HP and RT callbacks still use the dirty executors, but run node
 * work inline because no scheduler runtime is available. The realtime path
 * receives separate HP and RT child Runs without a mixed-domain owner.
 */
NodeOutput& ComputeService::compute_with_intent_impl(
    GraphModel& graph, const Request& request, compute::ComputeRun* hp_run,
    compute::ComputeRun* rt_run) {
  return compute_intent_update_impl(graph, ExecutionStrategy{}, request, hp_run,
                                    rt_run);
}

/**
 * @brief Internal non-parallel ComputeService entry point.
 *
 * @param graph Graph being computed.
 * @param request Service request carrying target, cache, telemetry, and
 * optional intent semantics.
 * @return Mutable output selected by the request.
 * @throws std::bad_alloc unchanged when any Host-reachable compute stage
 * exhausts memory.
 * @throws GraphError from validation, planning, recursive compute, or cache
 * operations.
 * @note Missing intent and explicit GlobalHighPrecision both create exactly one
 * request-owned Run before planning. RealTimeUpdate creates separate HP and RT
 * child Runs without a mixed-domain Run.
 */
NodeOutput& ComputeService::compute(GraphModel& graph, const Request& request) {
  if (is_realtime_request(request)) {
    compute::ComputeRun hp_run(make_run_submission(
        graph, request, ComputeIntent::GlobalHighPrecision));
    compute::ComputeRun rt_run(
        make_run_submission(graph, request, ComputeIntent::RealTimeUpdate));
    return execute_request_owned_realtime_runs(
        hp_run, rt_run, [&]() -> NodeOutput& {
          return compute_with_intent_impl(graph, request, &hp_run, &rt_run);
        });
  }

  compute::ComputeRun run(
      make_run_submission(graph, request, ComputeIntent::GlobalHighPrecision));
  return execute_request_owned_hp_run(
      run,
      [&]() -> NodeOutput& {
        if (request.intent) {
          return compute_with_intent_impl(graph, request, &run, nullptr);
        }
        return compute_sequential_impl(graph, request, run);
      },
      [&] {
        commit_high_precision_if_requested(
            run, graph, request.staged_realtime_proxy, request);
      });
}

/**
 * @brief Implements sequential high-precision compute with plan inspection.
 *
 * @param graph Graph being computed.
 * @param request Legacy HP request with target, cache, and telemetry options.
 * @param run Request-owned HP descriptor and terminal/storage owner.
 * @return Mutable target HP output stored in the graph.
 * @throws std::bad_alloc unchanged when planning, recursion, cache, telemetry,
 * or result storage exhausts memory.
 * @throws GraphError when the target is missing, topology is invalid, planning
 * fails, recursive compute fails, or target output is unavailable.
 * @note The method records the same node/cache-pruned plan shape used by the
 * parallel path before delegating to the recursive executor. The direct
 * recursive algorithm has no temporary staging object and may skip
 * CommitPending.
 */
NodeOutput& ComputeService::compute_sequential_impl(GraphModel& graph,
                                                    const Request& request,
                                                    compute::ComputeRun& run) {
  if (!graph.has_node(request.node_id)) {
    throw GraphError(
        GraphErrc::NotFound,
        "Node " + std::to_string(request.node_id) + " not found in graph.");
  }

  if (request.telemetry.benchmark_events) {
    request.telemetry.benchmark_events->clear();
  }

  if (request.telemetry.enable_timing) {
    clear_timing_results(graph);
  }

  if (request.cache.force_recache) {
    graph.clear_full_task_graph_cache();
  }

  run.advance_to(compute::ComputeRunPhase::Running);
  std::vector<int> execution_order;
  try {
    execution_order = traversal_.topo_postorder_from(graph, request.node_id);
  } catch (const GraphError&) {
    throw;
  }
  const compute::ComputeRequest planning_request =
      make_planning_request(request, false);
  const compute::ComputePlan compute_plan = prune_facade_node_cache_task_graph(
      graph, planning_request, execution_order);
  remember_facade_compute_plan(graph, compute_plan);
  execution_order = compute_plan.planned_nodes;

  if (request.cache.force_recache) {
    std::lock_guard<std::mutex> lk(graph.graph_mutex_);
    for (int nid : execution_order) {
      auto& node = graph.mutable_node(nid);
      node.cached_output_high_precision.reset();
    }
  }

  std::unordered_map<int, bool> visiting;
  const bool allow_disk_cache =
      !request.cache.disable_disk_cache && !request.cache.force_recache;
  const RecursiveComputeContext context{
      request.cache.precision, visiting, request.telemetry.enable_timing,
      allow_disk_cache, request.telemetry.benchmark_events};
  NodeOutput& result = compute_internal(graph, request.node_id, context);

  if (request.telemetry.enable_timing) {
    double total = 0.0;
    {
      std::lock_guard<std::mutex> lk(graph.timing_mutex_);
      for (const auto& timing : graph.timing_results.node_timings) {
        total += timing.elapsed_ms;
      }
      graph.timing_results.total_ms = total;
    }
  }

  return result;
}

/**
 * @brief Clears timing results for one graph.
 *
 * @param graph Graph whose TimingCollector should be reset.
 * @return Nothing.
 * @throws Nothing directly.
 * @note The method holds graph.timing_mutex_ while mutating timing fields.
 */
void ComputeService::clear_timing_results(GraphModel& graph) {
  std::lock_guard<std::mutex> lk(graph.timing_mutex_);
  graph.timing_results.node_timings.clear();
  graph.timing_results.total_ms = 0.0;
}

}  // namespace ps
