"""Emit per-key NUM/CRV cost coverage, checked against the live public registry.

Usage: python3 cost_inventory.py /path/to/photospider_numeric_inventory
The table records analytic cost and the relevant measurement driver. A driver
link is not a claim that every parameter/key has an individual timing row.
"""
from pathlib import Path
import re
import csv
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
SPECS = ROOT / 'docs/built-in_ops/01-numeric/op_specs'
GROUPS = {
    'NUM-01': ('numeric_expression.cpp', 'O(Q * AST); strict refinement depends on precision', 'expression'),
    'NUM-02': ('numeric_sequences.cpp', 'O(Q * L); scalar inputs, per-atom dependency stages', 'category_benchmark'),
    'NUM-03': ('numeric_arrays.cpp', 'O(1) view or O(Q) dense copy', 'category_benchmark'),
    'NUM-04': ('numeric_unary.cpp', 'O(Q) ordinary; strict transcendental refinement depends on P', 'unary'),
    'NUM-05': ('numeric_binary.cpp', 'O(Q) ordinary; pow/angle refinement depends on P', 'binary'),
    'NUM-06': ('numeric_ranges.cpp', 'O(Q); bounded rational fallback; regional mapped input reads', 'category_benchmark'),
    'NUM-07': ('numeric_comparisons.cpp', 'O(Q); exact predicates/selection, selected-source demand', 'category_benchmark'),
    'NUM-08': ('numeric_interpolation.cpp', 'O(Q); smoothstep regional, mix staged factor/source reads', 'category_benchmark'),
    'NUM-09': ('numeric_layouts.cpp', 'O(boxes) view or O(Q) copy', 'category_benchmark'),
    'NUM-10': ('numeric_indexing.cpp', 'O(Q) gather/concat; scatter requires full index/contributor validation', 'category_benchmark'),
    'NUM-11': ('numeric_reductions.cpp', 'O(S * L); bounded streamed accumulators, exact count/min/max', 'category_benchmark'),
    'NUM-12': ('numeric_ordering.cpp', 'O(S log S) stable sort; one permutation per demanded line and output; regional publication', 'category_benchmark'),
    'NUM-13': ('numeric_scans.cpp', 'prefix O(S * L + Q), windows of 64; integral_image up to O(Q * S * L) for overlapping rectangles', 'category_benchmark'),
    'NUM-14': ('numeric_matrix.cpp', 'O(Q * C); C<=4; exact dot with dyadic final rounding', 'category_benchmark'),
    'NUM-15': ('numeric_calculus.cpp', 'O(Q) derivative; O(S * L + Q) cumulative integral, windows of 64', 'category_benchmark'),
    'CRV-01': ('curve_interpolation.cpp', 'O(K) topology plus O(Q log K); bounded linear/PCHIP stencil', 'curves'),
    'CRV-02': ('bezier_function.cpp', 'O(K) topology plus Q times bounded exact root refinement', 'bezier'),
    'CRV-03': ('parametric_bezier.cpp', 'O(Q * C); degree<=3; selected control reads', 'category_benchmark'),
    'CRV-05': ('lut1d_application.cpp', 'O(K) axis validation plus O(Q log K)', 'category_benchmark'),
    'CRV-06': ('color_ramps.cpp', 'O(K) stop validation plus O(Q*C); transfer/hue certification varies', 'category_benchmark'),
    'CRV-07': ('lut3d_application.cpp', 'O(Q*C); 4/8 selected vertices; exact weights and validation', 'category_benchmark'),
    'CRV-08': ('log_shaper.cpp', 'O(Q); exact algebraic or certified log/exponential paths', 'category_benchmark'),
    'CRV-10': ('curve_inverse.cpp', 'O(K) topology plus Q times bracket/refinement work', 'signal_benchmark'),
    'CRV-11': ('lowpass_uniform.cpp / lowpass_nonuniform.cpp', 'O(Q*T) uniform, certified coefficients reused; nonuniform geometry/polynomials may dominate', 'signal_benchmark'),
}
legacy = ['numeric.cast','numeric.encode_range','numeric.add','numeric.subtract',
          'numeric.multiply','numeric.divide','numeric.clamp','numeric.mean',
          'numeric.ordered_scan','numeric.variance','numeric.minimum','numeric.maximum',
          'numeric.abs','field.apply_lut_1d','field.smoothstep','math.add',
          'curve.sample_linear','curve.sample_monotone','numeric.sample_expression',
          'lut.apply_1d','curve.pack_lut3d','curve.measure_lut3d',
          'curve.unpack_lut3d','curve.gate_lut3d']
registry = set(subprocess.check_output([sys.argv[1]], text=True).splitlines())
rows = {}
for path in sorted(SPECS.glob('*.md')):
    text = path.read_text()
    match = re.search(r'proposed_operation_keys:\n((?:  - [^\n]+\n)+)', text)
    if not match:
        continue
    group = path.name[:6]
    for key in re.findall(r'  - (\S+)', match[1]):
        rows.setdefault(key, (path.name, group))
assert not (set(rows) & set(legacy))
missing = (set(rows) | set(legacy)) - registry
assert not missing, sorted(missing)
print('# 01-numeric operation cost inventory\n')
print(f'The live public registry resolves {len(rows)} specified profile keys and '
      f'{len(legacy)} additional maintained keys, {len(rows)+len(legacy)} total. '
      'This table is generated by `examples/numeric_workflow/cost_inventory.py`.\n')
print('Q is requested output count; S is actually demanded source count; K is table/stop count; '
      'T is tap count; C is component count; L is active exact-integer width; P is refinement precision. '
      'Big-O describes numeric work. Dependency construction, validation, publication and allocator '
      'work are separately included in public workflow timings.\n')
print('The measurement column identifies a driver, not an individual measured result for every key. '
      'The extended and legacy modes now provide an ordinary workload for every modern basename '
      'and maintained legacy key. Profiles share the listed implementation, but measured timings '
      'below apply only to the stated profile and workload, not every parameter or platform. '
      'Current implementation and measured limitations are recorded in the accelerated specification under docs/built-in_ops/01-numeric/op_specs/NUM_accelerated_contract.md.\n')
print('| Operation key | Specification | Shared implementation / numeric cost | Measurement driver |\n'
      '| --- | --- | --- | --- |')
for key, (spec, group) in sorted(rows.items()):
    source, cost, driver = GROUPS[group]
    if group == 'CRV-11' and 'lowpass' not in key:
        source, cost, driver = GROUPS['CRV-01']
    print(f'| `{key}` | [{spec.split("_")[0]}](op_specs/{spec}) | `{source}`; {cost} | `{driver}` |')
LEGACY_COSTS = {
    'math.add': 'O(1) scalar arithmetic and publication',
    'numeric.mean': 'O(S) ordered streaming reduction; bounded block/carry state',
    'numeric.variance': 'O(S) ordered streaming moments; bounded block/carry state',
    'numeric.ordered_scan': 'up to O(Q*S) per-atom prefixes; admitted checkpoints can reduce repeated work',
    'numeric.sample_expression': 'O(AST + Q*AST); legacy Whole callback parses then evaluates; bounded expression scratch',
    'curve.sample_linear': 'O(K+Q) validation and monotone segment walk; Whole execution',
    'curve.sample_monotone': 'O(K+Q) slopes and monotone segment walk; O(K) scratch; Whole execution',
    'field.apply_lut_1d': 'O(K+Q) full table validation plus constant-size local interpolation; Whole execution',
    'lut.apply_1d': 'O(K+Q) typed table validation and compensated local interpolation',
    'curve.pack_lut3d': 'O(S) full source validation/copy into an owned Result',
    'curve.measure_lut3d': 'O(S*L) exact tolerance checks over declared probe/reference data',
    'curve.unpack_lut3d': 'O(Q) bounded Result windows and packed output copies',
    'curve.gate_lut3d': 'O(1) report/association gate plus O(Q) Result windows and copies',
}
for key in legacy:
    cost = LEGACY_COSTS.get(key, 'O(Q) finite native arithmetic/conversion and dense publication; legacy semantics')
    print(f'| `{key}` | Maintained legacy/template support | {cost} | `category_benchmark legacy` |')

if len(sys.argv) > 2:
    directory = Path(sys.argv[2])
    def measurements(version):
        result = {}
        for group in ('unary','binary','category','signal','extended','legacy','expression'):
            for row in csv.DictReader((directory / f'{version}-{group}.csv').open()):
                if group == 'expression':
                    if row['region'] != 'Whole' or row['expression'] != 'exp(x)':
                        continue
                    key = 'numeric.sample_expression_accelerated_apple_silicon'
                    row['output_shape'] = row['M']
                    row['source_elements'] = row['scalar_support']
                else:
                    key = row['operation']
                    if '.' not in key:
                        key = 'numeric.' + key + '_accelerated_apple_silicon'
                if key == 'bake_lut3d_identity':
                    continue
                row['driver'] = group
                result[key] = row  # Last row is the larger declared workload.
        return result
    before, after = measurements('before'), measurements('after')
    wanted = {key for key in rows if key.endswith('_accelerated_apple_silicon')} | set(legacy)
    assert wanted <= before.keys() and wanted <= after.keys(), sorted(wanted - (before.keys() & after.keys()))
    print('\n## Measured ordinary workloads\n')
    print('All 110 modern basenames and all 24 legacy keys have an individual row. '
          'Modern rows are Apple Silicon accelerated on M5 / Clang 21.1.3 / RelWithDebInfo; '
          'the strict and x86 keys above retain separate correctness coverage, not invented M5 AVX2 timings. '
          'Each row uses one worker, cache off, one warmup and seven measured executions. '
          'Before is ops-impl eb0e90c8 with measurement-driver changes only. Values are microseconds.\n')
    print('S counts unique certified source elements, not repeated internal reads. '
          'Peak is host-accounted payload bytes; allocator call counts and unavailable metadata are not inferred. '
          'Legacy zero numeric counters mean no numeric instrumentation. The four Result support rows '
          'are explicitly callback times within the same bake workflow; their resource totals cannot be '
          'attributed separately. All other rows measure the complete public execution. '
          'The full raw CSV includes maximum time, shapes, retained memory and metadata where exposed.\n')
    print('| Operation / profile | Output shape or N | Layer | Before median / max | After median / max | Speedup | S | Peak payload | Fallbacks |\n'
          '| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |')
    for key in sorted(wanted):
        a,b=before[key],after[key]
        base = key.removesuffix('_accelerated_apple_silicon')
        label = base + (' (Apple)' if key.endswith('_accelerated_apple_silicon') else ' (legacy)')
        layer = 'callback' if b.get('cluster') == 'callback' else 'workflow'
        shape = b.get('output_shape',b.get('requested',b.get('N','?')))
        source = b.get('source_elements')
        if source is None:
            source = str(int(b['N']) * (2 if b['driver']=='binary' or 'rational' in key else 1))
        peak = b.get('peak_payload',b.get('peak_payload_bytes','unavailable'))
        ratio = f"{int(a['median_us'])/int(b['median_us']):.2f}x" if int(b['median_us']) else '<1 us'
        print(f"| `{label}` | {shape} | {layer} | {a['median_us']} / {a['max_us']} | {b['median_us']} / {b['max_us']} | {ratio} | {source} | {peak} | {b['fallbacks']} |")
