"""Generate certified floor(pi*2^4096), floor(ln(2)*2^4096).

Only exact Python integer/Fraction arithmetic is used. Alternating atan series
and the positive atanh geometric tail bound certify both rounding endpoints.
The generator stops only when lower and upper enclosures have the same floor.
"""
from fractions import Fraction
from pathlib import Path
import sys

BITS = 4096


def atan_bounds(inverse):
    z = Fraction(1, inverse)
    square = z*z
    power = z
    total = Fraction()
    for k in range(5000):
        total += (-1 if k % 2 else 1)*power/(2*k+1)
        power *= square
        next_term = (-1 if (k+1) % 2 else 1)*power/(2*k+3)
        low, high = sorted((total, total+next_term))
        if high-low < Fraction(1, 1 << (BITS+16)):
            return low, high
    raise ArithmeticError('atan enclosure did not converge')


def ln2_bounds():
    z = Fraction(1, 3)
    square = z*z
    power = z
    total = Fraction()
    for k in range(5000):
        total += 2*power/(2*k+1)
        power *= square
        tail = 2*power/((2*k+3)*(1-square))
        if tail < Fraction(1, 1 << (BITS+16)):
            return total, total+tail
    raise ArithmeticError('ln2 enclosure did not converge')


def certified_floor(bounds):
    lower, upper = (x*(1 << BITS) for x in bounds)
    lo = lower.numerator//lower.denominator
    hi = upper.numerator//upper.denominator
    assert lo == hi, 'increase guard bits to certify constant floor'
    return lo


def generate():
    a, b = atan_bounds(5), atan_bounds(239)
    pi = certified_floor((16*a[0]-4*b[1], 16*a[1]-4*b[0]))
    ln2 = certified_floor(ln2_bounds())
    text = '// Generated by generate_math_constants.py using exact rational enclosures.\n'
    text += '#pragma once\n\n#include <array>\n#include <cstdint>\n\n'
    text += 'namespace ps::plugin_internal::numeric_ops {\n'
    for name, value in [('pi', pi), ('ln2', ln2)]:
        words = [(value >> (64*i)) & ((1 << 64)-1) for i in range(65)]
        text += f'inline constexpr std::array<std::uint64_t, 65> {name}_floor_4096 = {{{{\n'
        text += '\n'.join('    '+', '.join(f'UINT64_C(0x{x:016x})' for x in words[i:i+2])+',' for i in range(0,65,2))
        text += '\n}};\n'
    return text+'}  // namespace ps::plugin_internal::numeric_ops\n'


if __name__ == '__main__':
    destination = Path(__file__).resolve().parents[2] / 'plugins/ops/01-numeric/math_constants.hpp'
    text = generate()
    if '--check' in sys.argv:
        # Formatting is delegated to the repository's ClangFormat 21 tool.
        import re
        assert re.findall(r'0x[0-9a-f]+', destination.read_text()) == re.findall(r'0x[0-9a-f]+', text)
        print('4096-bit pi/ln2 constants certified by independent rational bounds')
    else:
        destination.write_text(text)
