#!/usr/bin/env python3
"""Regenerate independent FMT-10 finite-value oracles (stdlib, Python >=3.9).

Geometry uses Fraction + Gaussian elimination, not the production adjugate.
Final IEEE rounding uses integer quotient/remainder; it never goes via float.
Run from any directory; --check verifies the checked-in output without edits.
"""
from fractions import Fraction as F
from pathlib import Path
import textwrap
import argparse
import random
import struct

PRESETS = [
    (.64,.33,.30,.60,.15,.06,.3127,.3290),
    (.68,.32,.265,.69,.15,.06,.3127,.3290),
    (.708,.292,.170,.797,.131,.046,.3127,.3290),
    (.64,.33,.21,.71,.15,.06,.3127,.3290),
    (.734699,.265301,.159597,.840403,.036598,.000105,.3457,.3585),
    (.73470,.26530,0.,1.,.00010,-.077,.32168,.33767),
    (.713,.293,.165,.830,.128,.044,.32168,.33767),
    (1.,0.,0.,1.,0.,0.,.25,.25),  # exact diagonal, legal y=0
    (1.,0.,0.,1.,0.,0.,.5,.25),
    (.5,.25,.5+2.**-45,.25,.125,.25+2.**-45,.3125,.34375),
]
H = [
    [F(int(i % 4 == 0)) for i in range(9)],
    list(map(F, ['.8951','.2664','-.1614','-.7502','1.7135','.0367','.0389','-.0685','1.0296'])),
    list(map(F, ['.7328','.4296','-.1624','-.7036','1.6975','.0061','.0030','.0136','.9834'])),
    list(map(F, ['.401288','.650173','-.051461','-.250268','1.204414','.045854','-.002079','.048952','.953127'])),
]

def solve(a, b):
    aug = [list(a[3*i:3*i+3]) + [b[i]] for i in range(3)]
    for j in range(3):
        pivot = next(i for i in range(j, 3) if aug[i][j])
        aug[j], aug[pivot] = aug[pivot], aug[j]
        scale = aug[j][j]
        aug[j] = [x/scale for x in aug[j]]
        for i in range(3):
            if i != j:
                scale = aug[i][j]
                aug[i] = [x-scale*y for x,y in zip(aug[i],aug[j])]
    return [aug[i][-1] for i in range(3)]

def inverse(a):
    columns = [solve(a, [F(int(i==j)) for i in range(3)]) for j in range(3)]
    return [columns[c][r] for r in range(3) for c in range(3)]

def mv(a,b):
    return [sum(a[3*r+c]*b[c] for c in range(3)) for r in range(3)]

def white(xy):
    x,y = map(F, xy)
    return [x/y,F(1),(1-x-y)/y]

def basis(v):
    x0,y0,x1,y1,x2,y2,wx,wy = map(F,v)
    p = [x0,x1,x2,y0,y1,y2,1-x0-y0,1-x1-y1,1-x2-y2]
    scale = solve(p,white((wx,wy)))
    assert all(scale)
    return [p[3*r+c]*scale[c] for r in range(3) for c in range(3)]

def adapt(source,target,method):
    h = H[method]
    s,t = mv(h,white(source)),mv(h,white(target))
    assert all(x > 0 for x in s+t)
    ih = inverse(h)
    return [sum(ih[3*r+j]*(t[j]/s[j])*h[3*j+c] for j in range(3))
            for r in range(3) for c in range(3)]

def decode(word,narrow):
    m,e,bias = (23,8,127) if narrow else (52,11,1023)
    fraction = word & ((1<<m)-1)
    exponent = (word>>m) & ((1<<e)-1)
    assert exponent != (1<<e)-1
    if exponent:
        fraction |= 1<<m
    value = F(fraction)*F(2)**((exponent or 1)-bias-m)
    return -value if word>>(m+e) else value

def round_bits(value,narrow):
    m,e,bias = (23,8,127) if narrow else (52,11,1023)
    sign = (1 << (m+e)) if value < 0 else 0
    n,d = abs(value.numerator),value.denominator
    if not n:
        return 0
    exponent = n.bit_length()-d.bit_length()
    if F(n,d) < F(2)**exponent:
        exponent -= 1
    shift = max(exponent,1-bias)-m
    if shift < 0:
        n <<= -shift
    else:
        d <<= shift
    q,rem = divmod(n,d)
    if 2*rem > d or (2*rem == d and q&1):
        q += 1
    if q >= (1 << (m+1)):
        q >>= 1
        exponent += 1
    if exponent > bias:
        return sign | (((1<<e)-1)<<m)
    if q < (1<<m):
        return sign | q
    exponent = max(exponent,1-bias)
    return sign | ((exponent+bias)<<m) | (q-(1<<m))

def raw(x,narrow):
    return int.from_bytes(struct.pack('>f' if narrow else '>d',x),'big')

def generate():
    matrices = [(0,i,0,basis(v)) for i,v in enumerate(PRESETS)]
    matrices += [(1,i,0,inverse(basis(v))) for i,v in enumerate(PRESETS)]
    matrices += [(2,0,m,adapt((.25,.25),(.5,.25),m)) for m in range(4)]
    matrices += [(2,1,m,adapt((.3127,.3290),(.3457,.3585),m)) for m in range(4)]
    rng = random.Random(0xF0710)
    lines = ['// Generated by generate_fmt10_oracles.py; do not hand edit.',
             '#pragma once', '#include <array>', '#include <cstdint>',
             'namespace fmt10_oracle {', 'struct Case {',
             '  unsigned member, basis, method;', '  bool narrow;',
             '  std::array<std::uint64_t, 3> input, expected;', '};',
             'inline const std::array<std::array<double, 8>, 10> geometry{{']
    for v in PRESETS:
        row = ', '.join(float(x).hex() for x in v) + '}},'
        lines.extend(textwrap.wrap(
            row, width=80, initial_indent='    {{', subsequent_indent='      ',
            break_long_words=False, break_on_hyphens=False))
    lines += ['}};', 'inline const Case cases[] = {']
    for member,index,method,a in matrices:
        for narrow in (True,False):
            width,m,expbits = (32,23,8) if narrow else (64,52,11)
            maxfin = (((1<<expbits)-2)<<m) | ((1<<m)-1)
            triples = [[raw(x,narrow) for x in v] for v in
                       [(0.,0.,0.),(-0.,-0.,-0.),(1.,1.,1.),(1.,0.,0.),
                        (0.,1.,0.),(0.,0.,1.),(-2.,.125,16.),(2.**-24,1.,-1.)]]
            triples += [[1,2,3],[(1<<(width-1))|1,0,0],[maxfin,maxfin,maxfin],
                        [maxfin,(1<<(width-1))|maxfin,1]]
            for _ in range(12):
                triple = []
                for j in range(3):
                    word = rng.getrandbits(width)
                    if ((word>>m)&((1<<expbits)-1)) == (1<<expbits)-1:
                        word ^= 1<<m
                    triple.append(word)
                triples.append(triple)
            for triple in triples:
                exact = mv(a,[decode(x,narrow) for x in triple])
                out = [round_bits(x,narrow) for x in exact]
                lines += [f'    {{{member},', f'     {index},',
                          f'     {method},', f'     {str(narrow).lower()},']
                for values, ending in ((triple, '}},'), (out, '}}},')):
                    words = [f'UINT64_C(0x{x:016x})' for x in values]
                    lines += ['     {{' + words[0] + ', ' + words[1] + ',',
                              '       ' + words[2] + ending]
    lines += ['};','}  // namespace fmt10_oracle','']
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).with_name('fmt10_oracles.hpp')
    text = generate()
    if args.check:
        if path.read_text() != text:
            raise SystemExit('FMT-10 oracle fixture differs; regenerate and review')
        print('FMT-10 independent Fraction oracle fixture is reproducible')
    else:
        path.write_text(text)
        print(path)
