import math
import unittest
from fractions import Fraction as F
import rng as r
import exact as e


class RandomOracleTests(unittest.TestCase):
    def test_three_external_known_answers(self):
        # External S07 Random123 KAT, not generated by this implementation.
        import json
        from pathlib import Path
        cases=json.loads(Path(__file__).with_name('philox4x64_kat.json').read_text())['cases']
        for case in cases:
            self.assertEqual(r.philox4x64(case['counter'],case['key']),
                             tuple(int(w,16) for w in case['words']))
    def test_counter_encoding(self):
        self.assertEqual(r.pack_counter(-1,0,7,2,3,5,9),(0xffffffff,5|(9<<32),3|(7<<32)|(2<<48),0))
        self.assertEqual(r.block(0,0,seed=-1),r.philox4x64(r.pack_counter(0,0),(r.MASK,0)))
    def test_counter_injective_supported_subset(self):
        counters={r.pack_counter(x,y,c,d,s,f,k) for x in (-1,0,1) for y in (-1,0) for c in (0,1) for d in (1,2) for s in (0,1) for f in (0,1) for k in (0,1)}
        self.assertEqual(len(counters),3*2*2**5)
    def test_counter_bounds_reject_aliases(self):
        for args in ({'x':1<<31,'y':0},{'x':0,'y':0,'frame':1<<32},{'x':0,'y':0,'channel':65536},{'x':0,'y':0,'draw':1<<32},{'x':0,'y':0,'stream':1<<32}):
            with self.assertRaises(ValueError):r.pack_counter(**args)
    def test_uniform_grid(self):
        for dtype,p in [('float32',24),('float64',53)]:
            for i in range(128):
                u=r.uniform(i,-3,2,dtype,seed=17)
                self.assertGreaterEqual(u,0);self.assertLess(u,1)
                self.assertEqual((F(u)*(1<<p)).denominator,1)
    def test_open_uniform_endpoints(self):
        self.assertEqual(r.open52(0,0),F(1,1<<53))
        self.assertEqual(r.open52(r.MASK,r.MASK),1-F(1,1<<53))
        self.assertEqual(r.halfopen53(r.MASK,r.MASK),1-F(1,1<<53))
    def test_gaussian_slot_mapping(self):
        u,v=r.gaussian_inputs(7,-2,3,seed=42)
        b=r.block(7,-2,3,domain=2,seed=42)
        self.assertEqual((u,v),(r.open52(b[0],b[1]),r.halfopen53(b[2],b[3])))
    def test_roi_order_invariance(self):
        coordinates=[(x,y) for y in range(-2,2) for x in range(-3,5)]
        forward={(x,y):e.float_bits(r.uniform(x,y,seed=9)) for x,y in coordinates}
        reverse={(x,y):e.float_bits(r.uniform(x,y,seed=9)) for x,y in reversed(coordinates)}
        self.assertEqual(forward,reverse)
        self.assertEqual({k:v for k,v in forward.items() if k[0]>=0},{k:e.float_bits(r.uniform(*k,seed=9)) for k in forward if k[0]>=0})
    def test_channel_frame_stream_domains(self):
        samples=[r.block(0,0,channel=1),r.block(0,0,frame=1),r.block(0,0,stream=1),r.block(0,0,domain=2),r.block(0,0)]
        self.assertEqual(len(set(samples)),len(samples)) # finite fixture, not an independence proof
    def test_jitter_zero_grid(self):
        self.assertEqual(r.jitter_points([0,0,4,3],4,3,0,seed=1),e.grid_points([0,0,4,3],4,3))
    def test_jitter_one_per_cell(self):
        pts=r.jitter_points([-2,-3,2,1],4,4,1,seed=12)
        for j in range(4):
            for i in range(4):
                x,y=pts[j*4+i]
                self.assertTrue(-2+i<=x<-1+i);self.assertTrue(-3+j<=y<-2+j)
    def test_rejection_spacing_and_prefix(self):
        a=r.rejection_points([0,0,3,3],F(1,2),100,seed=3)
        b=r.rejection_points([0,0,3,3],F(1,2),50,seed=3)
        self.assertTrue(r.pairwise_distances(a,F(1,2)));self.assertEqual(a[:len(b)],b)
    def test_rejection_empty_large_radius_capacity(self):
        self.assertEqual(r.rejection_points([0,0,1,1],3,0),[])
        self.assertEqual(len(r.rejection_points([0,0,1,1],3,20)),1)
        got=r.rejection_points([0,0,10,10],F(1,100),20,max_count=1,with_status=True)
        self.assertEqual(len(got['points']),1);self.assertEqual(got['stop_reason'],'count_reached')
    def test_measured_bridson_invariants(self):
        pts=r.bridson_reference([0,0,3,3],F(3,4),k=10,seed=1,max_count=100)
        self.assertTrue(r.pairwise_distances(pts,F(3,4)))
        self.assertTrue(all(0<=x<3 and 0<=y<3 for x,y in pts))
        self.assertEqual(pts,r.bridson_reference([0,0,3,3],F(3,4),k=10,seed=1,max_count=100))
    def test_measured_bridson_iteration_failure(self):
        with self.assertRaises(ArithmeticError):r.bridson_reference([0,0,2,2],F(1,4),max_iterations=0)
    def test_perlin_table_and_integer_lattice(self):
        self.assertEqual(sorted(r.PERM_2002),list(range(256)))
        for q in ((0,0,0),(1,-2,7),(256,256,256),(-1000,17,31)):
            self.assertEqual(r.perlin2002_fraction(q),0)
    def test_perlin_analytic_slice(self):
        # On (x,0,0), the published gradients give n=x-fade(x).
        for q in (F(1,4),F(1,2),F(3,4)):
            self.assertEqual(r.perlin2002_fraction((q,0,0)),q-r.fade(q))
    def test_perlin_periodic_and_range(self):
        for i in range(20):
            q=(F(i-7,8),F(i+2,7),F(3-i,9));v=r.perlin2002_fraction(q)
            self.assertEqual(v,r.perlin2002_fraction((q[0]+256,q[1]-256,q[2]+512)))
            self.assertLessEqual(abs(v),2)
    def test_seeded_gradient_periodic(self):
        for i in range(10):
            q=(F(i-5,7),F(i,3));kw={'period':(5,7),'seed':13}
            self.assertEqual(r.gradient2d_fraction(q,**kw),r.gradient2d_fraction((q[0]+5,q[1]-7),**kw))
        self.assertEqual(r.gradient2d_fraction((1,2)),0)
    def test_seeded_gradient_edge_domain(self):
        with self.assertRaises(ValueError):r.gradient2d_fraction(((1<<31)-1,F(1,2)))
    def test_cellular_search_certificate(self):
        for p in ((F(1,4),F(3,8)),(F(-5,4),F(7,8)),(0,0)):
            got=r.cellular2d(p,seed=5)
            self.assertLessEqual(got['f1'],got['f2'])
            self.assertGreater(got['unvisited_lower2'],got['distance2'][1])
            ix,iy=(v//1 for v in p)
            brute=sorted((r.distance2(p,r.cellular_feature(x,y,seed=5)),y,x) for y in range(iy-4,iy+5) for x in range(ix-4,ix+5))
            self.assertEqual(got['distance2'],(brute[0][0],brute[1][0]))
            self.assertEqual(got['cell'],(brute[0][2],brute[0][1]))
    def test_cellular_insufficient_rings(self):
        with self.assertRaises(ArithmeticError):r.cellular2d((F(1,2),F(1,2)),max_search_rings=0)
    def test_fractal_one_octave_and_gain_zero(self):
        q=(F(2,7),F(-3,8));base=r.gradient2d_fraction(q)
        self.assertEqual(r.fractal_fraction(q,octaves=1),base)
        self.assertEqual(r.fractal_fraction(q,octaves=32,gain=0),base)
    def test_fractal_variants(self):
        q=(F(2,7),F(-3,8));n=r.gradient2d_fraction(q)
        self.assertEqual(r.fractal_fraction(q,kind='turbulence',octaves=1),abs(n))
        self.assertEqual(r.fractal_fraction(q,kind='ridged',octaves=1),(1-abs(n)/2)**2)
        self.assertEqual(r.fractal_fraction((0,0),kind='ridged'),1)
    def test_footprint_non_amplifying_cutoff(self):
        q=(F(2,7),F(3,8))
        self.assertEqual(r.fractal_fraction(q,footprint=0),r.fractal_fraction(q))
        self.assertEqual(r.fractal_fraction(q,footprint=1),0)
    def test_temporal_fixed_field(self):
        p=(F(1,4),F(1,3))
        self.assertEqual(r.advected_fraction(p,(0,0),19),r.gradient2d_fraction(p))
        self.assertEqual(r.advected_fraction(p,(1,2),F(1,4)),r.gradient2d_fraction((0,F(-1,6))))
        self.assertEqual(r.temporal_fraction(p,0),r.temporal_fraction(p,256))
    def test_poisson_speckle_slots(self):
        u=r.poisson_input(0,0);b=r.block(0,0,domain=8)
        self.assertEqual(u,r.open52(b[0],b[1]))
        self.assertNotEqual(r.block(0,0,domain=9,draw=0),r.block(0,0,domain=9,draw=1))


if __name__=='__main__':unittest.main()
