include_guard(GLOBAL)

function(photospider_add_result_table_fixture target source)
  cmake_parse_arguments(PS "BAD" "" "" ${ARGN})
  add_library(${target} MODULE "${source}")
  target_link_libraries(${target} PRIVATE Photospider::operation_sdk)
  set_target_properties(${target} PROPERTIES C_STANDARD 11
    C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
  if(PS_BAD)
    target_compile_definitions(${target} PRIVATE PS_RESULT_BAD_TABLES=1)
  endif()
endfunction()

# Test modules use the same instrumentation as their host. Mach-O C modules
# need an atexit owner to retire compiler-rt image globals before dlclose unmaps
# the image; the generated mod_term_func destructor alone is not sufficient.
function(photospider_configure_test_module target sanitizer)
  if(sanitizer STREQUAL "none")
    return()
  endif()
  target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer}" -fno-omit-frame-pointer)
  target_link_options(${target} PRIVATE "-fsanitize=${sanitizer}")
  if(APPLE AND sanitizer STREQUAL "address")
    target_sources(${target} PRIVATE
      "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/support/asan_module_retirement.cpp")
  endif()
endfunction()

# One registration declares execution, build dependencies and semantic labels.
function(photospider_register_test)
  cmake_parse_arguments(PS "CORE" "NAME;TARGET;TIMEOUT;SKIP_RETURN_CODE" "COMMAND;SOURCES;FIXTURES;DEPENDENCIES;LABELS" ${ARGN})
  if(NOT PS_NAME)
    message(FATAL_ERROR "Behavior test requires NAME")
  endif()
  if(PS_SOURCES)
    if(NOT PS_TARGET)
      set(PS_TARGET ${PS_NAME})
    endif()
    add_executable(${PS_TARGET} ${PS_SOURCES})
  endif()
  if(NOT PS_COMMAND)
    set(PS_COMMAND ${PS_TARGET})
  endif()
  if(NOT PS_TARGET)
    list(GET PS_COMMAND 0 _command)
    if(TARGET ${_command})
      set(PS_TARGET ${_command})
    endif()
  endif()
  if(PS_TARGET)
    if(PS_FIXTURES OR PS_DEPENDENCIES)
      add_dependencies(${PS_TARGET} ${PS_FIXTURES} ${PS_DEPENDENCIES})
    endif()
    get_target_property(_sources ${PS_TARGET} SOURCES)
    set_property(GLOBAL APPEND PROPERTY PHOTOSPIDER_BEHAVIOR_TARGETS ${PS_TARGET})
  endif()
  add_test(NAME ${PS_NAME} COMMAND ${PS_COMMAND})
  set(_labels ${PS_LABELS})
  set(_timeout 300)
  if(_sources MATCHES "tests/unit/|^../unit/")
    list(APPEND _labels unit)
    set(_timeout 120)
  else()
    list(APPEND _labels integration)
  endif()
  if(PS_NAME MATCHES "numeric|ordered_|scan_|matrix|arithmetic")
    list(APPEND _labels numeric)
    set(_timeout 600)
  endif()
  if(PS_NAME MATCHES "image|alpha|color|channel|model|transfer|rgb|perlin|gaussian|sampling|inpaint")
    list(APPEND _labels image)
    set(_timeout 600)
  endif()
  if(PS_NAME MATCHES "execution|dependency|result|cache|scheduler|cancel|resource|shared|binding|memory")
    list(APPEND _labels execution)
  endif()
  if(PS_NAME MATCHES "plugin|_c_|_c11|repeated|expression|contract|package|consumer|sdk")
    list(APPEND _labels abi)
  endif()
  if(PS_NAME MATCHES "gpu|metal|vulkan|native")
    list(APPEND _labels gpu)
  endif()
  if(PS_NAME MATCHES "^installed_")
    list(APPEND _labels installed)
    set_property(GLOBAL APPEND PROPERTY PHOTOSPIDER_INSTALLED_TARGETS ${PS_TARGET})
    if(PS_CORE)
      list(APPEND _labels package_core)
      set_property(GLOBAL APPEND PROPERTY PHOTOSPIDER_CORE_TARGETS ${PS_TARGET})
    endif()
  elseif(PS_NAME STREQUAL "test_installed_consumer")
    list(APPEND _labels installed)
    set(_timeout 1800)
  endif()
  if(PS_TIMEOUT)
    set(_timeout ${PS_TIMEOUT})
  endif()
  if((DEFINED PHOTOSPIDER_SANITIZER_MODE AND NOT PHOTOSPIDER_SANITIZER_MODE STREQUAL "none") OR
     (DEFINED PHOTOSPIDER_CONSUMER_SANITIZER AND NOT PHOTOSPIDER_CONSUMER_SANITIZER STREQUAL "none"))
    math(EXPR _timeout "${_timeout} * 3")
  endif()
  list(REMOVE_DUPLICATES _labels)
  set_tests_properties(${PS_NAME} PROPERTIES LABELS "${_labels}" TIMEOUT ${_timeout})
  if(DEFINED PS_SKIP_RETURN_CODE AND NOT PS_SKIP_RETURN_CODE STREQUAL "")
    set_tests_properties(${PS_NAME} PROPERTIES SKIP_RETURN_CODE ${PS_SKIP_RETURN_CODE})
  endif()
endfunction()

# DSO paths are declared once in compile definitions. Their target references
# also declare the fixture build dependency, including later negative cases.
function(photospider_finalize_behavior_targets)
  get_property(_targets GLOBAL PROPERTY PHOTOSPIDER_BEHAVIOR_TARGETS)
  list(REMOVE_DUPLICATES _targets)
  foreach(_target IN LISTS _targets)
    get_target_property(_definitions ${_target} COMPILE_DEFINITIONS)
    string(REGEX MATCHALL "\\$<TARGET_FILE:[^>]+>" _references "${_definitions}")
    foreach(_reference IN LISTS _references)
      string(REGEX REPLACE "^\\$<TARGET_FILE:([^>]+)>$" "\\1" _fixture "${_reference}")
      if(NOT TARGET ${_fixture})
        message(FATAL_ERROR "${_target} references missing fixture ${_fixture}")
      endif()
      add_dependencies(${_target} ${_fixture})
    endforeach()
  endforeach()
endfunction()
